// EthernetEcho
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:59:11
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable EthernetEcho.exe

#include "EthernetEcho.h"

// opath operation: 10: cgen2

 void EthernetEcho::exe012()
 { 
  //  Method no 0 mname=EthernetEcho
    if (xpc10nz==22/*22:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void EthernetEcho::exe112()
 { 
  //  Method no 1 mname=EthernetEcho
    if (rx_sof_n&&xpc10nz==21/*21:xpc10nz*/)
    xpc10nz = (22/*22:xpc10nz*/);
}

 void EthernetEcho::exe212()
 { 
  //  Method no 2 mname=EthernetEcho
    if (!rx_sof_n&&xpc10nz==21/*21:xpc10nz*/)
    xpc10nz = (22/*22:xpc10nz*/);
}

 void EthernetEcho::exe310()
 { 
  //  Method no 3 mname=EthernetEcho
    if (xpc10nz==20/*20:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void EthernetEcho::exe410()
 { 
  //  Method no 4 mname=EthernetEcho
    if (xpc10nz==19/*19:xpc10nz*/)
    xpc10nz = (20/*20:xpc10nz*/);
}

 void EthernetEcho::exe510()
 { 
  //  Method no 5 mname=EthernetEcho
    if (xpc10nz==18/*18:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void EthernetEcho::exe610()
 { 
  //  Method no 6 mname=EthernetEcho
    if (xpc10nz==17/*17:xpc10nz*/)
    xpc10nz = (8/*8:xpc10nz*/);
}

 void EthernetEcho::exe710()
 { 
  //  Method no 7 mname=EthernetEcho
    if (xpc10nz==16/*16:xpc10nz*/)
    xpc10nz = (10/*10:xpc10nz*/);
}

 void EthernetEcho::exe810()
 { 
  //  Method no 8 mname=EthernetEcho
    if (xpc10nz==15/*15:xpc10nz*/)
    xpc10nz = (16/*16:xpc10nz*/);
}

 void EthernetEcho::exe910()
 { 
  //  Method no 9 mname=EthernetEcho
    if (xpc10nz==14/*14:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void EthernetEcho::exe1010()
 { 
  //  Method no 10 mname=EthernetEcho
    if (xpc10nz==13/*13:xpc10nz*/)
    xpc10nz = (15/*15:xpc10nz*/);
}

 void EthernetEcho::exe1110()
 { 
  //  Method no 11 mname=EthernetEcho
    if (xpc10nz==12/*12:xpc10nz*/)
    xpc10nz = (13/*13:xpc10nz*/);
}

 void EthernetEcho::exe1210()
 { 
  //  Method no 12 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2!=-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==10/*10:xpc10nz*/)
    xpc10nz = (12/*12:xpc10nz*/);
}

 void EthernetEcho::exe1310()
 { 
  //  Method no 13 mname=EthernetEcho
    if (xpc10nz==11/*11:xpc10nz*/)
    xpc10nz = (15/*15:xpc10nz*/);
}

 void EthernetEcho::exe1410()
 { 
  //  Method no 14 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2==-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==10/*10:xpc10nz*/)
    xpc10nz = (11/*11:xpc10nz*/);
}

 void EthernetEcho::exe1510()
 { 
  //  Method no 15 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2>=T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==10/*10:xpc10nz*/)
    xpc10nz = (14/*14:xpc10nz*/);
}

 void EthernetEcho::exe1610()
 { 
  //  Method no 16 mname=EthernetEcho
    if (xpc10nz==9/*9:xpc10nz*/)
    xpc10nz = (17/*17:xpc10nz*/);
}

 void EthernetEcho::exe1710()
 { 
  //  Method no 17 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<6&&xpc10nz==8/*8:xpc10nz*/)
    xpc10nz = (9/*9:xpc10nz*/);
}

 void EthernetEcho::exe1810()
 { 
  //  Method no 18 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2>=6&&xpc10nz==8/*8:xpc10nz*/)
    xpc10nz = (10/*10:xpc10nz*/);
}

 void EthernetEcho::exe1910()
 { 
  //  Method no 19 mname=EthernetEcho
    if (xpc10nz==7/*7:xpc10nz*/)
    xpc10nz = (18/*18:xpc10nz*/);
}

 void EthernetEcho::exe2010()
 { 
  //  Method no 20 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<12&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (7/*7:xpc10nz*/);
}

 void EthernetEcho::exe2110()
 { 
  //  Method no 21 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2>=12&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (8/*8:xpc10nz*/);
}

 void EthernetEcho::exe2210()
 { 
  //  Method no 22 mname=EthernetEcho
    if (rx_src_rdy_n&&!T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (19/*19:xpc10nz*/);
}

 void EthernetEcho::exe2310()
 { 
  //  Method no 23 mname=EthernetEcho
    if (xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (19/*19:xpc10nz*/);
}

 void EthernetEcho::exe2410()
 { 
  //  Method no 24 mname=EthernetEcho
    if (!rx_src_rdy_n&&!T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void EthernetEcho::exe2510()
 { 
  //  Method no 25 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void EthernetEcho::exe2610()
 { 
  //  Method no 26 mname=EthernetEcho
    if (!T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_0&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (21/*21:xpc10nz*/);
}

 void EthernetEcho::exe2710()
 { 
  //  Method no 27 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_0&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void EthernetEcho::exe2810()
 { 
  //  Method no 28 mname=EthernetEcho
    if (xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void EthernetEcho::exe2910()
 { 
  //  Method no 29 mname=EthernetEcho
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void EthernetEcho::exe3010()
 { 
  //  Method no 30 mname=EthernetEcho
    if (rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void EthernetEcho::exe3110()
 { 
  //  Method no 31 mname=EthernetEcho
    if (!rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void EthernetEcho::exe3210()
 { 
  //  Method no 32 mname=EthernetEcho
    Z8USCCSCALbx10ARA0RRh10shot0 = ((T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2!=-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==12/*12:xpc10nz*/)||(T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<12&&xpc10nz==6/*6:xpc10nz*/)||(T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<6&&xpc10nz==8/*8:xpc10nz*/)||(T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2==-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==10/*10:xpc10nz*/));
}

 void EthernetEcho::exe3310()
 { 
  //  Method no 33 mname=EthernetEcho
    _8_US_CC_SCALbx10_ARA0_WEN0 = (!rx_src_rdy_n&&!T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/);
}

 void EthernetEcho::exe3410()
 { 
  //  Method no 34 mname=EthernetEcho
    _8_US_CC_SCALbx10_ARA0_REN0 = ((T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2==-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==10/*10:xpc10nz*/)||(T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<6&&xpc10nz==8/*8:xpc10nz*/)||(T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<12&&xpc10nz==6/*6:xpc10nz*/)||(T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2!=-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==12/*12:xpc10nz*/));
}

 void EthernetEcho::exe3510()
 { 
  //  Method no 35 mname=EthernetEcho
    if (Z8USCCSCALbx10ARA0RRh10shot0)
    Z8USCCSCALbx10ARA0RRh10hold = (_8_US_CC_SCALbx10_ARA0_RDD0);
}

 void EthernetEcho::exe3610()
 { 
  //  Method no 36 mname=EthernetEcho
    if (Z8USCCSCALbx10ARA0RRh10shot0)
    Z8USCCSCALbx10ARA0RRh10hold = (_8_US_CC_SCALbx10_ARA0_RDD0);
}

 void EthernetEcho::exe3710()
 { 
  //  Method no 37 mname=EthernetEcho
    if (Z8USCCSCALbx10ARA0RRh10shot0)
    Z8USCCSCALbx10ARA0RRh10hold = (_8_US_CC_SCALbx10_ARA0_RDD0);
}

 void EthernetEcho::exe3810()
 { 
  //  Method no 38 mname=EthernetEcho
    if (Z8USCCSCALbx10ARA0RRh10shot0)
    Z8USCCSCALbx10ARA0RRh10hold = (_8_US_CC_SCALbx10_ARA0_RDD0);
}

 void EthernetEcho::exe3910()
 { 
  //  Method no 39 mname=EthernetEcho
    if (rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1__SPILL_256 = (0);
}

 void EthernetEcho::exe4010()
 { 
  //  Method no 40 mname=EthernetEcho
    if (rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    tx_eof_n = (0x1);
}

 void EthernetEcho::exe4110()
 { 
  //  Method no 41 mname=EthernetEcho
    if (rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    tx_src_rdy_n = (0x1);
}

 void EthernetEcho::exe4210()
 { 
  //  Method no 42 mname=EthernetEcho
    if (rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    tx_sof_n = (0x1);
}

 void EthernetEcho::exe4310()
 { 
  //  Method no 43 mname=EthernetEcho
    if (!rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1__SPILL_256 = ((int)(0==rx_src_rdy_n));
}

 void EthernetEcho::exe4410()
 { 
  //  Method no 44 mname=EthernetEcho
    if (!rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    tx_eof_n = (0x1);
}

 void EthernetEcho::exe4510()
 { 
  //  Method no 45 mname=EthernetEcho
    if (!rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    tx_src_rdy_n = (0x1);
}

 void EthernetEcho::exe4610()
 { 
  //  Method no 46 mname=EthernetEcho
    if (!rx_sof_n&&xpc10nz==0/*0:xpc10nz*/)
    tx_sof_n = (0x1);
}

 void EthernetEcho::exe4710()
 { 
  //  Method no 47 mname=EthernetEcho
    if (xpc10nz==1/*1:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_0 = ((sc_uint<1>)(T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1__SPILL_256));
}

 void EthernetEcho::exe4810()
 { 
  //  Method no 48 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_0&&xpc10nz==3/*3:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3 = (0x0);
}

 void EthernetEcho::exe4910()
 { 
  //  Method no 49 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_0&&xpc10nz==3/*3:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1 = (0);
}

 void EthernetEcho::exe5010()
 { 
  //  Method no 50 mname=EthernetEcho
    if (!rx_src_rdy_n&&!T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1 = (1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1);
}

 void EthernetEcho::exe5110()
 { 
  //  Method no 51 mname=EthernetEcho
    if (!rx_src_rdy_n&&!T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/)
    _8_US_CC_SCALbx10_ARA0_WRD0 = ((unsigned char)(rx_data));
}

 void EthernetEcho::exe5210()
 { 
  //  Method no 52 mname=EthernetEcho
    if (!rx_src_rdy_n&&!T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/)
    _8_US_CC_SCALbx10_ARA0_AD0 = (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1);
}

 void EthernetEcho::exe5310()
 { 
  //  Method no 53 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/)
    tx_src_rdy_n = (0x0);
}

 void EthernetEcho::exe5410()
 { 
  //  Method no 54 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/)
    tx_sof_n = (0x1);
}

 void EthernetEcho::exe5510()
 { 
  //  Method no 55 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3&&xpc10nz==4/*4:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2 = (6);
}

 void EthernetEcho::exe5610()
 { 
  //  Method no 56 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<12&&xpc10nz==6/*6:xpc10nz*/)
    _8_US_CC_SCALbx10_ARA0_AD0 = (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2);
}

 void EthernetEcho::exe5710()
 { 
  //  Method no 57 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<12&&xpc10nz==7/*7:xpc10nz*/)
    tx_sof_n = (0/*0:USA10*/==6==T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2);
}

 void EthernetEcho::exe5810()
 { 
  //  Method no 58 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<12&&xpc10nz==7/*7:xpc10nz*/)
    tx_data = ((unsigned char)(((xpc10nz==7/*7:xpc10nz*/)?_8_US_CC_SCALbx10_ARA0_RDD0:Z8USCCSCALbx10ARA0RRh10hold)));
}

 void EthernetEcho::exe5910()
 { 
  //  Method no 59 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2>=12&&xpc10nz==6/*6:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2 = (0);
}

 void EthernetEcho::exe6010()
 { 
  //  Method no 60 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<6&&xpc10nz==8/*8:xpc10nz*/)
    _8_US_CC_SCALbx10_ARA0_AD0 = (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2);
}

 void EthernetEcho::exe6110()
 { 
  //  Method no 61 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<6&&xpc10nz==9/*9:xpc10nz*/)
    tx_data = ((unsigned char)(((xpc10nz==9/*9:xpc10nz*/)?_8_US_CC_SCALbx10_ARA0_RDD0:Z8USCCSCALbx10ARA0RRh10hold)));
}

 void EthernetEcho::exe6210()
 { 
  //  Method no 62 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2>=6&&xpc10nz==8/*8:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2 = (12);
}

 void EthernetEcho::exe6310()
 { 
  //  Method no 63 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2!=-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==12/*12:xpc10nz*/)
    _8_US_CC_SCALbx10_ARA0_AD0 = (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2);
}

 void EthernetEcho::exe6410()
 { 
  //  Method no 64 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2!=-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==13/*13:xpc10nz*/)
    tx_data = ((unsigned char)(((xpc10nz==13/*13:xpc10nz*/)?_8_US_CC_SCALbx10_ARA0_RDD0:Z8USCCSCALbx10ARA0RRh10hold)));
}

 void EthernetEcho::exe6510()
 { 
  //  Method no 65 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2==-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==10/*10:xpc10nz*/)
    _8_US_CC_SCALbx10_ARA0_AD0 = (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2);
}

 void EthernetEcho::exe6610()
 { 
  //  Method no 66 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2==-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==11/*11:xpc10nz*/)
    tx_eof_n = (0x0);
}

 void EthernetEcho::exe6710()
 { 
  //  Method no 67 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2<T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2==-1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==11/*11:xpc10nz*/)
    tx_data = ((unsigned char)(((xpc10nz==11/*11:xpc10nz*/)?_8_US_CC_SCALbx10_ARA0_RDD0:Z8USCCSCALbx10ARA0RRh10hold)));
}

 void EthernetEcho::exe6810()
 { 
  //  Method no 68 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2>=T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==10/*10:xpc10nz*/)
    tx_eof_n = (0x1);
}

 void EthernetEcho::exe6910()
 { 
  //  Method no 69 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2>=T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==10/*10:xpc10nz*/)
    tx_src_rdy_n = (0x1);
}

 void EthernetEcho::exe7010()
 { 
  //  Method no 70 mname=EthernetEcho
    if (T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2>=T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_1&&xpc10nz==10/*10:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_0 = (0x0);
}

 void EthernetEcho::exe7110()
 { 
  //  Method no 71 mname=EthernetEcho
    if (xpc10nz==15/*15:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2 = (1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2);
}

 void EthernetEcho::exe7210()
 { 
  //  Method no 72 mname=EthernetEcho
    if (xpc10nz==17/*17:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2 = (1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2);
}

 void EthernetEcho::exe7310()
 { 
  //  Method no 73 mname=EthernetEcho
    if (xpc10nz==18/*18:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2 = (1+T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_2);
}

 void EthernetEcho::exe7410()
 { 
  //  Method no 74 mname=EthernetEcho
    if (xpc10nz==19/*19:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_3 = (!rx_eof_n);
}

 void EthernetEcho::exe7510()
 { 
  //  Method no 75 mname=EthernetEcho
    if (rx_sof_n&&xpc10nz==21/*21:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1__SPILL_257 = (0);
}

 void EthernetEcho::exe7610()
 { 
  //  Method no 76 mname=EthernetEcho
    if (!rx_sof_n&&xpc10nz==21/*21:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1__SPILL_257 = ((int)(0==rx_src_rdy_n));
}

 void EthernetEcho::exe7710()
 { 
  //  Method no 77 mname=EthernetEcho
    if (xpc10nz==22/*22:xpc10nz*/)
    T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1_V_0 = ((sc_uint<1>)(T404_LocalLinkLoopBackTest_EthernetEcho_echo_1_1__SPILL_257));
}

 void EthernetEcho::exe010()
 { 
  //  Method no 0 mname=@8_US/CC/SCALbx10_ARA0.RAM
    if (_8_US_CC_SCALbx10_ARA0_WEN0)
    _8_US_CC_SCALbx10_ARA0[_8_US_CC_SCALbx10_ARA0_AD0] = (_8_US_CC_SCALbx10_ARA0_WRD0);
}

 void EthernetEcho::exe110()
 { 
  //  Method no 1 mname=@8_US/CC/SCALbx10_ARA0.RAM
    _8_US_CC_SCALbx10_ARA0_RDD0 = (_8_US_CC_SCALbx10_ARA0[_8_US_CC_SCALbx10_ARA0_AD0]);
}

 void EthernetEcho::exe210()
 { 
  //  Method no 2 mname=@8_US/CC/SCALbx10_ARA0.RAM
// Resource=SRAM iname=i_@8_US/CC/SCALbx10_ARA0 1024x8 clk=posedge(clk) synchronous/pipeline=1 no_ports=1 <NONE> used by threads xpc10
}
// eof EthernetEcho
