// LocalLinkLoopBackTest_EthernetEcho
// Generated by CBG Orangepath HPR/LS
// 8/3/2011 11:12:29 AM
//  /home/djg11/d320/hprls/kiwic/distro/lib/kiwic.exe -report-each-step -csharp-gen=enable -gtrace-loglevel=0 -firstpass-loglevel=0 EthernetEcho.exe

using SystemCsharp;
// opath operation: 8: csharp-gen

public class  LocalLinkLoopBackTest_EthernetEcho  : sc_module
{
  public sc_signal TLEec1_1_V_0;
  public sc_signal TLEec1_1_V_1;
  public sc_signal TLEec1_1_V_2;
  public sc_signal TLEec1_1_V_3;
  public sc_signal mpc10;
  public sc_signal DRSX8US_AX_CC_SOL_QC_SOL_AD0;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr28;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc40;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr26;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc38;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr24;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc36;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr22;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc34;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr20;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc32;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr18;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc30;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr16;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc28;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr14;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc26;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr12;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc24;
  public sc_signal DRSXUSAXCCSOLQCSOLholdr10;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc22;
  public sc_signal mpc10zz;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc20;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc16;
  public sc_signal DRSXUSAXCCSOLQCSOLholdc10;
  public sc_in < byte > rx_data;
  public sc_in < bool > rx_sof_n;
  public sc_in < bool > rx_eof_n;
  public sc_in < bool > rx_src_rdy_n;
  public sc_out  < byte > tx_data;
  public sc_out  < bool > tx_sof_n;
  public sc_out  < bool > tx_eof_n;
  public sc_out  < bool > tx_src_rdy_n;
  public sc_in < bool > tx_dst_rdy_n;
  byte []DRSX8US_AX_CC_SOL_QC_SOL = new byte [ 1024];
  public sc_in < bool > clk;
  public sc_signal DRSX8US_AX_CC_SOL_QC_SOL_RDD0;
  public sc_signal DRSX8US_AX_CC_SOL_QC_SOL_registered_AD0;
  public sc_signal DRSX8US_AX_CC_SOL_QC_SOL_WEN0;
  public sc_signal DRSX8US_AX_CC_SOL_QC_SOL_REN0;
  public sc_signal DRSX8US_AX_CC_SOL_QC_SOL_WRD0;

  public LocalLinkLoopBackTest_EthernetEcho( string name)  :    base("LocalLinkLoopBackTest_EthernetEcho")
   { 
      clk = (new sc_in<bool>(this, "clk"));
      rx_data = (new sc_in<byte>(this, "rx_data"));
      rx_sof_n = (new sc_in<bool>(this, "rx_sof_n"));
      rx_eof_n = (new sc_in<bool>(this, "rx_eof_n"));
      rx_src_rdy_n = (new sc_in<bool>(this, "rx_src_rdy_n"));
      tx_data = (new sc_out<byte>(this, "tx_data"));
      tx_sof_n = (new sc_out<bool>(this, "tx_sof_n"));
      tx_eof_n = (new sc_out<bool>(this, "tx_eof_n"));
      tx_src_rdy_n = (new sc_out<bool>(this, "tx_src_rdy_n"));
      tx_dst_rdy_n = (new sc_in<bool>(this, "tx_dst_rdy_n"));
      TLEec1_1_V_0 = (new sc_signal(1, "TLEec1_1_V_0"));
      TLEec1_1_V_1 = (new sc_signal(32, "TLEec1_1_V_1"));
      TLEec1_1_V_2 = (new sc_signal(32, "TLEec1_1_V_2"));
      TLEec1_1_V_3 = (new sc_signal(1, "TLEec1_1_V_3"));
      mpc10 = (new sc_signal(32, "mpc10"));
      DRSX8US_AX_CC_SOL_QC_SOL_AD0 = (new sc_signal(32, "DRSX8US_AX_CC_SOL_QC_SOL_AD0"));
      DRSXUSAXCCSOLQCSOLholdr28 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr28"));
      DRSXUSAXCCSOLQCSOLholdc40 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc40"));
      DRSXUSAXCCSOLQCSOLholdr26 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr26"));
      DRSXUSAXCCSOLQCSOLholdc38 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc38"));
      DRSXUSAXCCSOLQCSOLholdr24 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr24"));
      DRSXUSAXCCSOLQCSOLholdc36 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc36"));
      DRSXUSAXCCSOLQCSOLholdr22 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr22"));
      DRSXUSAXCCSOLQCSOLholdc34 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc34"));
      DRSXUSAXCCSOLQCSOLholdr20 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr20"));
      DRSXUSAXCCSOLQCSOLholdc32 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc32"));
      DRSXUSAXCCSOLQCSOLholdr18 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr18"));
      DRSXUSAXCCSOLQCSOLholdc30 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc30"));
      DRSXUSAXCCSOLQCSOLholdr16 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr16"));
      DRSXUSAXCCSOLQCSOLholdc28 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc28"));
      DRSXUSAXCCSOLQCSOLholdr14 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr14"));
      DRSXUSAXCCSOLQCSOLholdc26 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc26"));
      DRSXUSAXCCSOLQCSOLholdr12 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr12"));
      DRSXUSAXCCSOLQCSOLholdc24 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc24"));
      DRSXUSAXCCSOLQCSOLholdr10 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdr10"));
      DRSXUSAXCCSOLQCSOLholdc22 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc22"));
      mpc10zz = (new sc_signal(4, "mpc10zz"));
      DRSXUSAXCCSOLQCSOLholdc20 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc20"));
      DRSXUSAXCCSOLQCSOLholdc16 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc16"));
      DRSXUSAXCCSOLQCSOLholdc10 = (new sc_signal(8, "DRSXUSAXCCSOLQCSOLholdc10"));
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe18)).sensitive_pos(clk);
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe16)).sensitive_pos(clk);
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe14));
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe12)).sensitive(DRSX8US_AX_CC_SOL_QC_SOL).sensitive(DRSX8US_AX_CC_SOL_QC_SOL_registered_AD0);
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe10)).sensitive_pos(clk);
  }

   void exe16()
   { 
    //  Method no 0 mname=LocalLinkLoopBackTest_EthernetEcho
      DRSX8US_AX_CC_SOL_QC_SOL_registered_AD0.Write(DRSX8US_AX_CC_SOL_QC_SOL_AD0.Read());
  }

   void exe18()
   { 
    //  Method no 1 mname=LocalLinkLoopBackTest_EthernetEcho
      switch (mpc10zz.Read())     {
 
    case 0:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow(0);
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow(0);
      mpc10zz.Write(1/*1:mpc10zz*/);

    }
    break;
    case 1:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow(((((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?6:((rx_sof_n.Read()!=0L)||((rx_src_rdy_n.Read())!=(0)))?0:0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WRD0.WriteNow(((((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0)))))?rx_data.Read():0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(((((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0)))))?((((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0)))))?1:0:0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow(0);
      mpc10zz.Write(((((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?3/*3:mpc10zz*/:((rx_sof_n.Read()!=0L)||((rx_src_rdy_n.Read())!=(0)))?2/*2:mpc10zz*/:mpc10zz.Read());
      TLEec1_1_V_0.Write((!((rx_sof_n.Read()!=0L)))?(((rx_src_rdy_n.Read())==(0)))?1:0:(!((rx_sof_n.Read()!=0L)))?TLEec1_1_V_0.Read():0);
      TLEec1_1_V_1.Write(((rx_sof_n.Read()!=0L)||!(((rx_src_rdy_n.Read())==(0))))?TLEec1_1_V_1.Read():((((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0)))))?1:0);
      TLEec1_1_V_3.Write(((((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?(((rx_eof_n.Read())==(0)))?1:0:TLEec1_1_V_3.Read());
      mpc10.Write(((rx_sof_n.Read()!=0L)||((rx_src_rdy_n.Read())!=(0)))?1/*1:mpc10XS:":pcIS189:AG"*/:((((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?2/*2:mpc10XS:":pcIS239:AG"*/:mpc10.Read());
      tx_src_rdy_n.Write(1);
      tx_eof_n.Write(1);
      tx_sof_n.Write(1);

    }
    break;
    case 2:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow(((((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?6:((rx_sof_n.Read()!=0L)||!(((rx_src_rdy_n.Read())==(0))))?0:0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WRD0.WriteNow(((((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0)))))?rx_data.Read():0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(((((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0)))))?((((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0)))))?1:0:0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow(0);
      mpc10zz.Write(((((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?3/*3:mpc10zz*/:((rx_sof_n.Read()!=0L)||!(((rx_src_rdy_n.Read())==(0))))?2/*2:mpc10zz*/:mpc10zz.Read());
      TLEec1_1_V_0.Write((!((rx_sof_n.Read()!=0L)))?(((rx_src_rdy_n.Read())==(0)))?1:0:(!((rx_sof_n.Read()!=0L)))?TLEec1_1_V_0.Read():0);
      TLEec1_1_V_1.Write(((rx_sof_n.Read()!=0L)||!(((rx_src_rdy_n.Read())==(0))))?TLEec1_1_V_1.Read():((((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0)))))?1:0);
      TLEec1_1_V_3.Write(((((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?(((rx_eof_n.Read())==(0)))?1:0:TLEec1_1_V_3.Read());
      mpc10.Write(((((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?2/*2:mpc10XS:":pcIS239:AG"*/:mpc10.Read());

    }
    break;
    case 3:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow(TLEec1_1_V_1.Read());
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(0);
      DRSXUSAXCCSOLQCSOLholdc36.WriteNow(DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read());
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow(1);
      mpc10zz.Write(4/*4:mpc10zz*/);
      DRSXUSAXCCSOLQCSOLholdr24.Write(DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read());
      DRSXUSAXCCSOLQCSOLholdc20.Write(DRSXUSAXCCSOLQCSOLholdc36.Read());

    }
    break;
    case 4:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow(((TLEec1_1_V_3.Read()!=0L))?0:(!((TLEec1_1_V_3.Read()!=0L)))?6:0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WRD0.WriteNow(((((TLEec1_1_V_3.Read()!=0L))?false:!((rx_src_rdy_n.Read()!=0L))))?rx_data.Read():0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(((((TLEec1_1_V_3.Read()!=0L))?false:!((rx_src_rdy_n.Read()!=0L))))?((((TLEec1_1_V_3.Read()!=0L))?false:!((rx_src_rdy_n.Read()!=0L))))?1:0:0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow(0);
      mpc10zz.Write(((TLEec1_1_V_3.Read()!=0L))?5/*5:mpc10zz*/:(!((TLEec1_1_V_3.Read()!=0L)))?3/*3:mpc10zz*/:mpc10zz.Read());
      TLEec1_1_V_1.Write(((((TLEec1_1_V_3.Read()!=0L))?false:!((rx_src_rdy_n.Read()!=0L))))?1+TLEec1_1_V_1.Read():TLEec1_1_V_1.Read());
      TLEec1_1_V_3.Write((!((TLEec1_1_V_3.Read()!=0L)))?(((rx_eof_n.Read())==(0)))?1:0:TLEec1_1_V_3.Read());
      mpc10.Write(((TLEec1_1_V_3.Read()!=0L))?4/*4:mpc10XS:":pcIS257:AG"*/:mpc10.Read());
      tx_src_rdy_n.Write((!((TLEec1_1_V_3.Read()!=0L)))?tx_src_rdy_n.Read():((TLEec1_1_V_3.Read()!=0L))?0:1);
      tx_data.Write(((TLEec1_1_V_3.Read()!=0L))?DRSXUSAXCCSOLQCSOLholdc20.Read():tx_data.Read());
      TLEec1_1_V_2.Write((!((TLEec1_1_V_3.Read()!=0L)))?TLEec1_1_V_2.Read():((TLEec1_1_V_3.Read()!=0L))?6:12);
      tx_sof_n.Write((!((TLEec1_1_V_3.Read()!=0L)))?tx_sof_n.Read():0);

    }
    break;
    case 5:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow(1+TLEec1_1_V_2.Read());
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow(1);
      DRSXUSAXCCSOLQCSOLholdc32.WriteNow(DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read());
      mpc10zz.Write(6/*6:mpc10zz*/);
      DRSXUSAXCCSOLQCSOLholdr20.Write(DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read());
      DRSXUSAXCCSOLQCSOLholdc16.Write(DRSXUSAXCCSOLQCSOLholdc32.Read());

    }
    break;
    case 6:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow((((TLEec1_1_V_2.Read())>=(11)))?12:(((TLEec1_1_V_2.Read())<(11)))?0:0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow((((TLEec1_1_V_2.Read())<(11)))?(((TLEec1_1_V_2.Read())<(11)))?1:0:0);
      DRSXUSAXCCSOLQCSOLholdc30.WriteNow((((TLEec1_1_V_2.Read())<(11)))?DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read():0/*UNDEF*/);
      mpc10zz.Write((((TLEec1_1_V_2.Read())>=(11)))?7/*7:mpc10zz*/:(((TLEec1_1_V_2.Read())<(11)))?5/*5:mpc10zz*/:mpc10zz.Read());
      DRSXUSAXCCSOLQCSOLholdr18.Write((((TLEec1_1_V_2.Read())<(11)))?DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read():DRSXUSAXCCSOLQCSOLholdr18.Read());
      mpc10.Write((((TLEec1_1_V_2.Read())>=(11)))?8/*8:mpc10XS:":pcIS272:AG"*/:mpc10.Read());
      tx_data.Write((((TLEec1_1_V_2.Read())<(11)))?DRSXUSAXCCSOLQCSOLholdc30.Read():(((TLEec1_1_V_2.Read())>=(11)))?DRSXUSAXCCSOLQCSOLholdc16.Read():tx_data.Read());
      TLEec1_1_V_2.Write((((TLEec1_1_V_2.Read())<(11)))?1+TLEec1_1_V_2.Read():(!(((TLEec1_1_V_2.Read())>=(11))))?TLEec1_1_V_2.Read():(((TLEec1_1_V_2.Read())>=(11)))?0:12);
      tx_sof_n.Write((((TLEec1_1_V_2.Read())<(11)))?(((TLEec1_1_V_2.Read())!=(5)))?1:0:tx_sof_n.Read());

    }
    break;
    case 7:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow(1+TLEec1_1_V_2.Read());
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow(1);
      DRSXUSAXCCSOLQCSOLholdc28.WriteNow(DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read());
      mpc10zz.Write(8/*8:mpc10zz*/);
      DRSXUSAXCCSOLQCSOLholdr16.Write(DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read());
      DRSXUSAXCCSOLQCSOLholdc10.Write(DRSXUSAXCCSOLQCSOLholdc28.Read());

    }
    break;
    case 8:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow((((TLEec1_1_V_2.Read())>=(5))&&((((TLEec1_1_V_1.Read())!=(13)))?((TLEec1_1_V_1.Read())>=(13)):true))?13:(((TLEec1_1_V_2.Read())>=(5))&&!(((TLEec1_1_V_1.Read())<(13))))?12:(((TLEec1_1_V_2.Read())>=(5))&&((TLEec1_1_V_1.Read())<(13)))?0:(((TLEec1_1_V_2.Read())<(5)))?12:0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow((((TLEec1_1_V_2.Read())<(5)))?(((TLEec1_1_V_2.Read())<(5)))?1:0:0);
      DRSXUSAXCCSOLQCSOLholdc26.WriteNow((((TLEec1_1_V_2.Read())<(5)))?DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read():0/*UNDEF*/);
      mpc10zz.Write((((TLEec1_1_V_2.Read())>=(5))&&((TLEec1_1_V_1.Read())<(13)))?10/*10:mpc10zz*/:(((TLEec1_1_V_2.Read())>=(5))&&((TLEec1_1_V_1.Read())==(13))||((TLEec1_1_V_1.Read())>=(13)))?9/*9:mpc10zz*/:(((TLEec1_1_V_2.Read())<(5)))?7/*7:mpc10zz*/:mpc10zz.Read());
      DRSXUSAXCCSOLQCSOLholdr14.Write((((TLEec1_1_V_2.Read())<(5)))?DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read():DRSXUSAXCCSOLQCSOLholdr14.Read());
      TLEec1_1_V_0.Write((((((TLEec1_1_V_2.Read())>=(5)))?!(((TLEec1_1_V_1.Read())<(13))):true))?TLEec1_1_V_0.Read():0);
      mpc10.Write((((TLEec1_1_V_2.Read())>=(5))&&((((TLEec1_1_V_1.Read())!=(13)))?((TLEec1_1_V_1.Read())>=(13)):true))?16/*16:mpc10XS:":pcIS303:AG"*/:(((TLEec1_1_V_2.Read())>=(5))&&((TLEec1_1_V_1.Read())<(13)))?32/*32:mpc10XS:":pcIS311:AG"*/:mpc10.Read());
      tx_src_rdy_n.Write((((((TLEec1_1_V_2.Read())>=(5)))?!(((TLEec1_1_V_1.Read())<(13))):true))?tx_src_rdy_n.Read():1);
      tx_eof_n.Write((((((TLEec1_1_V_2.Read())>=(5)))?((((TLEec1_1_V_1.Read())==(13)))?false:!(((TLEec1_1_V_1.Read())<(13)))):true))?tx_eof_n.Read():(((TLEec1_1_V_2.Read())>=(5))&&((TLEec1_1_V_1.Read())==(13)))?0:1);
      tx_data.Write((((TLEec1_1_V_2.Read())<(5)))?DRSXUSAXCCSOLQCSOLholdc26.Read():(((TLEec1_1_V_2.Read())>=(5))&&((((TLEec1_1_V_1.Read())!=(13)))?((TLEec1_1_V_1.Read())>=(13)):true))?DRSXUSAXCCSOLQCSOLholdc10.Read():tx_data.Read());
      TLEec1_1_V_2.Write((((TLEec1_1_V_2.Read())<(5)))?1+TLEec1_1_V_2.Read():(!(((TLEec1_1_V_2.Read())>=(5))))?TLEec1_1_V_2.Read():(((TLEec1_1_V_2.Read())>=(5))&&((((TLEec1_1_V_1.Read())!=(13)))?((TLEec1_1_V_1.Read())>=(13)):true))?13:12);

    }
    break;
    case 9:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow((TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?1+TLEec1_1_V_2.Read():(TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?TLEec1_1_V_2.Read():(TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?12:(!(TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read()))?0:0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow((TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?(TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?1:0:0);
      DRSXUSAXCCSOLQCSOLholdc24.WriteNow((TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read():0/*UNDEF*/);
      mpc10zz.Write((!(TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read()))?10/*10:mpc10zz*/:(TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?9/*9:mpc10zz*/:mpc10zz.Read());
      DRSXUSAXCCSOLQCSOLholdr12.Write((TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Read():DRSXUSAXCCSOLQCSOLholdr12.Read());
      TLEec1_1_V_0.Write((TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?TLEec1_1_V_0.Read():0);
      mpc10.Write((!(TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read()))?32/*32:mpc10XS:":pcIS311:AG"*/:mpc10.Read());
      tx_src_rdy_n.Write((TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?tx_src_rdy_n.Read():1);
      tx_eof_n.Write((TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read()&&!(TLEec1_1_V_2.Read()==-1+TLEec1_1_V_1.Read()))?tx_eof_n.Read():(TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read()&&TLEec1_1_V_2.Read()==-1+TLEec1_1_V_1.Read())?0:1);
      tx_data.Write((TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?DRSXUSAXCCSOLQCSOLholdc24.Read():tx_data.Read());
      TLEec1_1_V_2.Write((TLEec1_1_V_2.Read()<TLEec1_1_V_1.Read())?1+TLEec1_1_V_2.Read():TLEec1_1_V_2.Read());

    }
    break;
    case 10:
    
    {      DRSX8US_AX_CC_SOL_QC_SOL_AD0.WriteNow(((TLEec1_1_V_0.Read()!=0L)||(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?6:((((TLEec1_1_V_0.Read()!=0L))?false:(rx_sof_n.Read()!=0L)||((rx_src_rdy_n.Read())!=(0))))?0:0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WRD0.WriteNow(((((TLEec1_1_V_0.Read()!=0L))?!((rx_src_rdy_n.Read()!=0L)):(((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))))?rx_data.Read():0/*UNDEF*/);
      DRSX8US_AX_CC_SOL_QC_SOL_WEN0.WriteNow(((((TLEec1_1_V_0.Read()!=0L))?!((rx_src_rdy_n.Read()!=0L)):(((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))))?((((TLEec1_1_V_0.Read()!=0L))?!((rx_src_rdy_n.Read()!=0L)):(((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))))?1:0:0);
      DRSX8US_AX_CC_SOL_QC_SOL_REN0.WriteNow(0);
      mpc10zz.Write(((TLEec1_1_V_0.Read()!=0L)||(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?3/*3:mpc10zz*/:((((TLEec1_1_V_0.Read()!=0L))?false:(rx_sof_n.Read()!=0L)||((rx_src_rdy_n.Read())!=(0))))?2/*2:mpc10zz*/:mpc10zz.Read());
      TLEec1_1_V_0.Write(((((TLEec1_1_V_0.Read()!=0L))?false:!((rx_sof_n.Read()!=0L))))?(((rx_src_rdy_n.Read())==(0)))?1:0:((TLEec1_1_V_0.Read()!=0L)||!((rx_sof_n.Read()!=0L)))?TLEec1_1_V_0.Read():0);
      TLEec1_1_V_1.Write(((((TLEec1_1_V_0.Read()!=0L))?false:(rx_sof_n.Read()!=0L)||!(((rx_src_rdy_n.Read())==(0)))))?TLEec1_1_V_1.Read():((TLEec1_1_V_0.Read()!=0L)&&!((rx_src_rdy_n.Read()!=0L)))?1:((TLEec1_1_V_0.Read()!=0L)&&(rx_src_rdy_n.Read()!=0L))?0:((((TLEec1_1_V_0.Read()!=0L))?false:(((rx_src_rdy_n.Read()!=0L))?false:(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))))?1:0);
      TLEec1_1_V_3.Write(((TLEec1_1_V_0.Read()!=0L)||(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?(((rx_eof_n.Read())==(0)))?1:0:TLEec1_1_V_3.Read());
      mpc10.Write(((((TLEec1_1_V_0.Read()!=0L))?false:(rx_sof_n.Read()!=0L)||((rx_src_rdy_n.Read())!=(0))))?1/*1:mpc10XS:":pcIS189:AG"*/:((TLEec1_1_V_0.Read()!=0L)||(((rx_sof_n.Read()!=0L))?false:((rx_src_rdy_n.Read())==(0))))?2/*2:mpc10XS:":pcIS239:AG"*/:mpc10.Read());

    }
    break; }  }

   void exe10()
   { 
    //  Method no 0 mname=DRSX8US_AX/CC/SOL/QC/SOL.RAM
      if ((DRSX8US_AX_CC_SOL_QC_SOL_WEN0.Read()!=0L))
      DRSX8US_AX_CC_SOL_QC_SOL[DRSX8US_AX_CC_SOL_QC_SOL_registered_AD0] = (DRSX8US_AX_CC_SOL_QC_SOL_WRD0.Read());
  }

   void exe12()
   { 
    //  Method no 1 mname=DRSX8US_AX/CC/SOL/QC/SOL.RAM
      DRSX8US_AX_CC_SOL_QC_SOL_RDD0.Write(DRSX8US_AX_CC_SOL_QC_SOL[DRSX8US_AX_CC_SOL_QC_SOL_registered_AD0.Read()]);
  }

   void exe14()
   { 
    //  Method no 2 mname=DRSX8US_AX/CC/SOL/QC/SOL.RAM
// SRAM i_DRSX8US_AX/CC/SOL/QC/SOL 1024x8 clk=clk synchronous/pipeline=1 ports=1 
  }
};

// eof LocalLinkLoopBackTest_EthernetEcho
