// test49
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:56:50
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test49.exe -sim 1800 -diosim-tl=100 -diosim-vcd=test49.vcd -vnl-rootmodname=DUT -vnl-resets=synchronous -vnl=test49.v -res2-loadstore-port-count=0 -bevelab-default-pause-mode=hard -give-backtrace -report-each-step

#ifndef test49_H
#define test49_H
#define HPR_NEEDS_SYSTEMC 1
#include "hprls.h"
// opath operation: 10: cgen2

struct  test49  : public sc_module
{
  unsigned int test49_volx;
  unsigned int T403_test49_test49_phase1_0_6_V_2_GP;
  unsigned int T403_test49_test49_phase1_0_6_V_1_GP;
  unsigned INT64 T403_test49_test49_phase0_0_5_V_1;
  unsigned int T403_test49_test49_phase0_0_5_V_2;
  unsigned int T403_test49_test49_phase0_0_5_V_3;
  unsigned INT64 __FPD_CC_SCALbx10_ARA0[6];
  sc_uint<5> xpc10nz;
  unsigned INT64 fpcvt10RRh10hold;
  sc_uint<1> fpcvt10RRh10shot0;
  sc_uint<1> fpcvt10RRh10shot1;
  unsigned INT64 CVFPMULTIPLIER10RRh10hold;
  sc_uint<1> CVFPMULTIPLIER10RRh10shot0;
  sc_uint<1> CVFPMULTIPLIER10RRh10shot1;
  sc_uint<1> CVFPMULTIPLIER10RRh10shot2;
  unsigned int fpcvt12RRh10hold;
  sc_uint<1> fpcvt12RRh10shot0;
  sc_uint<1> fpcvt12RRh10shot1;
  unsigned int fpcvt14RRh10hold;
  sc_uint<1> fpcvt14RRh10shot0;
  sc_uint<1> fpcvt14RRh10shot1;
  unsigned int CVFPMULTIPLIER12RRh10hold;
  sc_uint<1> CVFPMULTIPLIER12RRh10shot0;
  sc_uint<1> CVFPMULTIPLIER12RRh10shot1;
  sc_uint<1> CVFPMULTIPLIER12RRh10shot2;
  unsigned INT64 fpcvt16RRh10hold;
  sc_uint<1> fpcvt16RRh10shot0;
  sc_uint<1> fpcvt16RRh10shot1;
  unsigned INT64 CVFPMULTIPLIER14RRh10hold;
  sc_uint<1> CVFPMULTIPLIER14RRh10shot0;
  sc_uint<1> CVFPMULTIPLIER14RRh10shot1;
  sc_uint<1> CVFPMULTIPLIER14RRh10shot2;
  unsigned INT64 CVFPMULTIPLIER16RRh10hold;
  sc_uint<1> CVFPMULTIPLIER16RRh10shot0;
  sc_uint<1> CVFPMULTIPLIER16RRh10shot1;
  sc_uint<1> CVFPMULTIPLIER16RRh10shot2;
  unsigned INT64 CVFPADDER10RRh10hold;
  sc_uint<1> CVFPADDER10RRh10shot0;
  sc_uint<1> CVFPADDER10RRh10shot1;
  sc_uint<1> CVFPADDER10RRh10shot2;
  sc_uint<1> CVFPADDER10RRh10shot3;
  unsigned INT64 CVFPADDER12RRh10hold;
  sc_uint<1> CVFPADDER12RRh10shot0;
  sc_uint<1> CVFPADDER12RRh10shot1;
  sc_uint<1> CVFPADDER12RRh10shot2;
  sc_uint<1> CVFPADDER12RRh10shot3;
  unsigned INT64 CVFPDIVIDER10RRh10hold;
  sc_uint<1> CVFPDIVIDER10RRh10shot0;
  sc_uint<1> CVFPDIVIDER10RRh10shot1;
  sc_uint<1> CVFPDIVIDER10RRh10shot2;
  sc_uint<1> CVFPDIVIDER10RRh10shot3;
  sc_uint<1> CVFPDIVIDER10RRh10shot4;
  unsigned INT64 CVFPADDER120_PR10;
  unsigned INT64 CVFPADDER121_PR12;
  unsigned INT64 CVFPADDER122_PR14;
  unsigned INT64 CVFPADDER12_FPRR;
  unsigned INT64 CVFPADDER12_A0;
  unsigned INT64 CVFPADDER12_A1;
  sc_uint<1> CVFPADDER12_fail;
  unsigned INT64 CVFPDIVIDER100_PR16;
  unsigned INT64 CVFPDIVIDER101_PR18;
  unsigned INT64 CVFPDIVIDER102_PR20;
  unsigned INT64 CVFPDIVIDER103_PR22;
  unsigned INT64 CVFPDIVIDER10_FPRR;
  unsigned INT64 CVFPDIVIDER10_NN;
  unsigned INT64 CVFPDIVIDER10_DD;
  sc_uint<1> CVFPDIVIDER10_fail;
  unsigned INT64 CVFPADDER100_PR24;
  unsigned INT64 CVFPADDER101_PR26;
  unsigned INT64 CVFPADDER102_PR28;
  unsigned INT64 CVFPADDER10_FPRR;
  unsigned INT64 CVFPADDER10_A0;
  unsigned INT64 CVFPADDER10_A1;
  sc_uint<1> CVFPADDER10_fail;
  unsigned INT64 CVFPMULTIPLIER160_PR30;
  unsigned INT64 CVFPMULTIPLIER161_PR32;
  unsigned INT64 CVFPMULTIPLIER16_FPRR;
  unsigned INT64 CVFPMULTIPLIER16_A0;
  unsigned INT64 CVFPMULTIPLIER16_A1;
  sc_uint<1> CVFPMULTIPLIER16_fail;
  unsigned INT64 CVFPMULTIPLIER140_PR34;
  unsigned INT64 CVFPMULTIPLIER141_PR36;
  unsigned INT64 CVFPMULTIPLIER14_FPRR;
  unsigned INT64 CVFPMULTIPLIER14_A0;
  unsigned INT64 CVFPMULTIPLIER14_A1;
  sc_uint<1> CVFPMULTIPLIER14_fail;
  unsigned INT64 fpcvt16_midpt;
  unsigned INT64 fpcvt16_result;
  unsigned int fpcvt16_arg;
  sc_uint<1> fpcvt16_fail;
  unsigned int CVFPMULTIPLIER120_PR38;
  unsigned int CVFPMULTIPLIER121_PR40;
  unsigned int CVFPMULTIPLIER12_FPRR;
  unsigned int CVFPMULTIPLIER12_A0;
  unsigned int CVFPMULTIPLIER12_A1;
  sc_uint<1> CVFPMULTIPLIER12_fail;
  unsigned int fpcvt14_midpt;
  unsigned int fpcvt14_result;
  unsigned int fpcvt14_arg;
  sc_uint<1> fpcvt14_fail;
  unsigned int fpcvt12_midpt;
  unsigned int fpcvt12_result;
  unsigned int fpcvt12_arg;
  sc_uint<1> fpcvt12_fail;
  unsigned INT64 CVFPMULTIPLIER100_PR42;
  unsigned INT64 CVFPMULTIPLIER101_PR44;
  sc_in < sc_uint<1> > reset;
  unsigned INT64 CVFPMULTIPLIER10_FPRR;
  unsigned INT64 CVFPMULTIPLIER10_A0;
  unsigned INT64 CVFPMULTIPLIER10_A1;
  sc_uint<1> CVFPMULTIPLIER10_fail;
  unsigned INT64 fpcvt10_midpt;
  sc_in < sc_uint<1> > clk;
  unsigned INT64 fpcvt10_result;
  unsigned int fpcvt10_arg;
  sc_uint<1> fpcvt10_fail;

  test49( sc_core::sc_module_name name)  :    sc_core::sc_module("test49")
   { 
       SC_HAS_PROCESS(test49);
SC_METHOD(new SystemCsharp.sc_method_t(exe13610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe13510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe13410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe13310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe13210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe13110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe13010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe12010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe11010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe10010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe412)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe316)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe224)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe132)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe032)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe314)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe222)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe130)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe030)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe312)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe220)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe128)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe028)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe218)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe126)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe026)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe216)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe124)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe024)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe214)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe122)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe022)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe120)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe020)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe212)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe118)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe018)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe116)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe016)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe114)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe014)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe112)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe012)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe010)).sensitive_pos(clk);
  }

   void exe032();

   void exe132();

   void exe224();

   void exe316();

   void exe412();

   void exe510();

   void exe610();

   void exe710();

   void exe810();

   void exe910();

   void exe1010();

   void exe1110();

   void exe1210();

   void exe1310();

   void exe1410();

   void exe1510();

   void exe1610();

   void exe1710();

   void exe1810();

   void exe1910();

   void exe2010();

   void exe2110();

   void exe2210();

   void exe2310();

   void exe2410();

   void exe2510();

   void exe2610();

   void exe2710();

   void exe2810();

   void exe2910();

   void exe3010();

   void exe3110();

   void exe3210();

   void exe3310();

   void exe3410();

   void exe3510();

   void exe3610();

   void exe3710();

   void exe3810();

   void exe3910();

   void exe4010();

   void exe4110();

   void exe4210();

   void exe4310();

   void exe4410();

   void exe4510();

   void exe4610();

   void exe4710();

   void exe4810();

   void exe4910();

   void exe5010();

   void exe5110();

   void exe5210();

   void exe5310();

   void exe5410();

   void exe5510();

   void exe5610();

   void exe5710();

   void exe5810();

   void exe5910();

   void exe6010();

   void exe6110();

   void exe6210();

   void exe6310();

   void exe6410();

   void exe6510();

   void exe6610();

   void exe6710();

   void exe6810();

   void exe6910();

   void exe7010();

   void exe7110();

   void exe7210();

   void exe7310();

   void exe7410();

   void exe7510();

   void exe7610();

   void exe7710();

   void exe7810();

   void exe7910();

   void exe8010();

   void exe8110();

   void exe8210();

   void exe8310();

   void exe8410();

   void exe8510();

   void exe8610();

   void exe8710();

   void exe8810();

   void exe8910();

   void exe9010();

   void exe9110();

   void exe9210();

   void exe9310();

   void exe9410();

   void exe9510();

   void exe9610();

   void exe9710();

   void exe9810();

   void exe9910();

   void exe10010();

   void exe10110();

   void exe10210();

   void exe10310();

   void exe10410();

   void exe10510();

   void exe10610();

   void exe10710();

   void exe10810();

   void exe10910();

   void exe11010();

   void exe11110();

   void exe11210();

   void exe11310();

   void exe11410();

   void exe11510();

   void exe11610();

   void exe11710();

   void exe11810();

   void exe11910();

   void exe12010();

   void exe12110();

   void exe12210();

   void exe12310();

   void exe12410();

   void exe12510();

   void exe12610();

   void exe12710();

   void exe12810();

   void exe12910();

   void exe13010();

   void exe13110();

   void exe13210();

   void exe13310();

   void exe13410();

   void exe13510();

   void exe13610();

   void exe030();

   void exe130();

   void exe222();

   void exe314();

   void exe028();

   void exe128();

   void exe220();

   void exe312();

   void exe410();

   void exe026();

   void exe126();

   void exe218();

   void exe310();

   void exe024();

   void exe124();

   void exe216();

   void exe022();

   void exe122();

   void exe214();

   void exe020();

   void exe120();

   void exe018();

   void exe118();

   void exe212();

   void exe016();

   void exe116();

   void exe014();

   void exe114();

   void exe012();

   void exe112();

   void exe210();

   void exe010();

   void exe110();
};

#endif
// eof test49
