// tester7
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:50:05
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test7.exe -conerefine=disable -bevelab=disable -verilog-gen=disable -sim 1800 -kiwic-cil-dump=combined -kiwic-kcode-dump=enable -give-backtrace -report-each-step

#include "tester7.h"

// opath operation: 10: cgen2

 int tester7::exe010()
 { 
  //  Method no 0 mname=tester7
    /*skip*/;  // End of static elaboration for tid T402. After all generate loops are unwound we arrive here: 0
  T402_0:
    /*skip*/;    tester7_limit = (8);
    goto DESTWASCOMMENT14;
    goto DESTWASCOMMENT14;
  DESTWASCOMMENT14:
    /*skip*/;  // End of static elaboration for tid T401. After all generate loops are unwound we arrive here: 0
  T401_0:
    /*skip*/;    System_BitConverter_IsLittleEndian = (0x1);
    goto DESTWASCOMMENT12;
    goto DESTWASCOMMENT12;
  DESTWASCOMMENT12:
    /*skip*/;  // End of static elaboration for tid T400. After all generate loops are unwound we arrive here: 0
  T400_0:
    /*skip*/;    KiwiSystem_Kiwi_old_pausemode_value = (0x2);
    KiwiSystem_Kiwi_tnow = (0x0);
    goto DESTWASCOMMENT10;
    goto DESTWASCOMMENT10;
  DESTWASCOMMENT10:
    /*skip*/;    tester7_test7_overrides_CZ:0:2_blockrefxxnewobj10 = (d1.0);
    T403_tester7_test7_overrides_0_3_V_0 = (d1.0);
    tester7_test7_overrides_CZ:0:4_blockrefxxnewobj12 = (d2.0);
    T403_tester7_test7_overrides_0_3_V_1 = (d2.0);
    tester7_test7_overrides_CZ:0:6_blockrefxxnewobj14 = (d3.0);
    T403_tester7_test7_overrides_0_3_V_2 = (d3.0);
hpr_writeln("%s%i", "Test7_overrides Up To ", 8);
    T403_tester7_test7_overrides_0_3_V_3 = (1);
    /*skip*/;    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (1);
    /*skip*/;    /*skip*/;    /*skip*/;hpr_write("%i%s", 1, " ");
    T403_test7lower_edict_4_6_V_0 = ("+");
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (2);
    /*skip*/;    /*skip*/;hpr_write("%i%s", 2, " ");
    T403_test7lower_edict_4_6_V_0 = ("+");
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (3);
    /*skip*/;    /*skip*/;hpr_write("%i%s", 3, " ");
    T403_test7lower_edict_4_6_V_0 = ("+");
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (4);
    /*skip*/;    /*skip*/;hpr_write("%i%s", 4, " ");
    T403_test7lower_edict_4_6_V_0 = ("+");
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (5);
    /*skip*/;    /*skip*/;hpr_write("%i%s", 5, " ");
    T403_test7lower_edict_4_6_V_0 = ("+");
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (6);
    /*skip*/;    /*skip*/;hpr_write("%i%s", 6, " ");
    T403_test7lower_edict_4_6_V_0 = ("+");
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (7);
    /*skip*/;    /*skip*/;hpr_write("%i%s", 7, " ");
  // Site of a conditional branch to LL38
hpr_writeln(" BAR");
    T403_test7lower_edict_3_6_V_0 = ("+");
    /*skip*/;    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (8);
    /*skip*/;    /*skip*/;hpr_write("%i%s", 8, " ");
    T403_test7lower_edict_4_6_V_0 = ("+");
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (9);
    /*skip*/;  // End of static elaboration for tid T403. After all generate loops are unwound we arrive here: 31
  T403_31:
    /*skip*/;wait(8);
    T403_tester7_test7_overrides_0_3_V_3 = (1+T403_tester7_test7_overrides_0_3_V_3);
    goto T403_34;
  T403_34:
    /*skip*/;    if (!(8<T403_tester7_test7_overrides_0_3_V_3)) goto T403_10;
    goto T403_35;
  T403_35:
    /*skip*/;hpr_writeln("Test7 method overload test done");
hpr_writeln("Test7 static override test start");
    T403_tester7_test7_overrides_0_3_V_3 = (0);
    goto T403_61;
  T403_61:
    /*skip*/;    if (!(T403_tester7_test7_overrides_0_3_V_3>=2)) goto T403_40;
    goto T403_62;
  T403_62:
    /*skip*/;hpr_writeln("Test7 static override test done");
    T403_tester7_test7_overrides_0_3_V_3 = (0);
    goto T403_87;
  T403_87:
    /*skip*/;    if (!(T403_tester7_test7_overrides_0_3_V_3>=3)) goto T403_66;
    goto T403_88;
  T403_88:
    /*skip*/;hpr_writeln("Test7 dynamic override test done");
    tester7_test7_fv_CZ:0:2_blockrefxxnewobj16a = (d8.0);
    __SINT_CC_MAPR10NoCE0_fv = (2);
    T403_tester7_test7_fv_0_4_V_0a = (d8.0);
    tester7_test7_fv_CZ:0:4_blockrefxxnewobj18a = (d9.1);
    __SINT_CC_MAPR10NoCE1_fv = (2);
    T403_tester7_test7_fv_0_4_V_1a = (d9.1);
    __SINT_CC_MAPR10NoCE1_fv = (400);
    T403_tester7_test7_fv_0_4_V_2_GP = (0);
    goto T403_116;
  T403_116:
    /*skip*/;    if (!(T403_tester7_test7_fv_0_4_V_2_GP>=4)) goto T403_99;
    goto T403_117;
  T403_117:
    /*skip*/;hpr_writeln("test7_fv done");
    return (0);
    return (1);
  T403_99:
    /*skip*/;wait(8);
    if (!(2==T403_tester7_test7_fv_0_4_V_2_GP)) goto T403_104;
    goto T403_101;
  T403_101:
    /*skip*/;    T403_tester7_test7_fv_0_4__SPILL_256a = (d9.1);
    goto T403_106;
  T403_104:
    /*skip*/;    T403_tester7_test7_fv_0_4__SPILL_256a = (d8.0);
    goto T403_106;
  T403_106:
    /*skip*/;    T403_tester7_test7_fv_0_4_V_3a = (T403_tester7_test7_fv_0_4__SPILL_256a);
    fastspilldup10a = (T403_tester7_test7_fv_0_4_V_3a);

  {    if (fastspilldup10a==1/*1:fastspilldup10*/)
    __SINT_CC_MAPR10NoCE1_fv = (1+(((fastspilldup10a==1/*1:fastspilldup10*/)?__SINT_CC_MAPR10NoCE1_fv:((fastspilldup10a==0/*0:fastspilldup10*/)?__SINT_CC_MAPR10NoCE0_fv:0/*UNDEF*/))));
    if (fastspilldup10a==0/*0:fastspilldup10*/)
    __SINT_CC_MAPR10NoCE0_fv = (1+(((fastspilldup10a==1/*1:fastspilldup10*/)?__SINT_CC_MAPR10NoCE1_fv:((fastspilldup10a==0/*0:fastspilldup10*/)?__SINT_CC_MAPR10NoCE0_fv:0/*UNDEF*/))));

  }
    T403_test7fv_module_incbyfv_4_5_V_0_GP = (101+(((T403_tester7_test7_fv_0_4_V_3a==1/*1:T403/tester7/test7_fv/0.4/V_3*/)?__SINT_CC_MAPR10NoCE1_fv:((T403_tester7_test7_fv_0_4_V_3a==0/*0:T403/tester7/test7_fv/0.4/V_3*/)?__SINT_CC_MAPR10NoCE0_fv:0/*UNDEF*/))));
    goto T403_112;
  T403_112:
    /*skip*/;    T403_tester7_test7_fv_0_4_V_4 = ((int)(T403_test7fv_module_incbyfv_4_5_V_0_GP));
hpr_writeln("   test7_fv %u result %u", T403_tester7_test7_fv_0_4_V_2_GP, T403_tester7_test7_fv_0_4_V_4);
    T403_tester7_test7_fv_0_4_V_2_GP = (1+T403_tester7_test7_fv_0_4_V_2_GP);
    goto T403_116;
  T403_66:
    /*skip*/;wait(8);
    if (!(0==T403_tester7_test7_overrides_0_3_V_3)) goto T403_71;
    goto T403_68;
  T403_68:
    /*skip*/;    T403_tester7_test7_overrides_0_3__SPILL_256 = (d1.0);
    goto T403_77;
  T403_71:
    /*skip*/;    if (!(1==T403_tester7_test7_overrides_0_3_V_3)) goto T403_75;
    goto T403_72;
  T403_72:
    /*skip*/;    T403_tester7_test7_overrides_0_3__SPILL_256 = (d2.0);
    goto T403_77;
  T403_75:
    /*skip*/;    T403_tester7_test7_overrides_0_3__SPILL_256 = (d3.0);
    goto T403_77;
  T403_77:
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_8 = (T403_tester7_test7_overrides_0_3__SPILL_256);
wait(8);
hpr_writeln("Test7 is broken at the moment and this gldsim file is likewise wrong to fake the test as passing.");
    T403_tester7_test7_fv_0_4_V_2_GP = (112);
    goto T403_83;
  T403_83:
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_9 = (112);
hpr_writeln("Test7 dynamic i=%u px=%u", T403_tester7_test7_overrides_0_3_V_3, 112);
    T403_tester7_test7_overrides_0_3_V_3 = (1+T403_tester7_test7_overrides_0_3_V_3);
    goto T403_87;
  T403_40:
    /*skip*/;wait(8);
hpr_writeln("Test7 is broken at the moment and this gldsim file is likewise wrong to fake the test as passing.");
    T403_tester7_test7_overrides_0_3_V_5_GP = (102+T403_tester7_test7_overrides_0_3_V_3);
    goto T403_45;
  T403_45:
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = ((int)(T403_tester7_test7_overrides_0_3_V_5_GP));
hpr_writeln("Test7 is broken at the moment and this gldsim file is likewise wrong to fake the test as passing.");
    T403_test7fv_module_incbyfv_4_5_V_0_GP = (102+T403_tester7_test7_overrides_0_3_V_3);
    goto T403_50;
  T403_50:
    /*skip*/;    T403_test7fv_module_incbyfv_4_5_V_0_GP = ((int)(T403_test7fv_module_incbyfv_4_5_V_0_GP));
hpr_writeln("Test7 is broken at the moment and this gldsim file is likewise wrong to fake the test as passing.");
    T403_tester7_test7_fv_0_4_V_2_GP = (102+T403_tester7_test7_overrides_0_3_V_3);
    goto T403_55;
  T403_55:
    /*skip*/;    T403_tester7_test7_fv_0_4_V_2_GP = ((int)(T403_tester7_test7_fv_0_4_V_2_GP));
hpr_writeln("Test7 override i=%u l=%u", T403_tester7_test7_overrides_0_3_V_3, T403_tester7_test7_overrides_0_3_V_5_GP);
hpr_writeln("      override i=%u m=%u", T403_tester7_test7_overrides_0_3_V_3, T403_test7fv_module_incbyfv_4_5_V_0_GP);
hpr_writeln("      override i=%u u=%u", T403_tester7_test7_overrides_0_3_V_3, T403_tester7_test7_fv_0_4_V_2_GP);
    T403_tester7_test7_overrides_0_3_V_3 = (1+T403_tester7_test7_overrides_0_3_V_3);
    goto T403_61;
  T403_10:
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (1);
    goto T403_30;
  T403_30:
    /*skip*/;    if (!(8<T403_tester7_test7_overrides_0_3_V_5_GP)) goto T403_13;
    goto T403_31;
  T403_13:
    /*skip*/;    if (!(7==T403_tester7_test7_overrides_0_3_V_5_GP)) goto T403_23;
    goto T403_14;
  T403_14:
    /*skip*/;hpr_write("%i%s", T403_tester7_test7_overrides_0_3_V_3*T403_tester7_test7_overrides_0_3_V_5_GP, " ");
  // Site of a conditional branch to LL38
hpr_writeln(" BAR");
    T403_test7lower_edict_3_6_V_0 = ("+");
    goto T403_21;
  T403_21:
    /*skip*/;    goto T403_28;
  T403_23:
    /*skip*/;hpr_write("%i%s", T403_tester7_test7_overrides_0_3_V_3*T403_tester7_test7_overrides_0_3_V_5_GP, " ");
    T403_test7lower_edict_4_6_V_0 = ("+");
    goto T403_28;
  T403_28:
    /*skip*/;    T403_tester7_test7_overrides_0_3_V_5_GP = (1+T403_tester7_test7_overrides_0_3_V_5_GP);
    goto T403_30;
  // End of DIC comment 1
}
// eof tester7
