// test1
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:47:45
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test1.exe -diosim-plot b.plt -sim 2080 -vnl DUT.v -preserve-sequencer=true -give-backtrace -report-each-step

#include "test1.h"

// opath operation: 10: cgen2

 void test1::exe010()
 { 
  //  Method no 0 mname=test1
    if (xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test1::exe110()
 { 
  //  Method no 1 mname=test1
    if (xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test1::exe210()
 { 
  //  Method no 2 mname=test1
    if (xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test1::exe310()
 { 
  //  Method no 3 mname=test1
    if (10>=test1_T403_Main_T403_Main_V_0&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test1::exe410()
 { 
  //  Method no 4 mname=test1
    if (10<test1_T403_Main_T403_Main_V_0&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test1::exe510()
 { 
  //  Method no 5 mname=test1
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test1::exe610()
 { 
  //  Method no 6 mname=test1
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test1::exe710()
 { 
  //  Method no 7 mname=test1
    if (xpc10nz==0/*0:xpc10nz*/)
     hpr_writeln("%s%i", "Test 1 Limit=", 10);
}

 void test1::exe810()
 { 
  //  Method no 8 mname=test1
    if (10<test1_T403_Main_T403_Main_V_0&&xpc10nz==2/*2:xpc10nz*/)
     hpr_writeln(" Test 1 finished.");
}

 void test1::exe910()
 { 
  //  Method no 9 mname=test1
    if (xpc10nz==3/*3:xpc10nz*/)
     hpr_sysexit(0);
}

 void test1::exe1010()
 { 
  //  Method no 10 mname=test1
    if (xpc10nz==4/*4:xpc10nz*/)
     hpr_write("%i%s", test1_T403_Main_T403_Main_V_0, " ");
}

 void test1::exe1110()
 { 
  //  Method no 11 mname=test1
    if (xpc10nz==1/*1:xpc10nz*/)
    test1_T403_Main_T403_Main_V_0 = (1);
}

 void test1::exe1210()
 { 
  //  Method no 12 mname=test1
    if (xpc10nz==5/*5:xpc10nz*/)
    test1_T403_Main_T403_Main_V_0 = (2+test1_T403_Main_T403_Main_V_0);
}
// eof test1
