// tester7
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:50:05
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test7.exe -conerefine=disable -bevelab=disable -verilog-gen=disable -sim 1800 -kiwic-cil-dump=combined -kiwic-kcode-dump=enable -give-backtrace -report-each-step

#ifndef tester7_H
#define tester7_H
#define HPR_NEEDS_SYSTEMC 1
#include "hprls.h"
// opath operation: 10: cgen2

struct  tester7  : public sc_module
{
  unsigned int tester7_limit;
  unsigned int T403_tester7_test7_overrides_0_3_V_9;
  unsigned int T403_tester7_test7_overrides_0_3_V_8;
  unsigned int T403_tester7_test7_fv_0_4_V_4;
  bool fastspilldup10;
  sc_int<-1> T403_test7lower_edict_3_6_V_0;
  sc_int<-1> T403_test7lower_edict_4_6_V_0;
  unsigned int T403_tester7_test7_fv_0_4_V_0;
  unsigned int T403_tester7_test7_fv_0_4_V_1;
  bool T403_tester7_test7_fv_0_4_V_3;
  unsigned int T403_tester7_test7_overrides_0_3_V_3;
  unsigned int T403_tester7_test7_overrides_0_3_V_5_GP;
  unsigned int T403_test7fv_module_incbyfv_4_5_V_0_GP;
  unsigned int T403_tester7_test7_fv_0_4_V_2_GP;
  unsigned int T403_tester7_test7_overrides_0_3_V_1;
  unsigned int T403_tester7_test7_overrides_0_3_V_2;
  unsigned int T403_tester7_test7_overrides_0_3_V_0;
  unsigned int tester7_test7_fv_CZ:0:4_blockrefxxnewobj18;
  unsigned int tester7_test7_fv_CZ:0:2_blockrefxxnewobj16;
  unsigned int T403_tester7_test7_fv_0_4__SPILL_256;
  unsigned int tester7_test7_overrides_CZ:0:6_blockrefxxnewobj14;
  unsigned int tester7_test7_overrides_CZ:0:4_blockrefxxnewobj12;
  unsigned int tester7_test7_overrides_CZ:0:2_blockrefxxnewobj10;
  unsigned int T403_tester7_test7_overrides_0_3__SPILL_256;
  unsigned int ktop16;
  unsigned int ktop14;
  sc_uint<1> System_BitConverter_IsLittleEndian;
  unsigned int ktop12;
  unsigned INT64 KiwiSystem_Kiwi_tnow;
  unsigned int KiwiSystem_Kiwi_old_pausemode_value;
  unsigned int ktop10;
  sc_uint<1> tester7_test7_fv_CZ:0:4_blockrefxxnewobj18a;
  sc_uint<1> T403_tester7_test7_fv_0_4_V_1a;
  sc_uint<1> fastspilldup10a;
  sc_uint<1> tester7_test7_fv_CZ:0:2_blockrefxxnewobj16a;
  sc_uint<1> T403_tester7_test7_fv_0_4_V_3a;
  sc_uint<1> T403_tester7_test7_fv_0_4_V_0a;
  sc_uint<1> T403_tester7_test7_fv_0_4__SPILL_256a;
  unsigned int __SINT_CC_MAPR10NoCE1_fv;
  unsigned int __SINT_CC_MAPR10NoCE0_fv;
  sc_in < sc_uint<1> > clk;
  sc_out  < sc_uint<1> > hf1_dram0bank_opreq;
  sc_in < sc_uint<1> > hf1_dram0bank_oprdy;
  sc_in < sc_uint<1> > hf1_dram0bank_ack;
  sc_out  < sc_uint<1> > hf1_dram0bank_rwbar;
  sc_out  < sc_uint<256> > hf1_dram0bank_wdata;
  sc_out  < sc_uint<22> > hf1_dram0bank_addr;
  sc_in < sc_uint<256> > hf1_dram0bank_rdata;
  sc_out  < unsigned int > hf1_dram0bank_lanes;

  tester7( sc_core::sc_module_name name)  :    sc_core::sc_module("tester7")
   { 
       SC_HAS_PROCESS(tester7);
SC_METHOD(new SystemCsharp.sc_method_t(exe010)).sensitive_pos(clk);
  }

   int exe010();
};

#endif
// eof tester7
