// test9
// Generated by CBG Orangepath HPR/LS
// 8/3/2011 4:37:23 PM
//  /home/djg11/d320/hprls/kiwic/distro/lib/kiwic.exe -report-each-step -csharp-gen=enable -gtrace-loglevel=0 -firstpass-loglevel=0 test9.exe /home/djg11/d320/hprls/kiwic/distro/support/Kiwi.dll /home/djg11/d320/hprls/kiwic/distro/support/Kiwic.dll -finish true -vnl test9.v -sim 1800

using SystemCsharp;
// opath operation: 8: csharp-gen

public class  test9  : sc_module
{
  public sc_signal Ttpa0_3_V_0;
  public sc_signal mpc10;
  public sc_in < bool > clk;

  public test9( string name)  :    base("test9")
   { 
      clk = (new sc_in<bool>(this, "clk"));
      Ttpa0_3_V_0 = (new sc_signal(32, "Ttpa0_3_V_0"));
      mpc10 = (new sc_signal(32, "mpc10"));
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe12)).sensitive_pos(clk);
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe10)).sensitive_pos(clk);
  }

   void exe10()
   { 
    //  Method no 0 mname=test9

    {      if (((mpc10.Read())==(0)))
       hpr_write("%s%d", " ", 0x0ff&"Hello World\n"[0]);
      if (((mpc10.Read())==(2)))

    {      if (((Ttpa0_3_V_0.Read())<(11)))
       hpr_write("%s%d", " ", 0x0ff&"Hello World\n"[1+Ttpa0_3_V_0.Read()]);
      if (((Ttpa0_3_V_0.Read())>=(11)))

    {       hpr_writeln("\nDone");
       hpr_sysexit(0);

    }

    }

    }
  }

   void exe12()
   { 
    //  Method no 1 mname=test9
      switch (mpc10.Read())     {
 
    case 0:
    
    {      mpc10.Write(2/*2:mpc10XS:":pcIS27:AG"*/);
      Ttpa0_3_V_0.Write(0);

    }
    break;
    case 2:
    
    {      mpc10.Write((((Ttpa0_3_V_0.Read())>=(11)))?1/*1:mpc10XS:":pcIS-10:AG"*/:(((Ttpa0_3_V_0.Read())<(11)))?2/*2:mpc10*/:mpc10.Read());
      Ttpa0_3_V_0.Write(1+Ttpa0_3_V_0.Read());

    }
    break; }  }
};

// eof test9
