// test32
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:55:25
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test32.exe -max-no-int-divs=5 -diosim-vcd=test32b5.vcd -vnl-resets=synchronous -res2-loadstore-port-count=0 -vnl DUT.v -sim 4800 -give-backtrace -report-each-step

#ifndef test32_H
#define test32_H
#define HPR_NEEDS_SYSTEMC 1
#include "hprls.h"
// opath operation: 10: cgen2

struct  test32  : public sc_module
{
  unsigned int test32_nn;
  unsigned int test32_T403_Main_T403_Main_V_1_GP;
  sc_uint<6> xpc10nz;
  unsigned int isDIVIDER10RRh10hold;
  sc_uint<1> isDIVIDER10RRh10primed;
  sc_uint<1> isDIVIDER10RRh10vld;
  unsigned int isDIVIDER12RRh10hold;
  sc_uint<1> isDIVIDER12RRh10primed;
  sc_uint<1> isDIVIDER12RRh10vld;
  unsigned int isDIVIDER14RRh10hold;
  sc_uint<1> isDIVIDER14RRh10primed;
  sc_uint<1> isDIVIDER14RRh10vld;
  unsigned int isDIVIDER16RRh10hold;
  sc_uint<1> isDIVIDER16RRh10primed;
  sc_uint<1> isDIVIDER16RRh10vld;
  unsigned int isDIVIDER18RRh10hold;
  sc_uint<1> isDIVIDER18RRh10primed;
  sc_uint<1> isDIVIDER18RRh10vld;
  sc_uint<1> xpc10_stall;
  sc_uint<1> xpc10_clear;
  sc_uint<1> isDIVIDER18_rdy;
  sc_uint<1> isDIVIDER18_req;
  unsigned int isDIVIDER18_RR;
  unsigned int isDIVIDER18_NN;
  unsigned int isDIVIDER18_DD;
  sc_uint<1> isDIVIDER18_err;
  sc_uint<1> isDIVIDER16_rdy;
  sc_uint<1> isDIVIDER16_req;
  unsigned int isDIVIDER16_RR;
  unsigned int isDIVIDER16_NN;
  unsigned int isDIVIDER16_DD;
  sc_uint<1> isDIVIDER16_err;
  sc_uint<1> isDIVIDER14_rdy;
  sc_uint<1> isDIVIDER14_req;
  unsigned int isDIVIDER14_RR;
  unsigned int isDIVIDER14_NN;
  unsigned int isDIVIDER14_DD;
  sc_uint<1> isDIVIDER14_err;
  sc_uint<1> isDIVIDER12_rdy;
  sc_uint<1> isDIVIDER12_req;
  unsigned int isDIVIDER12_RR;
  unsigned int isDIVIDER12_NN;
  unsigned int isDIVIDER12_DD;
  sc_uint<1> isDIVIDER12_err;
  sc_in < sc_uint<1> > clk;
  sc_in < sc_uint<1> > reset;
  sc_uint<1> isDIVIDER10_rdy;
  sc_uint<1> isDIVIDER10_req;
  unsigned int isDIVIDER10_RR;
  unsigned int isDIVIDER10_NN;
  unsigned int isDIVIDER10_DD;
  sc_uint<1> isDIVIDER10_err;

  test32( sc_core::sc_module_name name)  :    sc_core::sc_module("test32")
   { 
       SC_HAS_PROCESS(test32);
SC_METHOD(new SystemCsharp.sc_method_t(exe9610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe9010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe8010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe120)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe020)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe118)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe018)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe116)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe016)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe114)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe014)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe112)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe012)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe010)).sensitive_pos(clk);
  }

   void exe020();

   void exe120();

   void exe210();

   void exe310();

   void exe410();

   void exe510();

   void exe610();

   void exe710();

   void exe810();

   void exe910();

   void exe1010();

   void exe1110();

   void exe1210();

   void exe1310();

   void exe1410();

   void exe1510();

   void exe1610();

   void exe1710();

   void exe1810();

   void exe1910();

   void exe2010();

   void exe2110();

   void exe2210();

   void exe2310();

   void exe2410();

   void exe2510();

   void exe2610();

   void exe2710();

   void exe2810();

   void exe2910();

   void exe3010();

   void exe3110();

   void exe3210();

   void exe3310();

   void exe3410();

   void exe3510();

   void exe3610();

   void exe3710();

   void exe3810();

   void exe3910();

   void exe4010();

   void exe4110();

   void exe4210();

   void exe4310();

   void exe4410();

   void exe4510();

   void exe4610();

   void exe4710();

   void exe4810();

   void exe4910();

   void exe5010();

   void exe5110();

   void exe5210();

   void exe5310();

   void exe5410();

   void exe5510();

   void exe5610();

   void exe5710();

   void exe5810();

   void exe5910();

   void exe6010();

   void exe6110();

   void exe6210();

   void exe6310();

   void exe6410();

   void exe6510();

   void exe6610();

   void exe6710();

   void exe6810();

   void exe6910();

   void exe7010();

   void exe7110();

   void exe7210();

   void exe7310();

   void exe7410();

   void exe7510();

   void exe7610();

   void exe7710();

   void exe7810();

   void exe7910();

   void exe8010();

   void exe8110();

   void exe8210();

   void exe8310();

   void exe8410();

   void exe8510();

   void exe8610();

   void exe8710();

   void exe8810();

   void exe8910();

   void exe9010();

   void exe9110();

   void exe9210();

   void exe9310();

   void exe9410();

   void exe9510();

   void exe9610();

   void exe018();

   void exe118();

   void exe016();

   void exe116();

   void exe014();

   void exe114();

   void exe012();

   void exe112();

   void exe010();

   void exe110();
};

#endif
// eof test32
