// test38r4
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:56:16
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test38r4.exe -sim 1800 -vnl-resets=synchronous -vnl DUT.v -give-backtrace -report-each-step

#ifndef test38r4_H
#define test38r4_H
#define HPR_NEEDS_SYSTEMC 1
#include "hprls.h"
// opath operation: 10: cgen2

struct  test38r4  : public sc_module
{
  unsigned int test38r4_T402_Main_T402_Main_V_1;
  unsigned int test38r4_T402_Main_T402_Main_V_2;
  unsigned int __star1__TestClass_CC_SCALbx16_ARA0[3];
  unsigned int __SINT_CC_MAPR12NoCE0_SCALARB1_0;
  unsigned int __SINT_CC_MAPR12NoCE1_SCALARB1_0;
  unsigned int __SINT_CC_MAPR12NoCE2_SCALARB1_0;
  unsigned int __SINT_CC_MAPR12NoCE0_SCALARC0_0;
  unsigned int __SINT_CC_MAPR12NoCE1_SCALARC0_0;
  unsigned int __SINT_CC_MAPR12NoCE2_SCALARC0_0;
  unsigned int __SINT_CC_MAPR10NoCE0_duranfield;
  unsigned int __SINT_CC_MAPR10NoCE1_duranfield;
  unsigned int __SINT_CC_MAPR10NoCE2_duranfield;
  unsigned int __s__SINT_CC_MAPR10NoCE0_lebon;
  unsigned int __s__SINT_CC_MAPR10NoCE1_lebon;
  unsigned int __s__SINT_CC_MAPR10NoCE2_lebon;
  sc_uint<5> xpc10nz;
  sc_in < sc_uint<1> > clk;
  sc_out  < sc_uint<1> > hf1_dram0bank_opreq;
  sc_in < sc_uint<1> > hf1_dram0bank_oprdy;
  sc_in < sc_uint<1> > hf1_dram0bank_ack;
  sc_out  < sc_uint<1> > hf1_dram0bank_rwbar;
  sc_out  < sc_uint<256> > hf1_dram0bank_wdata;
  sc_out  < sc_uint<22> > hf1_dram0bank_addr;
  sc_in < sc_uint<256> > hf1_dram0bank_rdata;
  sc_out  < unsigned int > hf1_dram0bank_lanes;

  test38r4( sc_core::sc_module_name name)  :    sc_core::sc_module("test38r4")
   { 
       SC_HAS_PROCESS(test38r4);
SC_METHOD(new SystemCsharp.sc_method_t(exe7110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe7010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe6010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe5010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe4010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe3010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe2010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe1010)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe910)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe810)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe710)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe610)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe510)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe410)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe310)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe210)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe010)).sensitive_pos(clk);
  }

   void exe010();

   void exe110();

   void exe210();

   void exe310();

   void exe410();

   void exe510();

   void exe610();

   void exe710();

   void exe810();

   void exe910();

   void exe1010();

   void exe1110();

   void exe1210();

   void exe1310();

   void exe1410();

   void exe1510();

   void exe1610();

   void exe1710();

   void exe1810();

   void exe1910();

   void exe2010();

   void exe2110();

   void exe2210();

   void exe2310();

   void exe2410();

   void exe2510();

   void exe2610();

   void exe2710();

   void exe2810();

   void exe2910();

   void exe3010();

   void exe3110();

   void exe3210();

   void exe3310();

   void exe3410();

   void exe3510();

   void exe3610();

   void exe3710();

   void exe3810();

   void exe3910();

   void exe4010();

   void exe4110();

   void exe4210();

   void exe4310();

   void exe4410();

   void exe4510();

   void exe4610();

   void exe4710();

   void exe4810();

   void exe4910();

   void exe5010();

   void exe5110();

   void exe5210();

   void exe5310();

   void exe5410();

   void exe5510();

   void exe5610();

   void exe5710();

   void exe5810();

   void exe5910();

   void exe6010();

   void exe6110();

   void exe6210();

   void exe6310();

   void exe6410();

   void exe6510();

   void exe6610();

   void exe6710();

   void exe6810();

   void exe6910();

   void exe7010();

   void exe7110();
};

#endif
// eof test38r4
