// test25
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:53:49
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test25.exe -diosim-vcd=test25.vcd -sim 1800 -bevelab-default-pause-mode=auto -give-backtrace -report-each-step

#include "test25.h"

// opath operation: 10: cgen2

 void test25::exe010()
 { 
  //  Method no 0 mname=test25
    if (test25_T402_Main_T402_Main_V_2<19&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test25::exe110()
 { 
  //  Method no 1 mname=test25
    if (test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test25::exe210()
 { 
  //  Method no 2 mname=test25
    if (0<dout%2&&!test25_T402_Main_T402_Main_V_0&&xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test25::exe310()
 { 
  //  Method no 3 mname=test25
    if (0<dout%2&&test25_T402_Main_T402_Main_V_0&&!test25_T402_Main_T402_Main_V_1&&xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test25::exe410()
 { 
  //  Method no 4 mname=test25
    if (test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0<(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test25::exe510()
 { 
  //  Method no 5 mname=test25
    if ((test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0&&xpc10nz==1/*1:xpc10nz*/)||(0>=dout%2&&0>=(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_1&&xpc10nz==1/*1:xpc10nz*/))
    if ((0>=dout%2&&!test25_T402_Main_T402_Main_V_1)||(0>=dout%2&&0>=(100+dout)%2)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0)||(test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2))
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test25::exe610()
 { 
  //  Method no 6 mname=test25
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test25::exe710()
 { 
  //  Method no 7 mname=test25
    if (0>=dout%2&&!test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_2<19&&xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("dout=%u", 1+1+din);
}

 void test25::exe810()
 { 
  //  Method no 8 mname=test25
    if (0>=dout%2&&!test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==1/*1:xpc10nz*/)
     hpr_sysexit(0);
}

 void test25::exe910()
 { 
  //  Method no 9 mname=test25
    if (0>=dout%2&&!test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("dout=%u", 1+1+din);
}

 void test25::exe1010()
 { 
  //  Method no 10 mname=test25
    if (0>=dout%2&&test25_T402_Main_T402_Main_V_0&&!test25_T402_Main_T402_Main_V_1&&test25_T402_Main_T402_Main_V_2<19&&xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("dout=%u", 1+1+din);
}

 void test25::exe1110()
 { 
  //  Method no 11 mname=test25
    if (0>=dout%2&&test25_T402_Main_T402_Main_V_0&&!test25_T402_Main_T402_Main_V_1&&test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==1/*1:xpc10nz*/)
     hpr_sysexit(0);
}

 void test25::exe1210()
 { 
  //  Method no 12 mname=test25
    if (0>=dout%2&&test25_T402_Main_T402_Main_V_0&&!test25_T402_Main_T402_Main_V_1&&test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("dout=%u", 1+1+din);
}

 void test25::exe1310()
 { 
  //  Method no 13 mname=test25
    if (test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&test25_T402_Main_T402_Main_V_2<19&&0>=(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/)
    if (test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2)
     hpr_writeln("dout=%u", 101+101+din);
}

 void test25::exe1410()
 { 
  //  Method no 14 mname=test25
    if (test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&test25_T402_Main_T402_Main_V_2>=19&&0>=(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/)
     hpr_sysexit(0);
}

 void test25::exe1510()
 { 
  //  Method no 15 mname=test25
    if (test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&test25_T402_Main_T402_Main_V_2>=19&&0>=(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/)
    if (test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2)
     hpr_writeln("dout=%u", 101+101+din);
}

 void test25::exe1610()
 { 
  //  Method no 16 mname=test25
    if (test25_T402_Main_T402_Main_V_2<19&&xpc10nz==2/*2:xpc10nz*/)
     hpr_writeln("dout=%u", 1+1+din);
}

 void test25::exe1710()
 { 
  //  Method no 17 mname=test25
    if (test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==2/*2:xpc10nz*/)
     hpr_sysexit(0);
}

 void test25::exe1810()
 { 
  //  Method no 18 mname=test25
    if (test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==2/*2:xpc10nz*/)
     hpr_writeln("dout=%u", 1+1+din);
}

 void test25::exe1910()
 { 
  //  Method no 19 mname=test25
    if (xpc10nz==0/*0:xpc10nz*/)
    test25_T402_Main_T402_Main_V_2 = (0);
}

 void test25::exe2010()
 { 
  //  Method no 20 mname=test25
    if (xpc10nz==0/*0:xpc10nz*/)
    test25_T402_Main_T402_Main_V_1 = (0x0);
}

 void test25::exe2110()
 { 
  //  Method no 21 mname=test25
    if (xpc10nz==0/*0:xpc10nz*/)
    test25_T402_Main_T402_Main_V_0 = (0x0);
}

 void test25::exe2210()
 { 
  //  Method no 22 mname=test25
    if (test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0<(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/)
    dout = (100+dout);
}

 void test25::exe2310()
 { 
  //  Method no 23 mname=test25
    if ((0>=dout%2&&!test25_T402_Main_T402_Main_V_1&&xpc10nz==1/*1:xpc10nz*/)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0&&xpc10nz==1/*1:xpc10nz*/)||(test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/))
    if ((test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_1))
    test25_T402_Main_T402_Main_V_2 = (1+test25_T402_Main_T402_Main_V_2);
}

 void test25::exe2410()
 { 
  //  Method no 24 mname=test25
    if ((0>=dout%2&&!test25_T402_Main_T402_Main_V_1&&xpc10nz==1/*1:xpc10nz*/)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0&&xpc10nz==1/*1:xpc10nz*/)||(test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/))
    if ((test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_1))
    test25_T402_Main_T402_Main_V_1 = ((sc_uint<1>)(!test25_T402_Main_T402_Main_V_1));
}

 void test25::exe2510()
 { 
  //  Method no 25 mname=test25
    if ((0>=dout%2&&!test25_T402_Main_T402_Main_V_1&&xpc10nz==1/*1:xpc10nz*/)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0&&xpc10nz==1/*1:xpc10nz*/)||(test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/))
    if ((test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_1))
    test25_T402_Main_T402_Main_V_0 = ((0>=dout%2&&!test25_T402_Main_T402_Main_V_0&&!test25_T402_Main_T402_Main_V_1)||(test25_T402_Main_T402_Main_V_0&&!test25_T402_Main_T402_Main_V_1)||(0<dout%2&&!test25_T402_Main_T402_Main_V_1));
}

 void test25::exe2610()
 { 
  //  Method no 26 mname=test25
    if ((0>=dout%2&&!test25_T402_Main_T402_Main_V_1&&xpc10nz==1/*1:xpc10nz*/)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0&&xpc10nz==1/*1:xpc10nz*/)||(test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2&&xpc10nz==1/*1:xpc10nz*/))
    if ((test25_T402_Main_T402_Main_V_0&&test25_T402_Main_T402_Main_V_1&&0>=(100+dout)%2)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_1))
    dout = ((((0>=dout%2&&test25_T402_Main_T402_Main_V_0&&!test25_T402_Main_T402_Main_V_1)||(0>=dout%2&&!test25_T402_Main_T402_Main_V_0))?1+1+din:101+101+din));
}

 void test25::exe2710()
 { 
  //  Method no 27 mname=test25
    if (test25_T402_Main_T402_Main_V_2<19&&xpc10nz==2/*2:xpc10nz*/)
    test25_T402_Main_T402_Main_V_2 = (1+test25_T402_Main_T402_Main_V_2);
}

 void test25::exe2810()
 { 
  //  Method no 28 mname=test25
    if (test25_T402_Main_T402_Main_V_2<19&&xpc10nz==2/*2:xpc10nz*/)
    test25_T402_Main_T402_Main_V_1 = ((sc_uint<1>)(!test25_T402_Main_T402_Main_V_1));
}

 void test25::exe2910()
 { 
  //  Method no 29 mname=test25
    if (test25_T402_Main_T402_Main_V_2<19&&xpc10nz==2/*2:xpc10nz*/)
    test25_T402_Main_T402_Main_V_0 = (!test25_T402_Main_T402_Main_V_1);
}

 void test25::exe3010()
 { 
  //  Method no 30 mname=test25
    if (test25_T402_Main_T402_Main_V_2<19&&xpc10nz==2/*2:xpc10nz*/)
    dout = (1+1+din);
}

 void test25::exe3110()
 { 
  //  Method no 31 mname=test25
    if (test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==2/*2:xpc10nz*/)
    test25_T402_Main_T402_Main_V_2 = (1+test25_T402_Main_T402_Main_V_2);
}

 void test25::exe3210()
 { 
  //  Method no 32 mname=test25
    if (test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==2/*2:xpc10nz*/)
    test25_T402_Main_T402_Main_V_1 = ((sc_uint<1>)(!test25_T402_Main_T402_Main_V_1));
}

 void test25::exe3310()
 { 
  //  Method no 33 mname=test25
    if (test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==2/*2:xpc10nz*/)
    test25_T402_Main_T402_Main_V_0 = (!test25_T402_Main_T402_Main_V_1);
}

 void test25::exe3410()
 { 
  //  Method no 34 mname=test25
    if (test25_T402_Main_T402_Main_V_2>=19&&xpc10nz==2/*2:xpc10nz*/)
    dout = (1+1+din);
}
// eof test25
