// test57
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:58:23
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test57.exe -sim 1800 -compose=disable -vnl-rootmodname=DUT -vnl-resets=synchronous -bevelab=disable -verilog-gen=disable -repack=disable -conerefine=disable -restructure2=disable -give-backtrace -report-each-step

#include "test57.h"

// opath operation: 10: cgen2

 int test57::exe010()
 { 
  //  Method no 0 mname=test5710
    /*skip*/;  // End of static elaboration for tid T401. After all generate loops are unwound we arrive here: 0
  T401_0:
    /*skip*/;    System_BitConverter_IsLittleEndian = (0x1);
    goto DESTWASCOMMENT12;
    goto DESTWASCOMMENT12;
  DESTWASCOMMENT12:
    /*skip*/;  // End of static elaboration for tid T400. After all generate loops are unwound we arrive here: 0
  T400_0:
    /*skip*/;    KiwiSystem_Kiwi_old_pausemode_value = (0x2);
    KiwiSystem_Kiwi_tnow = (0x0);
    goto DESTWASCOMMENT10;
    goto DESTWASCOMMENT10;
  DESTWASCOMMENT10:
    /*skip*/;  // End of static elaboration for tid T402. After all generate loops are unwound we arrive here: 0
  T402_0:
    /*skip*/;hpr_writeln("Kiwi Demo - Test57 starting.");
wait(8);
    T402_test57_test57_phase0_0_6_V_0 = ("Hello One");
    T402_test57_test57_phase0_0_6_V_1 = (0);
    goto T402_18;
  T402_18:
    /*skip*/;    if (!(T402_test57_test57_phase0_0_6_V_1>=4)) goto T402_6;
    goto T402_19;
  T402_19:
    /*skip*/;hpr_writeln("Test57 done.");
    return (0);
    return (1);
  T402_6:
    /*skip*/;    if (!(2<T402_test57_test57_phase0_0_6_V_1)) goto T402_10;
    goto T402_7;
  T402_7:
    /*skip*/;    T402_test57_test57_phase0_0_6__SPILL_256 = ("Bonjor Number Two");
    goto T402_12;
  T402_10:
    /*skip*/;    T402_test57_test57_phase0_0_6__SPILL_256 = ("Hello One");
    goto T402_12;
  T402_12:
    /*skip*/;    T402_test57_test57_phase0_0_6_V_2 = (T402_test57_test57_phase0_0_6__SPILL_256);
wait(8);
hpr_writeln("   stringers %u  %d len=%u", T402_test57_test57_phase0_0_6_V_1, T402_test57_test57_phase0_0_6_V_2, hpr_strlen(T402_test57_test57_phase0_0_6_V_2));
wait(8);
    T402_test57_test57_phase0_0_6_V_1 = (1+T402_test57_test57_phase0_0_6_V_1);
    goto T402_18;
  // End of DIC comment 1
}
// eof test57
