// test39r1
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:56:20
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test39r1.exe -sim 1800 -restructure2=disable -conerefine=disable -bevelab=disable -verilog-gen=disable -repack=disable -give-backtrace -report-each-step

#include "test39r1.h"

// opath operation: 10: cgen2

 void test39r1::exe010()
 { 
  //  Method no 0 mname=test39r1
// no items
}

 int test39r1::exe110()
 { 
  //  Method no 1 mname=test39r1
    /*skip*/;  // End of static elaboration for tid T402. After all generate loops are unwound we arrive here: 0
  T402_0:
    /*skip*/;    LinkedListOfInts_freelist = (0x0);
    LinkedListOfInts_sbrk = (0);
    CS_0_6_refxxarray10 = (d1.0x61a80);
    LinkedListOfInts_heapPool = (d1.0x61a80);
    T402__cctor_CZ:0:8_blockrefxxnewobj10 = (d2.0x5fbfb80);
    LinkedListOfInts_ohandler = (d2.0x5fbfb80);
    T402__cctor_CZ:0:10_blockrefxxnewobj12 = (d3.0x5fbfb88);
    LinkedListOfInts_locker = (d3.0x5fbfb88);
    goto DESTWASCOMMENT14;
    goto DESTWASCOMMENT14;
  DESTWASCOMMENT14:
    /*skip*/;  // End of static elaboration for tid T401. After all generate loops are unwound we arrive here: 0
  T401_0:
    /*skip*/;    System_BitConverter_IsLittleEndian = (0x1);
    goto DESTWASCOMMENT12;
    goto DESTWASCOMMENT12;
  DESTWASCOMMENT12:
    /*skip*/;  // End of static elaboration for tid T400. After all generate loops are unwound we arrive here: 0
  T400_0:
    /*skip*/;    KiwiSystem_Kiwi_old_pausemode_value = (0x2);
    KiwiSystem_Kiwi_tnow = (0x0);
    goto DESTWASCOMMENT10;
    goto DESTWASCOMMENT10;
  DESTWASCOMMENT10:
    /*skip*/;  // End of static elaboration for tid T403. After all generate loops are unwound we arrive here: 0
  T403_0:
    /*skip*/;hpr_writeln("Test 39r1 Linked Lists in DRAM Demo. Trees are a simple extension.");
    LinkedListOfInts_sbrk = (0);
hpr_writeln("Test 39r1: Freepool created, %u bytes.", 0x5f5e100);
wait(16);
wait(8);
    test39r1_T403_Main_T403_Main_V_0 = (0x0);
    test39r1_T403_Main_T403_Main_V_1 = (0);
    goto T403_49;
  T403_49:
    /*skip*/;    if (!(test39r1_T403_Main_T403_Main_V_1>=4)) goto T403_10;
    goto T403_50;
  T403_50:
    /*skip*/;    test39r1_T403_Main_T403_Main_V_3_GP = (test39r1_T403_Main_T403_Main_V_0);
    goto T403_57;
  T403_57:
    /*skip*/;    if (!(0==test39r1_T403_Main_T403_Main_V_3_GP)) goto T403_53;
    goto T403_58;
  T403_58:
    /*skip*/;hpr_writeln("Test 39r1 Linked List DRAM Demo Finished.");
    return (0);
    return (1);
  T403_53:
    /*skip*/;wait(8);
hpr_writeln("  Readback Item %u", /*ub T403/LinkedListOfInts/alloc/1.6/V_3_GP, test39r1/T403/Main/T403/Main/V_1, T403/LinkedListOfInts/alloc/1.6/V_1, test39r1/T403/Main/T403/Main/V_0, test39r1/T403/Main/T403/Main/V_3_GP, WASANON16/blockrefreftran16, WASANON14/blockrefreftran14, WASANON12/blockrefreftran12, WASANON10/blockrefreftran10, ktop16, T402/.cctor/CZ:0:10/blockrefxxnewobj12, T402/.cctor/CZ:0:8/blockrefxxnewobj10, CS/0.6/refxxarray10, LinkedListOfInts/locker, LinkedListOfInts/ohandler, LinkedListOfInts/heapPool, LinkedListOfInts/sbrk, LinkedListOfInts/freelist, ktop14, System/BitConverter/IsLittleEndian, ktop12, KiwiSystem/Kiwi/tnow, KiwiSystem/Kiwi/old_pausemode_value, ktop10, clk cf @_SINT*/__SINT[$offset+car.4+d6.test39r1_T403_Main_T403_Main_V_3_GP]);
    test39r1_T403_Main_T403_Main_V_3_GP = (/*ub T403/LinkedListOfInts/alloc/1.6/V_3_GP, test39r1/T403/Main/T403/Main/V_1, T403/LinkedListOfInts/alloc/1.6/V_1, test39r1/T403/Main/T403/Main/V_0, test39r1/T403/Main/T403/Main/V_3_GP, WASANON16/blockrefreftran16, WASANON14/blockrefreftran14, WASANON12/blockrefreftran12, WASANON10/blockrefreftran10, ktop16, T402/.cctor/CZ:0:10/blockrefxxnewobj12, T402/.cctor/CZ:0:8/blockrefxxnewobj10, CS/0.6/refxxarray10, LinkedListOfInts/locker, LinkedListOfInts/ohandler, LinkedListOfInts/heapPool, LinkedListOfInts/sbrk, LinkedListOfInts/freelist, ktop14, System/BitConverter/IsLittleEndian, ktop12, KiwiSystem/Kiwi/tnow, KiwiSystem/Kiwi/old_pausemode_value, ktop10, clk cf @$star1$_LinkedListOfInts*/__star1__LinkedListOfInts[$offset+cdr.8+d6.test39r1_T403_Main_T403_Main_V_3_GP]);
    goto T403_57;
  T403_10:
    /*skip*/;    test39r1_T403_Main_T403_Main_V_3_GP = (0x0);
    T403_LinkedListOfInts_alloc_1_6_V_1 = (4);
    if (!(4+LinkedListOfInts_sbrk>=0x5f5e100)) goto T403_17;
    goto T403_13;
  T403_13:
    /*skip*/;    if (!(0==LinkedListOfInts_freelist)) goto T403_17;
    goto T403_14;
  T403_14:
    /*skip*/;hpr_writeln("  Kiwi RunTimeAbend  msg=%d code=%u", "no free cells", 1);
    goto T403_42;
  T403_17:
    /*skip*/;    if (!(0==LinkedListOfInts_freelist)) goto T403_31;
    goto T403_18;
  T403_18:
    /*skip*/;    T403_LinkedListOfInts_alloc_1_6_V_3_GP = (d3.0x5fbfb88);
    goto T403_23;
  T403_23:
    /*skip*/;    WASANON10_blockrefreftran10 = ((sc_uint<1>)(hpr_testandset(/*ub T403/LinkedListOfInts/alloc/1.6/V_3_GP, test39r1/T403/Main/T403/Main/V_1, T403/LinkedListOfInts/alloc/1.6/V_1, test39r1/T403/Main/T403/Main/V_0, test39r1/T403/Main/T403/Main/V_3_GP, WASANON16/blockrefreftran16, WASANON14/blockrefreftran14, WASANON12/blockrefreftran12, WASANON10/blockrefreftran10, ktop16, T402/.cctor/CZ:0:10/blockrefxxnewobj12, T402/.cctor/CZ:0:8/blockrefxxnewobj10, CS/0.6/refxxarray10, LinkedListOfInts/locker, LinkedListOfInts/ohandler, LinkedListOfInts/heapPool, LinkedListOfInts/sbrk, LinkedListOfInts/freelist, ktop14, System/BitConverter/IsLittleEndian, ktop12, KiwiSystem/Kiwi/tnow, KiwiSystem/Kiwi/old_pausemode_value, ktop10, clk cf @_BOOL*/__BOOL[d3.0x5fbfb88+$offset+kiwi_objectlock.0], 1)));
    if (!(!WASANON10_blockrefreftran10)) goto T403_21;
    goto T403_25;
  T403_25:
    /*skip*/;    test39r1_T403_Main_T403_Main_V_3_GP = (d1.0x61a80+LinkedListOfInts_sbrk);
    LinkedListOfInts_sbrk = (4+LinkedListOfInts_sbrk);
    WASANON12_blockrefreftran12 = ((sc_uint<1>)(hpr_testandset(/*ub T403/LinkedListOfInts/alloc/1.6/V_3_GP, test39r1/T403/Main/T403/Main/V_1, T403/LinkedListOfInts/alloc/1.6/V_1, test39r1/T403/Main/T403/Main/V_0, test39r1/T403/Main/T403/Main/V_3_GP, WASANON16/blockrefreftran16, WASANON14/blockrefreftran14, WASANON12/blockrefreftran12, WASANON10/blockrefreftran10, ktop16, T402/.cctor/CZ:0:10/blockrefxxnewobj12, T402/.cctor/CZ:0:8/blockrefxxnewobj10, CS/0.6/refxxarray10, LinkedListOfInts/locker, LinkedListOfInts/ohandler, LinkedListOfInts/heapPool, LinkedListOfInts/sbrk, LinkedListOfInts/freelist, ktop14, System/BitConverter/IsLittleEndian, ktop12, KiwiSystem/Kiwi/tnow, KiwiSystem/Kiwi/old_pausemode_value, ktop10, clk cf @_BOOL*/__BOOL[d3.0x5fbfb88+$offset+kiwi_objectlock.0], 0)));
    goto T403_42;
  T403_21:
    /*skip*/;    goto T403_23;
  T403_31:
    /*skip*/;    T403_LinkedListOfInts_alloc_1_6_V_3_GP = (d3.0x5fbfb88);
    goto T403_36;
  T403_36:
    /*skip*/;    WASANON14_blockrefreftran14 = ((sc_uint<1>)(hpr_testandset(/*ub T403/LinkedListOfInts/alloc/1.6/V_3_GP, test39r1/T403/Main/T403/Main/V_1, T403/LinkedListOfInts/alloc/1.6/V_1, test39r1/T403/Main/T403/Main/V_0, test39r1/T403/Main/T403/Main/V_3_GP, WASANON16/blockrefreftran16, WASANON14/blockrefreftran14, WASANON12/blockrefreftran12, WASANON10/blockrefreftran10, ktop16, T402/.cctor/CZ:0:10/blockrefxxnewobj12, T402/.cctor/CZ:0:8/blockrefxxnewobj10, CS/0.6/refxxarray10, LinkedListOfInts/locker, LinkedListOfInts/ohandler, LinkedListOfInts/heapPool, LinkedListOfInts/sbrk, LinkedListOfInts/freelist, ktop14, System/BitConverter/IsLittleEndian, ktop12, KiwiSystem/Kiwi/tnow, KiwiSystem/Kiwi/old_pausemode_value, ktop10, clk cf @_BOOL*/__BOOL[d3.0x5fbfb88+$offset+kiwi_objectlock.0], 1)));
    if (!(!WASANON14_blockrefreftran14)) goto T403_34;
    goto T403_38;
  T403_38:
    /*skip*/;    test39r1_T403_Main_T403_Main_V_3_GP = (LinkedListOfInts_freelist);
    LinkedListOfInts_freelist = (/*ub T403/LinkedListOfInts/alloc/1.6/V_3_GP, test39r1/T403/Main/T403/Main/V_1, T403/LinkedListOfInts/alloc/1.6/V_1, test39r1/T403/Main/T403/Main/V_0, test39r1/T403/Main/T403/Main/V_3_GP, WASANON16/blockrefreftran16, WASANON14/blockrefreftran14, WASANON12/blockrefreftran12, WASANON10/blockrefreftran10, ktop16, T402/.cctor/CZ:0:10/blockrefxxnewobj12, T402/.cctor/CZ:0:8/blockrefxxnewobj10, CS/0.6/refxxarray10, LinkedListOfInts/locker, LinkedListOfInts/ohandler, LinkedListOfInts/heapPool, LinkedListOfInts/sbrk, LinkedListOfInts/freelist, ktop14, System/BitConverter/IsLittleEndian, ktop12, KiwiSystem/Kiwi/tnow, KiwiSystem/Kiwi/old_pausemode_value, ktop10, clk cf @$star1$_LinkedListOfInts*/__star1__LinkedListOfInts[$offset+cdr.8+d4.test39r1_T403_Main_T403_Main_V_3_GP]);
    WASANON16_blockrefreftran16 = ((sc_uint<1>)(hpr_testandset(/*ub T403/LinkedListOfInts/alloc/1.6/V_3_GP, test39r1/T403/Main/T403/Main/V_1, T403/LinkedListOfInts/alloc/1.6/V_1, test39r1/T403/Main/T403/Main/V_0, test39r1/T403/Main/T403/Main/V_3_GP, WASANON16/blockrefreftran16, WASANON14/blockrefreftran14, WASANON12/blockrefreftran12, WASANON10/blockrefreftran10, ktop16, T402/.cctor/CZ:0:10/blockrefxxnewobj12, T402/.cctor/CZ:0:8/blockrefxxnewobj10, CS/0.6/refxxarray10, LinkedListOfInts/locker, LinkedListOfInts/ohandler, LinkedListOfInts/heapPool, LinkedListOfInts/sbrk, LinkedListOfInts/freelist, ktop14, System/BitConverter/IsLittleEndian, ktop12, KiwiSystem/Kiwi/tnow, KiwiSystem/Kiwi/old_pausemode_value, ktop10, clk cf @_BOOL*/__BOOL[d3.0x5fbfb88+$offset+kiwi_objectlock.0], 0)));
    goto T403_42;
  T403_42:
    /*skip*/;    /*ub T403/LinkedListOfInts/alloc/1.6/V_3_GP, test39r1/T403/Main/T403/Main/V_1, T403/LinkedListOfInts/alloc/1.6/V_1, test39r1/T403/Main/T403/Main/V_0, test39r1/T403/Main/T403/Main/V_3_GP, WASANON16/blockrefreftran16, WASANON14/blockrefreftran14, WASANON12/blockrefreftran12, WASANON10/blockrefreftran10, ktop16, T402/.cctor/CZ:0:10/blockrefxxnewobj12, T402/.cctor/CZ:0:8/blockrefxxnewobj10, CS/0.6/refxxarray10, LinkedListOfInts/locker, LinkedListOfInts/ohandler, LinkedListOfInts/heapPool, LinkedListOfInts/sbrk, LinkedListOfInts/freelist, ktop14, System/BitConverter/IsLittleEndian, ktop12, KiwiSystem/Kiwi/tnow, KiwiSystem/Kiwi/old_pausemode_value, ktop10, clk cf @_SINT*/__SINT[$offset+car.4+d4.test39r1_T403_Main_T403_Main_V_3_GP] = (50+3*test39r1_T403_Main_T403_Main_V_1);
    /*ub T403/LinkedListOfInts/alloc/1.6/V_3_GP, test39r1/T403/Main/T403/Main/V_1, T403/LinkedListOfInts/alloc/1.6/V_1, test39r1/T403/Main/T403/Main/V_0, test39r1/T403/Main/T403/Main/V_3_GP, WASANON16/blockrefreftran16, WASANON14/blockrefreftran14, WASANON12/blockrefreftran12, WASANON10/blockrefreftran10, ktop16, T402/.cctor/CZ:0:10/blockrefxxnewobj12, T402/.cctor/CZ:0:8/blockrefxxnewobj10, CS/0.6/refxxarray10, LinkedListOfInts/locker, LinkedListOfInts/ohandler, LinkedListOfInts/heapPool, LinkedListOfInts/sbrk, LinkedListOfInts/freelist, ktop14, System/BitConverter/IsLittleEndian, ktop12, KiwiSystem/Kiwi/tnow, KiwiSystem/Kiwi/old_pausemode_value, ktop10, clk cf @$star1$_LinkedListOfInts*/__star1__LinkedListOfInts[$offset+cdr.8+d4.test39r1_T403_Main_T403_Main_V_3_GP] = (test39r1_T403_Main_T403_Main_V_0);
    test39r1_T403_Main_T403_Main_V_0 = (test39r1_T403_Main_T403_Main_V_3_GP);
hpr_writeln("  Runtime Alloc Item %u", test39r1_T403_Main_T403_Main_V_1);
    test39r1_T403_Main_T403_Main_V_1 = (1+test39r1_T403_Main_T403_Main_V_1);
    goto T403_49;
  T403_34:
    /*skip*/;    goto T403_36;
  // End of DIC comment 1
}
// eof test39r1
