// test2r1
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:48:11
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test2r1.exe -vnl-resets=synchronous -vnl DUT.v -sim 1180 -diosim-vcd=test2r1.vcd -kiwic-kcode-dump=enable -give-backtrace -report-each-step

#include "test2r1.h"

// opath operation: 10: cgen2

 void test2r1::exe014()
 { 
  //  Method no 0 mname=test2r1
    if (xpc10nz==28/*28:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test2r1::exe110()
 { 
  //  Method no 1 mname=test2r1
    if (xpc10nz==27/*27:xpc10nz*/)
    xpc10nz = (28/*28:xpc10nz*/);
}

 void test2r1::exe210()
 { 
  //  Method no 2 mname=test2r1
    if (xpc10nz==26/*26:xpc10nz*/)
    xpc10nz = (27/*27:xpc10nz*/);
}

 void test2r1::exe310()
 { 
  //  Method no 3 mname=test2r1
    if (xpc10nz==25/*25:xpc10nz*/)
    xpc10nz = (16/*16:xpc10nz*/);
}

 void test2r1::exe410()
 { 
  //  Method no 4 mname=test2r1
    if (xpc10nz==24/*24:xpc10nz*/)
    xpc10nz = (25/*25:xpc10nz*/);
}

 void test2r1::exe510()
 { 
  //  Method no 5 mname=test2r1
    if (xpc10nz==23/*23:xpc10nz*/)
    xpc10nz = (24/*24:xpc10nz*/);
}

 void test2r1::exe610()
 { 
  //  Method no 6 mname=test2r1
    if (xpc10nz==22/*22:xpc10nz*/)
    xpc10nz = (19/*19:xpc10nz*/);
}

 void test2r1::exe710()
 { 
  //  Method no 7 mname=test2r1
    if (xpc10nz==21/*21:xpc10nz*/)
    xpc10nz = (22/*22:xpc10nz*/);
}

 void test2r1::exe810()
 { 
  //  Method no 8 mname=test2r1
    if (xpc10nz==20/*20:xpc10nz*/)
    xpc10nz = (21/*21:xpc10nz*/);
}

 void test2r1::exe910()
 { 
  //  Method no 9 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==19/*19:xpc10nz*/)
    xpc10nz = (20/*20:xpc10nz*/);
}

 void test2r1::exe1010()
 { 
  //  Method no 10 mname=test2r1
    if (!__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==19/*19:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test2r1::exe1110()
 { 
  //  Method no 11 mname=test2r1
    if (xpc10nz==18/*18:xpc10nz*/)
    xpc10nz = (19/*19:xpc10nz*/);
}

 void test2r1::exe1210()
 { 
  //  Method no 12 mname=test2r1
    if (xpc10nz==17/*17:xpc10nz*/)
    xpc10nz = (18/*18:xpc10nz*/);
}

 void test2r1::exe1310()
 { 
  //  Method no 13 mname=test2r1
    if (!__BOOL_CC_SCALbx18_emptyflag&&xpc10nz==16/*16:xpc10nz*/)
    xpc10nz = (23/*23:xpc10nz*/);
}

 void test2r1::exe1410()
 { 
  //  Method no 14 mname=test2r1
    if (__BOOL_CC_SCALbx18_emptyflag&&xpc10nz==16/*16:xpc10nz*/)
    xpc10nz = (17/*17:xpc10nz*/);
}

 void test2r1::exe1510()
 { 
  //  Method no 15 mname=test2r1
    if (xpc10nz==15/*15:xpc10nz*/)
    xpc10nz = (16/*16:xpc10nz*/);
}

 void test2r1::exe1610()
 { 
  //  Method no 16 mname=test2r1
    if (xpc10nz==14/*14:xpc10nz*/)
    xpc10nz = (15/*15:xpc10nz*/);
}

 void test2r1::exe1710()
 { 
  //  Method no 17 mname=test2r1
    if (xpc10nz==13/*13:xpc10nz*/)
    xpc10nz = (14/*14:xpc10nz*/);
}

 void test2r1::exe1810()
 { 
  //  Method no 18 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP!=0/*0:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==12/*12:xpc10nz*/)
    xpc10nz = (13/*13:xpc10nz*/);
}

 void test2r1::exe1910()
 { 
  //  Method no 19 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP==0/*0:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==12/*12:xpc10nz*/)
    xpc10nz = (13/*13:xpc10nz*/);
}

 void test2r1::exe2010()
 { 
  //  Method no 20 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP!=1/*1:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==11/*11:xpc10nz*/)
    xpc10nz = (12/*12:xpc10nz*/);
}

 void test2r1::exe2110()
 { 
  //  Method no 21 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP==1/*1:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==11/*11:xpc10nz*/)
    xpc10nz = (12/*12:xpc10nz*/);
}

 void test2r1::exe2210()
 { 
  //  Method no 22 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP!=0/*0:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==9/*9:xpc10nz*/)
    xpc10nz = (11/*11:xpc10nz*/);
}

 void test2r1::exe2310()
 { 
  //  Method no 23 mname=test2r1
    if (xpc10nz==10/*10:xpc10nz*/)
    xpc10nz = (11/*11:xpc10nz*/);
}

 void test2r1::exe2410()
 { 
  //  Method no 24 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP==0/*0:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==9/*9:xpc10nz*/)
    xpc10nz = (10/*10:xpc10nz*/);
}

 void test2r1::exe2510()
 { 
  //  Method no 25 mname=test2r1
    if (xpc10nz==8/*8:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test2r1::exe2610()
 { 
  //  Method no 26 mname=test2r1
    if (3>=test2r1_T403_Main_T403_Main_V_1&&test2r1_T403_Main_T403_Main_V_6_GP!=1/*1:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (9/*9:xpc10nz*/);
}

 void test2r1::exe2710()
 { 
  //  Method no 27 mname=test2r1
    if (xpc10nz==7/*7:xpc10nz*/)
    xpc10nz = (9/*9:xpc10nz*/);
}

 void test2r1::exe2810()
 { 
  //  Method no 28 mname=test2r1
    if (3>=test2r1_T403_Main_T403_Main_V_1&&test2r1_T403_Main_T403_Main_V_6_GP==1/*1:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (7/*7:xpc10nz*/);
}

 void test2r1::exe2910()
 { 
  //  Method no 29 mname=test2r1
    if (3<test2r1_T403_Main_T403_Main_V_1&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (8/*8:xpc10nz*/);
}

 void test2r1::exe3010()
 { 
  //  Method no 30 mname=test2r1
    if (xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test2r1::exe3110()
 { 
  //  Method no 31 mname=test2r1
    if (3>=test2r1_T403_Main_T403_Main_V_0&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test2r1::exe3210()
 { 
  //  Method no 32 mname=test2r1
    if (3<test2r1_T403_Main_T403_Main_V_0&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test2r1::exe3310()
 { 
  //  Method no 33 mname=test2r1
    if (!__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (26/*26:xpc10nz*/);
}

 void test2r1::exe3410()
 { 
  //  Method no 34 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test2r1::exe3510()
 { 
  //  Method no 35 mname=test2r1
    if (xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test2r1::exe3610()
 { 
  //  Method no 36 mname=test2r1
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test2r1::exe3710()
 { 
  //  Method no 37 mname=test2r1
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test2r1::exe3810()
 { 
  //  Method no 38 mname=test2r1
    if (xpc10nz==0/*0:xpc10nz*/)
     hpr_writeln("%s%i", "Test2r1: Times Table Capsule Channel Test: limit=", 3);
}

 void test2r1::exe3910()
 { 
  //  Method no 39 mname=test2r1
    if (3<test2r1_T403_Main_T403_Main_V_0&&xpc10nz==4/*4:xpc10nz*/)
     hpr_sysexit(0);
}

 void test2r1::exe4010()
 { 
  //  Method no 40 mname=test2r1
    if (3<test2r1_T403_Main_T403_Main_V_0&&xpc10nz==4/*4:xpc10nz*/)
     hpr_writeln("\nTest2r1: Capsule Times Table Test: Finished\n");
}

 void test2r1::exe4110()
 { 
  //  Method no 41 mname=test2r1
    isMULTIPLIER10RRh10shot0 = (3>=test2r1_T403_Main_T403_Main_V_1&&test2r1_T403_Main_T403_Main_V_6_GP==1/*1:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==6/*6:xpc10nz*/);
}

 void test2r1::exe4210()
 { 
  //  Method no 42 mname=test2r1
    isMULTIPLIER12RRh10shot0 = (test2r1_T403_Main_T403_Main_V_6_GP==0/*0:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==9/*9:xpc10nz*/);
}

 void test2r1::exe4310()
 { 
  //  Method no 43 mname=test2r1
    if (isMULTIPLIER12RRh10shot0)
    isMULTIPLIER12RRh10hold = (isMULTIPLIER12_RR);
}

 void test2r1::exe4410()
 { 
  //  Method no 44 mname=test2r1
    if (isMULTIPLIER10RRh10shot0)
    isMULTIPLIER10RRh10hold = (isMULTIPLIER10_RR);
}

 void test2r1::exe4510()
 { 
  //  Method no 45 mname=test2r1
    if (xpc10nz==0/*0:xpc10nz*/)
    test2r1_T403_Main_T403_Main_V_6_GP = (d5.1);
}

 void test2r1::exe4610()
 { 
  //  Method no 46 mname=test2r1
    if (xpc10nz==0/*0:xpc10nz*/)
    __BOOL_CC_MAPR10NoCE1_newlinef = (0x0);
}

 void test2r1::exe4710()
 { 
  //  Method no 47 mname=test2r1
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE1_capint = (45);
}

 void test2r1::exe4810()
 { 
  //  Method no 48 mname=test2r1
    if (xpc10nz==0/*0:xpc10nz*/)
    __BOOL_CC_SCALbx16_emptyflag = (0x1);
}

 void test2r1::exe4910()
 { 
  //  Method no 49 mname=test2r1
    if (xpc10nz==0/*0:xpc10nz*/)
    __BOOL_CC_SCALbx18_emptyflag = (0x1);
}

 void test2r1::exe5010()
 { 
  //  Method no 50 mname=test2r1
    if (xpc10nz==0/*0:xpc10nz*/)
    __BOOL_CC_MAPR10NoCE0_newlinef = (0x0);
}

 void test2r1::exe5110()
 { 
  //  Method no 51 mname=test2r1
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE0_capint = (23);
}

 void test2r1::exe5210()
 { 
  //  Method no 52 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==3/*3:xpc10nz*/)
    test2r1_T403_Main_T403_Main_V_6_GP = (d1.0);
}

 void test2r1::exe5310()
 { 
  //  Method no 53 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==3/*3:xpc10nz*/)
    __BOOL_CC_SCALbx16_emptyflag = (0x0);
}

 void test2r1::exe5410()
 { 
  //  Method no 54 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==3/*3:xpc10nz*/)
    test2r1_T403_Main_T403_Main_V_0 = (1);
}

 void test2r1::exe5510()
 { 
  //  Method no 55 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==3/*3:xpc10nz*/)
    __star1__Capsule_CC_SCALbx16_datum = (d5.1);
}

 void test2r1::exe5610()
 { 
  //  Method no 56 mname=test2r1
    if (xpc10nz==5/*5:xpc10nz*/)
    test2r1_T403_Main_T403_Main_V_1 = (1);
}

 void test2r1::exe5710()
 { 
  //  Method no 57 mname=test2r1
    if (3>=test2r1_T403_Main_T403_Main_V_1&&test2r1_T403_Main_T403_Main_V_6_GP==1/*1:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==6/*6:xpc10nz*/)
    isMULTIPLIER10_A1 = (test2r1_T403_Main_T403_Main_V_1);
}

 void test2r1::exe5810()
 { 
  //  Method no 58 mname=test2r1
    if (3>=test2r1_T403_Main_T403_Main_V_1&&test2r1_T403_Main_T403_Main_V_6_GP==1/*1:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==6/*6:xpc10nz*/)
    isMULTIPLIER10_A0 = (test2r1_T403_Main_T403_Main_V_0);
}

 void test2r1::exe5910()
 { 
  //  Method no 59 mname=test2r1
    if (3>=test2r1_T403_Main_T403_Main_V_1&&test2r1_T403_Main_T403_Main_V_6_GP==1/*1:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==7/*7:xpc10nz*/)
    __SINT_CC_MAPR10NoCE1_capint = (((xpc10nz==7/*7:xpc10nz*/)?isMULTIPLIER10_RR:isMULTIPLIER10RRh10hold));
}

 void test2r1::exe6010()
 { 
  //  Method no 60 mname=test2r1
    if (xpc10nz==8/*8:xpc10nz*/)
    test2r1_T403_Main_T403_Main_V_0 = (1+test2r1_T403_Main_T403_Main_V_0);
}

 void test2r1::exe6110()
 { 
  //  Method no 61 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP==0/*0:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==9/*9:xpc10nz*/)
    isMULTIPLIER12_A1 = (test2r1_T403_Main_T403_Main_V_1);
}

 void test2r1::exe6210()
 { 
  //  Method no 62 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP==0/*0:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==9/*9:xpc10nz*/)
    isMULTIPLIER12_A0 = (test2r1_T403_Main_T403_Main_V_0);
}

 void test2r1::exe6310()
 { 
  //  Method no 63 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP==0/*0:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==10/*10:xpc10nz*/)
    __SINT_CC_MAPR10NoCE0_capint = (((xpc10nz==10/*10:xpc10nz*/)?isMULTIPLIER12_RR:isMULTIPLIER12RRh10hold));
}

 void test2r1::exe6410()
 { 
  //  Method no 64 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP==1/*1:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==11/*11:xpc10nz*/)
    __BOOL_CC_MAPR10NoCE1_newlinef = (3==test2r1_T403_Main_T403_Main_V_1);
}

 void test2r1::exe6510()
 { 
  //  Method no 65 mname=test2r1
    if (test2r1_T403_Main_T403_Main_V_6_GP==0/*0:test2r1/T403/Main/T403/Main/V_6_GP*/&&xpc10nz==12/*12:xpc10nz*/)
    __BOOL_CC_MAPR10NoCE0_newlinef = (3==test2r1_T403_Main_T403_Main_V_1);
}

 void test2r1::exe6610()
 { 
  //  Method no 66 mname=test2r1
    if (__BOOL_CC_SCALbx18_emptyflag&&xpc10nz==16/*16:xpc10nz*/)
    __BOOL_CC_SCALbx18_emptyflag = (0x0);
}

 void test2r1::exe6710()
 { 
  //  Method no 67 mname=test2r1
    if (__BOOL_CC_SCALbx18_emptyflag&&xpc10nz==16/*16:xpc10nz*/)
    __star1__Capsule_CC_SCALbx18_datum = (test2r1_T403_Main_T403_Main_V_6_GP);
}

 void test2r1::exe6810()
 { 
  //  Method no 68 mname=test2r1
    if (!__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==19/*19:xpc10nz*/)
    test2r1_T403_Main_T403_Main_V_6_GP = (__star1__Capsule_CC_SCALbx16_datum);
}

 void test2r1::exe6910()
 { 
  //  Method no 69 mname=test2r1
    if (!__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==19/*19:xpc10nz*/)
    __BOOL_CC_SCALbx16_emptyflag = (0x1);
}

 void test2r1::exe7010()
 { 
  //  Method no 70 mname=test2r1
    if (!__BOOL_CC_SCALbx16_emptyflag&&xpc10nz==19/*19:xpc10nz*/)
    test2r1_T403_Main_T403_Main_V_1 = (1+test2r1_T403_Main_T403_Main_V_1);
}

 void test2r1::exe7110()
 { 
  //  Method no 71 mname=test2r1
    if (xpc12nz==17/*17:xpc12nz*/)
    xpc12nz = (6/*6:xpc12nz*/);
}

 void test2r1::exe7210()
 { 
  //  Method no 72 mname=test2r1
    if (xpc12nz==16/*16:xpc12nz*/)
    xpc12nz = (17/*17:xpc12nz*/);
}

 void test2r1::exe7310()
 { 
  //  Method no 73 mname=test2r1
    if (xpc12nz==15/*15:xpc12nz*/)
    xpc12nz = (16/*16:xpc12nz*/);
}

 void test2r1::exe7410()
 { 
  //  Method no 74 mname=test2r1
    if (xpc12nz==14/*14:xpc12nz*/)
    xpc12nz = (11/*11:xpc12nz*/);
}

 void test2r1::exe7510()
 { 
  //  Method no 75 mname=test2r1
    if (xpc12nz==13/*13:xpc12nz*/)
    xpc12nz = (14/*14:xpc12nz*/);
}

 void test2r1::exe7610()
 { 
  //  Method no 76 mname=test2r1
    if (xpc12nz==12/*12:xpc12nz*/)
    xpc12nz = (13/*13:xpc12nz*/);
}

 void test2r1::exe7710()
 { 
  //  Method no 77 mname=test2r1
    if (!__BOOL_CC_SCALbx16_emptyflag&&xpc12nz==11/*11:xpc12nz*/)
    xpc12nz = (12/*12:xpc12nz*/);
}

 void test2r1::exe7810()
 { 
  //  Method no 78 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc12nz==11/*11:xpc12nz*/)
    xpc12nz = (2/*2:xpc12nz*/);
}

 void test2r1::exe7910()
 { 
  //  Method no 79 mname=test2r1
    if (xpc12nz==10/*10:xpc12nz*/)
    xpc12nz = (11/*11:xpc12nz*/);
}

 void test2r1::exe8010()
 { 
  //  Method no 80 mname=test2r1
    if (xpc12nz==9/*9:xpc12nz*/)
    xpc12nz = (10/*10:xpc12nz*/);
}

 void test2r1::exe8110()
 { 
  //  Method no 81 mname=test2r1
    if (xpc12nz==8/*8:xpc12nz*/)
    xpc12nz = (9/*9:xpc12nz*/);
}

 void test2r1::exe8210()
 { 
  //  Method no 82 mname=test2r1
    if (xpc12nz==7/*7:xpc12nz*/)
    xpc12nz = (8/*8:xpc12nz*/);
}

 void test2r1::exe8310()
 { 
  //  Method no 83 mname=test2r1
    if (__BOOL_CC_SCALbx18_emptyflag&&xpc12nz==6/*6:xpc12nz*/)
    xpc12nz = (15/*15:xpc12nz*/);
}

 void test2r1::exe8410()
 { 
  //  Method no 84 mname=test2r1
    if ((!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&!__BOOL_CC_MAPR10NoCE0_newlinef&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/))
    if ((!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&!__BOOL_CC_MAPR10NoCE0_newlinef))
    xpc12nz = (7/*7:xpc12nz*/);
}

 void test2r1::exe8510()
 { 
  //  Method no 85 mname=test2r1
    if ((!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/))
    if ((!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/))
    xpc12nz = (7/*7:xpc12nz*/);
}

 void test2r1::exe8610()
 { 
  //  Method no 86 mname=test2r1
    if (xpc12nz==5/*5:xpc12nz*/)
    xpc12nz = (6/*6:xpc12nz*/);
}

 void test2r1::exe8710()
 { 
  //  Method no 87 mname=test2r1
    if (xpc12nz==4/*4:xpc12nz*/)
    xpc12nz = (5/*5:xpc12nz*/);
}

 void test2r1::exe8810()
 { 
  //  Method no 88 mname=test2r1
    if (xpc12nz==3/*3:xpc12nz*/)
    xpc12nz = (4/*4:xpc12nz*/);
}

 void test2r1::exe8910()
 { 
  //  Method no 89 mname=test2r1
    if (test2r1_T404_process_T404_process_V_0<10&&xpc12nz==2/*2:xpc12nz*/)
    xpc12nz = (3/*3:xpc12nz*/);
}

 void test2r1::exe9010()
 { 
  //  Method no 90 mname=test2r1
    if (test2r1_T404_process_T404_process_V_0>=10&&xpc12nz==2/*2:xpc12nz*/)
    xpc12nz = (2/*2:xpc12nz*/);
}

 void test2r1::exe9110()
 { 
  //  Method no 91 mname=test2r1
    if (xpc12nz==1/*1:xpc12nz*/)
    xpc12nz = (2/*2:xpc12nz*/);
}

 void test2r1::exe9210()
 { 
  //  Method no 92 mname=test2r1
    if (xpc12nz==0/*0:xpc12nz*/)
    xpc12nz = (1/*1:xpc12nz*/);
}

 void test2r1::exe9310()
 { 
  //  Method no 93 mname=test2r1
    if (test2r1_T404_process_T404_process_V_0>=10&&xpc12nz==2/*2:xpc12nz*/)
     hpr_sysexit(0);
}

 void test2r1::exe9410()
 { 
  //  Method no 94 mname=test2r1
    if ((!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&!__BOOL_CC_MAPR10NoCE0_newlinef&&xpc12nz==6/*6:xpc12nz*/))
    if (!__BOOL_CC_SCALbx18_emptyflag)
     hpr_write("%u ", ((__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/)?__SINT_CC_MAPR10NoCE1_capint:((__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/)?__SINT_CC_MAPR10NoCE0_capint:0/*UNDEF*/)));
}

 void test2r1::exe9510()
 { 
  //  Method no 95 mname=test2r1
    if ((!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/))
    if ((!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/))
     hpr_writeln("");
}

 void test2r1::exe9610()
 { 
  //  Method no 96 mname=test2r1
    if ((!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/))
    if (!__BOOL_CC_SCALbx18_emptyflag)
     hpr_write("%u ", ((__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/)?__SINT_CC_MAPR10NoCE1_capint:((__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/)?__SINT_CC_MAPR10NoCE0_capint:0/*UNDEF*/)));
}

 void test2r1::exe9710()
 { 
  //  Method no 97 mname=test2r1
    if (isMULTIPLIER12RRh10shot0)
    isMULTIPLIER12RRh10hold = (isMULTIPLIER12_RR);
}

 void test2r1::exe9810()
 { 
  //  Method no 98 mname=test2r1
    if (isMULTIPLIER10RRh10shot0)
    isMULTIPLIER10RRh10hold = (isMULTIPLIER10_RR);
}

 void test2r1::exe9910()
 { 
  //  Method no 99 mname=test2r1
    if (xpc12nz==1/*1:xpc12nz*/)
    test2r1_T404_process_T404_process_V_0 = (0);
}

 void test2r1::exe10010()
 { 
  //  Method no 100 mname=test2r1
    if ((!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&!__BOOL_CC_MAPR10NoCE0_newlinef&&xpc12nz==6/*6:xpc12nz*/))
    if ((!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&!__BOOL_CC_MAPR10NoCE0_newlinef)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/))
    __BOOL_CC_SCALbx18_emptyflag = (0x1);
}

 void test2r1::exe10110()
 { 
  //  Method no 101 mname=test2r1
    if ((!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&!__BOOL_CC_MAPR10NoCE0_newlinef&&xpc12nz==6/*6:xpc12nz*/))
    if ((!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&!__BOOL_CC_MAPR10NoCE0_newlinef)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&!__BOOL_CC_MAPR10NoCE1_newlinef&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum!=0/*0:test2r1/T404/process/T404/process/V_1_GP*/))
    test2r1_T404_process_T404_process_V_1_GP = (__star1__Capsule_CC_SCALbx18_datum);
}

 void test2r1::exe10210()
 { 
  //  Method no 102 mname=test2r1
    if ((!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/))
    if ((!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/))
    __BOOL_CC_SCALbx18_emptyflag = (0x1);
}

 void test2r1::exe10310()
 { 
  //  Method no 103 mname=test2r1
    if ((!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/&&xpc12nz==6/*6:xpc12nz*/))
    if ((!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE1_newlinef&&__star1__Capsule_CC_SCALbx18_datum==1/*1:test2r1/T404/process/T404/process/V_1_GP*/)||(!__BOOL_CC_SCALbx18_emptyflag&&__BOOL_CC_MAPR10NoCE0_newlinef&&__star1__Capsule_CC_SCALbx18_datum==0/*0:test2r1/T404/process/T404/process/V_1_GP*/))
    test2r1_T404_process_T404_process_V_1_GP = (__star1__Capsule_CC_SCALbx18_datum);
}

 void test2r1::exe10410()
 { 
  //  Method no 104 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc12nz==11/*11:xpc12nz*/)
    __BOOL_CC_SCALbx16_emptyflag = (0x0);
}

 void test2r1::exe10510()
 { 
  //  Method no 105 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc12nz==11/*11:xpc12nz*/)
    __star1__Capsule_CC_SCALbx16_datum = (test2r1_T404_process_T404_process_V_1_GP);
}

 void test2r1::exe10610()
 { 
  //  Method no 106 mname=test2r1
    if (__BOOL_CC_SCALbx16_emptyflag&&xpc12nz==11/*11:xpc12nz*/)
    test2r1_T404_process_T404_process_V_0 = (1+test2r1_T404_process_T404_process_V_0);
}

 void test2r1::exe012()
 { 
  //  Method no 0 mname=isMULTIPLIER12.CV_INT_FL1_MULTIPLIER_S
    isMULTIPLIER12_RR = (isMULTIPLIER12_A0*isMULTIPLIER12_A1);
}

 void test2r1::exe010()
 { 
  //  Method no 0 mname=isMULTIPLIER10.CV_INT_FL1_MULTIPLIER_S
    isMULTIPLIER10_RR = (isMULTIPLIER10_A0*isMULTIPLIER10_A1);
}
// eof test2r1
