// test29
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:54:24
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test29.exe -diosim-vcd=test29.vcd -vnl-resets=synchronous -vnl DUT.v -sim 1800 -give-backtrace -report-each-step

#include "test29.h"

// opath operation: 10: cgen2

 void test29::exe010()
 { 
  //  Method no 0 mname=test29
    if (test29_T402_Main_T402_Main_V_8>=3&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test29::exe110()
 { 
  //  Method no 1 mname=test29
    if (test29_T402_Main_T402_Main_V_8<3&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test29::exe210()
 { 
  //  Method no 2 mname=test29
    if (xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test29::exe310()
 { 
  //  Method no 3 mname=test29
    if (xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test29::exe410()
 { 
  //  Method no 4 mname=test29
    if (test29_T402_Main_T402_Main_V_6<4&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test29::exe510()
 { 
  //  Method no 5 mname=test29
    if (test29_T402_Main_T402_Main_V_6>=4&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test29::exe610()
 { 
  //  Method no 6 mname=test29
    if (xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test29::exe710()
 { 
  //  Method no 7 mname=test29
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test29::exe810()
 { 
  //  Method no 8 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test29::exe910()
 { 
  //  Method no 9 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE0_ARA0[0] = (12);
}

 void test29::exe1010()
 { 
  //  Method no 10 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE0_ARA0[1] = (13);
}

 void test29::exe1110()
 { 
  //  Method no 11 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE0_ARA0[2] = (14);
}

 void test29::exe1210()
 { 
  //  Method no 12 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE1_ARA0[0] = (2);
}

 void test29::exe1310()
 { 
  //  Method no 13 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE1_ARA0[1] = (3);
}

 void test29::exe1410()
 { 
  //  Method no 14 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE1_ARA0[2] = (4);
}

 void test29::exe1510()
 { 
  //  Method no 15 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE2_ARA0[0] = (312);
}

 void test29::exe1610()
 { 
  //  Method no 16 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE2_ARA0[1] = (313);
}

 void test29::exe1710()
 { 
  //  Method no 17 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE2_ARA0[2] = (314);
}

 void test29::exe1810()
 { 
  //  Method no 18 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE3_ARA0[0] = (412);
}

 void test29::exe1910()
 { 
  //  Method no 19 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE3_ARA0[1] = (413);
}

 void test29::exe2010()
 { 
  //  Method no 20 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE3_ARA0[2] = (414);
}

 void test29::exe2110()
 { 
  //  Method no 21 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[0] = (d1.0);
}

 void test29::exe2210()
 { 
  //  Method no 22 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[1] = (d2.1);
}

 void test29::exe2310()
 { 
  //  Method no 23 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[2] = (d3.2);
}

 void test29::exe2410()
 { 
  //  Method no 24 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[3] = (d4.3);
}

 void test29::exe2510()
 { 
  //  Method no 25 mname=test29
    if (test29_T402_Main_T402_Main_V_6>=4&&xpc10nz==3/*3:xpc10nz*/)
     hpr_sysexit(0);
}

 void test29::exe2610()
 { 
  //  Method no 26 mname=test29
    if (xpc10nz==4/*4:xpc10nz*/)
     hpr_writeln(" Test29 i=%u  s=%u.", test29_T402_Main_T402_Main_V_6, test29_T402_Main_T402_Main_V_5+(((__s__SINT_CC_SCALbx12_ARA0[test29_T402_Main_T402_Main_V_6]==3/*3:USA12*/)?__SINT_CC_MAPR10NoCE3_ARA0[1]:((__s__SINT_CC_SCALbx12_ARA0[test29_T402_Main_T402_Main_V_6]==2/*2:USA12*/)?__SINT_CC_MAPR10NoCE2_ARA0[1]:((__s__SINT_CC_SCALbx12_ARA0[test29_T402_Main_T402_Main_V_6]==1/*1:USA12*/)?__SINT_CC_MAPR10NoCE1_ARA0[1]:((__s__SINT_CC_SCALbx12_ARA0[test29_T402_Main_T402_Main_V_6]==0/*0:USA12*/)?__SINT_CC_MAPR10NoCE0_ARA0[1]:0/*UNDEF*/))))));
}

 void test29::exe2710()
 { 
  //  Method no 27 mname=test29
    if (xpc10nz==5/*5:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[2] = (__s__SINT_CC_SCALbx12_ARA0[1]);
}

 void test29::exe2810()
 { 
  //  Method no 28 mname=test29
    if (xpc10nz==5/*5:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[1] = (__s__SINT_CC_SCALbx12_ARA0[2]);
}

 void test29::exe2910()
 { 
  //  Method no 29 mname=test29
    if (test29_T402_Main_T402_Main_V_8<3&&xpc10nz==6/*6:xpc10nz*/)
     hpr_writeln(" Test29 ii=%u  baser=%u.", test29_T402_Main_T402_Main_V_8, ((test29_T402_Main_T402_Main_V_7_GP==3/*3:test29/T402/Main/T402/Main/V_7_GP*/)?__SINT_CC_MAPR10NoCE3_ARA0[test29_T402_Main_T402_Main_V_8]:((test29_T402_Main_T402_Main_V_7_GP==2/*2:test29/T402/Main/T402/Main/V_7_GP*/)?__SINT_CC_MAPR10NoCE2_ARA0[test29_T402_Main_T402_Main_V_8]:((test29_T402_Main_T402_Main_V_7_GP==1/*1:test29/T402/Main/T402/Main/V_7_GP*/)?__SINT_CC_MAPR10NoCE1_ARA0[test29_T402_Main_T402_Main_V_8]:((test29_T402_Main_T402_Main_V_7_GP==0/*0:test29/T402/Main/T402/Main/V_7_GP*/)?__SINT_CC_MAPR10NoCE0_ARA0[test29_T402_Main_T402_Main_V_8]:0/*UNDEF*/)))));
}

 void test29::exe3010()
 { 
  //  Method no 30 mname=test29
    if (xpc10nz==0/*0:xpc10nz*/)
    test29_T402_Main_T402_Main_V_7_GP = (d4.3);
}

 void test29::exe3110()
 { 
  //  Method no 31 mname=test29
    if (xpc10nz==1/*1:xpc10nz*/)
    test29_T402_Main_T402_Main_V_5 = (1);
}

 void test29::exe3210()
 { 
  //  Method no 32 mname=test29
    if (xpc10nz==2/*2:xpc10nz*/)
    test29_T402_Main_T402_Main_V_6 = (0);
}

 void test29::exe3310()
 { 
  //  Method no 33 mname=test29
    if (xpc10nz==4/*4:xpc10nz*/)
    test29_T402_Main_T402_Main_V_5 = (test29_T402_Main_T402_Main_V_5+(((__s__SINT_CC_SCALbx12_ARA0[test29_T402_Main_T402_Main_V_6]==3/*3:USA12*/)?__SINT_CC_MAPR10NoCE3_ARA0[1]:((__s__SINT_CC_SCALbx12_ARA0[test29_T402_Main_T402_Main_V_6]==2/*2:USA12*/)?__SINT_CC_MAPR10NoCE2_ARA0[1]:((__s__SINT_CC_SCALbx12_ARA0[test29_T402_Main_T402_Main_V_6]==1/*1:USA12*/)?__SINT_CC_MAPR10NoCE1_ARA0[1]:((__s__SINT_CC_SCALbx12_ARA0[test29_T402_Main_T402_Main_V_6]==0/*0:USA12*/)?__SINT_CC_MAPR10NoCE0_ARA0[1]:0/*UNDEF*/))))));
}

 void test29::exe3410()
 { 
  //  Method no 34 mname=test29
    if (xpc10nz==5/*5:xpc10nz*/)
    test29_T402_Main_T402_Main_V_7_GP = (__s__SINT_CC_SCALbx12_ARA0[2]);
}

 void test29::exe3510()
 { 
  //  Method no 35 mname=test29
    if (xpc10nz==5/*5:xpc10nz*/)
    test29_T402_Main_T402_Main_V_8 = (0);
}

 void test29::exe3610()
 { 
  //  Method no 36 mname=test29
    if (test29_T402_Main_T402_Main_V_8>=3&&xpc10nz==6/*6:xpc10nz*/)
    test29_T402_Main_T402_Main_V_6 = (1+test29_T402_Main_T402_Main_V_6);
}

 void test29::exe3710()
 { 
  //  Method no 37 mname=test29
    if (test29_T402_Main_T402_Main_V_8<3&&xpc10nz==6/*6:xpc10nz*/)
    test29_T402_Main_T402_Main_V_8 = (1+test29_T402_Main_T402_Main_V_8);
}
// eof test29
