// test28
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:54:12
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test28.exe -diosim-vcd=test28.vcd -sim 1800 -give-backtrace -report-each-step

#include "test28.h"

// opath operation: 10: cgen2

 void test28::exe010()
 { 
  //  Method no 0 mname=test28
    if (xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test28::exe110()
 { 
  //  Method no 1 mname=test28
    if (xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test28::exe210()
 { 
  //  Method no 2 mname=test28
    if (xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test28::exe310()
 { 
  //  Method no 3 mname=test28
    if (test28_T402_Main_T402_Main_V_7_GP<0x5&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test28::exe410()
 { 
  //  Method no 4 mname=test28
    if (test28_T402_Main_T402_Main_V_7_GP>=0x5&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test28::exe510()
 { 
  //  Method no 5 mname=test28
    if (test28_T402_Main_T402_Main_V_7_GP<0x5&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test28::exe610()
 { 
  //  Method no 6 mname=test28
    if (test28_T402_Main_T402_Main_V_7_GP>=0x5&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test28::exe710()
 { 
  //  Method no 7 mname=test28
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test28::exe810()
 { 
  //  Method no 8 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test28::exe910()
 { 
  //  Method no 9 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[0] = (d1.0);
}

 void test28::exe1010()
 { 
  //  Method no 10 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[1] = (d2.1);
}

 void test28::exe1110()
 { 
  //  Method no 11 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[2] = (d3.2);
}

 void test28::exe1210()
 { 
  //  Method no 12 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[3] = (d4.3);
}

 void test28::exe1310()
 { 
  //  Method no 13 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    __s__SINT_CC_SCALbx12_ARA0[4] = (d2.1);
}

 void test28::exe1410()
 { 
  //  Method no 14 mname=test28
    if (test28_T402_Main_T402_Main_V_7_GP<0x5&&xpc10nz==2/*2:xpc10nz*/)
     hpr_writeln(" Test28 p1 i=%u  s=%u.", test28_T402_Main_T402_Main_V_7_GP, 0x30d40+(((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==3/*3:USA12*/)?__SINT_CC_MAPR10NoCE3_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==2/*2:USA12*/)?__SINT_CC_MAPR10NoCE2_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==1/*1:USA12*/)?__SINT_CC_MAPR10NoCE1_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==0/*0:USA12*/)?__SINT_CC_MAPR10NoCE0_SCALARF0_0:0/*UNDEF*/))))));
}

 void test28::exe1510()
 { 
  //  Method no 15 mname=test28
    if (test28_T402_Main_T402_Main_V_7_GP>=0x5&&xpc10nz==3/*3:xpc10nz*/)
     hpr_sysexit(0);
}

 void test28::exe1610()
 { 
  //  Method no 16 mname=test28
    if (xpc10nz==4/*4:xpc10nz*/)
     hpr_writeln(" Test28 p2 i=%u  s=%u.", test28_T402_Main_T402_Main_V_7_GP, test28_T402_Main_T402_Main_V_5+(((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==3/*3:USA12*/)?__SINT_CC_MAPR10NoCE3_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==2/*2:USA12*/)?__SINT_CC_MAPR10NoCE2_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==1/*1:USA12*/)?__SINT_CC_MAPR10NoCE1_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==0/*0:USA12*/)?__SINT_CC_MAPR10NoCE0_SCALARF0_0:0/*UNDEF*/))))));
}

 void test28::exe1710()
 { 
  //  Method no 17 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE3_SCALARF0_0 = (413);
}

 void test28::exe1810()
 { 
  //  Method no 18 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE2_SCALARF0_0 = (313);
}

 void test28::exe1910()
 { 
  //  Method no 19 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE1_SCALARF0_0 = (213);
}

 void test28::exe2010()
 { 
  //  Method no 20 mname=test28
    if (xpc10nz==0/*0:xpc10nz*/)
    __SINT_CC_MAPR10NoCE0_SCALARF0_0 = (13);
}

 void test28::exe2110()
 { 
  //  Method no 21 mname=test28
    if (xpc10nz==1/*1:xpc10nz*/)
    test28_T402_Main_T402_Main_V_7_GP = (0);
}

 void test28::exe2210()
 { 
  //  Method no 22 mname=test28
    if (xpc10nz==1/*1:xpc10nz*/)
    test28_T402_Main_T402_Main_V_5 = (0);
}

 void test28::exe2310()
 { 
  //  Method no 23 mname=test28
    if (test28_T402_Main_T402_Main_V_7_GP<0x5&&xpc10nz==2/*2:xpc10nz*/)
    test28_T402_Main_T402_Main_V_5 = (0x30d40+(((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==3/*3:USA12*/)?__SINT_CC_MAPR10NoCE3_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==2/*2:USA12*/)?__SINT_CC_MAPR10NoCE2_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==1/*1:USA12*/)?__SINT_CC_MAPR10NoCE1_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==0/*0:USA12*/)?__SINT_CC_MAPR10NoCE0_SCALARF0_0:0/*UNDEF*/))))));
}

 void test28::exe2410()
 { 
  //  Method no 24 mname=test28
    if (test28_T402_Main_T402_Main_V_7_GP>=0x5&&xpc10nz==2/*2:xpc10nz*/)
    test28_T402_Main_T402_Main_V_7_GP = (0);
}

 void test28::exe2510()
 { 
  //  Method no 25 mname=test28
    if (test28_T402_Main_T402_Main_V_7_GP>=0x5&&xpc10nz==2/*2:xpc10nz*/)
    test28_T402_Main_T402_Main_V_5 = (0);
}

 void test28::exe2610()
 { 
  //  Method no 26 mname=test28
    if (xpc10nz==4/*4:xpc10nz*/)
    test28_T402_Main_T402_Main_V_5 = (test28_T402_Main_T402_Main_V_5+(((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==3/*3:USA12*/)?__SINT_CC_MAPR10NoCE3_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==2/*2:USA12*/)?__SINT_CC_MAPR10NoCE2_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==1/*1:USA12*/)?__SINT_CC_MAPR10NoCE1_SCALARF0_0:((__s__SINT_CC_SCALbx12_ARA0[test28_T402_Main_T402_Main_V_7_GP]==0/*0:USA12*/)?__SINT_CC_MAPR10NoCE0_SCALARF0_0:0/*UNDEF*/))))));
}

 void test28::exe2710()
 { 
  //  Method no 27 mname=test28
    if (xpc10nz==5/*5:xpc10nz*/)
    test28_T402_Main_T402_Main_V_7_GP = (1+test28_T402_Main_T402_Main_V_7_GP);
}

 void test28::exe2810()
 { 
  //  Method no 28 mname=test28
    if (xpc10nz==6/*6:xpc10nz*/)
    test28_T402_Main_T402_Main_V_7_GP = (1+test28_T402_Main_T402_Main_V_7_GP);
}
// eof test28
