// test
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 30/12/2016 10:30:35
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test0.exe -vnl DUT.v -vnl-resets=synchronous -sim 1800 -kiwic-cil-dump=combined -kiwic-kcode-dump=enable -give-backtrace -report-each-step

#include "test.h"

// opath operation: 10: cgen2

 void test::exe012()
 { 
  //  Method no 0 mname=test
    if (xpc10nz==19/*19:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test::exe110()
 { 
  //  Method no 1 mname=test
    if (xpc10nz==18/*18:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test::exe210()
 { 
  //  Method no 2 mname=test
    if (xpc10nz==17/*17:xpc10nz*/)
    xpc10nz = (18/*18:xpc10nz*/);
}

 void test::exe310()
 { 
  //  Method no 3 mname=test
    if (xpc10nz==16/*16:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test::exe410()
 { 
  //  Method no 4 mname=test
    if (xpc10nz==15/*15:xpc10nz*/)
    xpc10nz = (8/*8:xpc10nz*/);
}

 void test::exe510()
 { 
  //  Method no 5 mname=test
    if (xpc10nz==14/*14:xpc10nz*/)
    xpc10nz = (10/*10:xpc10nz*/);
}

 void test::exe610()
 { 
  //  Method no 6 mname=test
    if (xpc10nz==13/*13:xpc10nz*/)
    xpc10nz = (14/*14:xpc10nz*/);
}

 void test::exe710()
 { 
  //  Method no 7 mname=test
    if (T403_test_st6_0_30_V_1_GP<<1>=0x0&&xpc10nz==12/*12:xpc10nz*/)
    xpc10nz = (13/*13:xpc10nz*/);
}

 void test::exe810()
 { 
  //  Method no 8 mname=test
    if (T403_test_st6_0_30_V_1_GP<<1<0x0&&xpc10nz==12/*12:xpc10nz*/)
    xpc10nz = (13/*13:xpc10nz*/);
}

 void test::exe910()
 { 
  //  Method no 9 mname=test
    if (xpc10nz==11/*11:xpc10nz*/)
    xpc10nz = (12/*12:xpc10nz*/);
}

 void test::exe1010()
 { 
  //  Method no 10 mname=test
    if (T403_test_st6_0_30_V_0_GP<4&&xpc10nz==10/*10:xpc10nz*/)
    xpc10nz = (11/*11:xpc10nz*/);
}

 void test::exe1110()
 { 
  //  Method no 11 mname=test
    if (T403_test_st6_0_30_V_0_GP>=4&&xpc10nz==10/*10:xpc10nz*/)
    xpc10nz = (10/*10:xpc10nz*/);
}

 void test::exe1210()
 { 
  //  Method no 12 mname=test
    if (xpc10nz==9/*9:xpc10nz*/)
    xpc10nz = (10/*10:xpc10nz*/);
}

 void test::exe1310()
 { 
  //  Method no 13 mname=test
    if (T403_test_st5_0_27_V_1_GP<2&&xpc10nz==8/*8:xpc10nz*/)
    xpc10nz = (15/*15:xpc10nz*/);
}

 void test::exe1410()
 { 
  //  Method no 14 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==8/*8:xpc10nz*/)
    xpc10nz = (9/*9:xpc10nz*/);
}

 void test::exe1510()
 { 
  //  Method no 15 mname=test
    if (xpc10nz==7/*7:xpc10nz*/)
    xpc10nz = (8/*8:xpc10nz*/);
}

 void test::exe1610()
 { 
  //  Method no 16 mname=test
    if (T403_test_st6_0_30_V_0_GP<3&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (16/*16:xpc10nz*/);
}

 void test::exe1710()
 { 
  //  Method no 17 mname=test
    if (T403_test_st6_0_30_V_0_GP>=3&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (7/*7:xpc10nz*/);
}

 void test::exe1810()
 { 
  //  Method no 18 mname=test
    if (T403_test_st5_0_27_V_1_GP<2&&xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (17/*17:xpc10nz*/);
}

 void test::exe1910()
 { 
  //  Method no 19 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test::exe2010()
 { 
  //  Method no 20 mname=test
    if (xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (19/*19:xpc10nz*/);
}

 void test::exe2110()
 { 
  //  Method no 21 mname=test
    if (T403_test_st5_0_27_V_1_GP<4&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test::exe2210()
 { 
  //  Method no 22 mname=test
    if (T403_test_st5_0_27_V_1_GP>=4&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test::exe2310()
 { 
  //  Method no 23 mname=test
    if (T403_test_st5_0_27_V_1_GP<1&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test::exe2410()
 { 
  //  Method no 24 mname=test
    if (T403_test_st5_0_27_V_1_GP>=1&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test::exe2510()
 { 
  //  Method no 25 mname=test
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test::exe2610()
 { 
  //  Method no 26 mname=test
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test::exe2710()
 { 
  //  Method no 27 mname=test
    if (xpc10nz==0/*0:xpc10nz*/)
     hpr_writeln("Test0 st0");
}

 void test::exe2810()
 { 
  //  Method no 28 mname=test
    if (T403_test_st5_0_27_V_1_GP<1&&xpc10nz==2/*2:xpc10nz*/)
     hpr_writeln(" st0 byte left shift: %H %H", T403_test_st0_0_12_V_3_GP, T403_test_st3_0_21_V_3_GP);
}

 void test::exe2910()
 { 
  //  Method no 29 mname=test
    if (T403_test_st5_0_27_V_1_GP>=1&&xpc10nz==2/*2:xpc10nz*/)
     hpr_writeln(" st0 byte left shift: %H %H", T403_test_st0_0_12_V_3_GP, T403_test_st3_0_21_V_3_GP);
}

 void test::exe3010()
 { 
  //  Method no 30 mname=test
    if (T403_test_st5_0_27_V_1_GP>=4&&xpc10nz==3/*3:xpc10nz*/)
     hpr_writeln("Test0 st3");
}

 void test::exe3110()
 { 
  //  Method no 31 mname=test
    if (T403_test_st5_0_27_V_1_GP>=4&&xpc10nz==3/*3:xpc10nz*/)
     hpr_writeln("<><><>> data: %H", 0xdead00ef);
}

 void test::exe3210()
 { 
  //  Method no 32 mname=test
    if (T403_test_st5_0_27_V_1_GP>=4&&xpc10nz==3/*3:xpc10nz*/)
     hpr_writeln("Test0 st2");
}

 void test::exe3310()
 { 
  //  Method no 33 mname=test
    if (T403_test_st5_0_27_V_1_GP>=4&&xpc10nz==3/*3:xpc10nz*/)
     hpr_writeln("<><><>> mask: %H", 0xffffffffffff00ff);
}

 void test::exe3410()
 { 
  //  Method no 34 mname=test
    if (T403_test_st5_0_27_V_1_GP>=4&&xpc10nz==3/*3:xpc10nz*/)
     hpr_writeln("Test0 st1");
}

 void test::exe3510()
 { 
  //  Method no 35 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln();
}

 void test::exe3610()
 { 
  //  Method no 36 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln("preloop   shr     %h", -1);
}

 void test::exe3710()
 { 
  //  Method no 37 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln("preloop   shr.uns %h", 0xffffff);
}

 void test::exe3810()
 { 
  //  Method no 38 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln("Test0 st4");
}

 void test::exe3910()
 { 
  //  Method no 39 mname=test
    if (T403_test_st6_0_30_V_0_GP>=3&&xpc10nz==6/*6:xpc10nz*/)
     hpr_writeln("shipton test st5a: one's complement  %u %u --> %u", 32, 101, -135);
}

 void test::exe4010()
 { 
  //  Method no 40 mname=test
    if (T403_test_st6_0_30_V_0_GP>=3&&xpc10nz==6/*6:xpc10nz*/)
     hpr_writeln("Test0 st5");
}

 void test::exe4110()
 { 
  //  Method no 41 mname=test
    if (T403_test_st5_0_27_V_1_GP<2&&xpc10nz==8/*8:xpc10nz*/)
     hpr_writeln("shipton test st5b: one's complement  %u %u --> %u", test_t1, test_t2, ~test_t1+~test_t2);
}

 void test::exe4210()
 { 
  //  Method no 42 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==8/*8:xpc10nz*/)
     hpr_writeln("Test0 st6");
}

 void test::exe4310()
 { 
  //  Method no 43 mname=test
    if (T403_test_st6_0_30_V_0_GP>=4&&xpc10nz==10/*10:xpc10nz*/)
     hpr_sysexit(0);
}

 void test::exe4410()
 { 
  //  Method no 44 mname=test
    if (xpc10nz==11/*11:xpc10nz*/)
     hpr_writeln("dfsin ulong to long -ve kk=%u pp=%H %d", T403_test_st6_0_30_V_0_GP, 0xff000000<<(63&16*T403_test_st6_0_30_V_0_GP), (0xff000000<<(63&16*T403_test_st6_0_30_V_0_GP))<<1);
}

 void test::exe4510()
 { 
  //  Method no 45 mname=test
    if (T403_test_st6_0_30_V_1_GP<<1<0x0&&xpc10nz==12/*12:xpc10nz*/)
     hpr_writeln("Went -ve");
}

 void test::exe4610()
 { 
  //  Method no 46 mname=test
    if (xpc10nz==16/*16:xpc10nz*/)
     hpr_writeln("        shr     %h", -1);
}

 void test::exe4710()
 { 
  //  Method no 47 mname=test
    if (xpc10nz==16/*16:xpc10nz*/)
     hpr_writeln("inloop  shr.uns %h", T403_test_st4_0_24_V_0_GP);
}

 void test::exe4810()
 { 
  //  Method no 48 mname=test
    if (xpc10nz==18/*18:xpc10nz*/)
     hpr_writeln("v3 %H", T403_test_st3_0_21_V_3_GP);
}

 void test::exe4910()
 { 
  //  Method no 49 mname=test
    if (xpc10nz==18/*18:xpc10nz*/)
     hpr_writeln("v2 %H", T403_test_st4_0_24_V_0_GP);
}

 void test::exe5010()
 { 
  //  Method no 50 mname=test
    if (xpc10nz==19/*19:xpc10nz*/)
     hpr_writeln(" st0 byte arith %u: summ=%d  prod=%d", T403_test_st5_0_27_V_1_GP, T403_test_st3_0_21_V_3_GP, T403_test_st4_0_24_V_0_GP);
}

 void test::exe5110()
 { 
  //  Method no 51 mname=test
    iuMULTIPLIER10RRh10shot0 = (T403_test_st5_0_27_V_1_GP<4&&xpc10nz==3/*3:xpc10nz*/);
}

 void test::exe5210()
 { 
  //  Method no 52 mname=test
    if (iuMULTIPLIER10RRh10shot0)
    iuMULTIPLIER10RRh10hold = (iuMULTIPLIER10_RR);
}

 void test::exe5310()
 { 
  //  Method no 53 mname=test
    if (xpc10nz==0/*0:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (0);
}

 void test::exe5410()
 { 
  //  Method no 54 mname=test
    if (xpc10nz==0/*0:xpc10nz*/)
    T403_test_st0_0_12_V_3_GP = (0x44);
}

 void test::exe5510()
 { 
  //  Method no 55 mname=test
    if (xpc10nz==0/*0:xpc10nz*/)
    test_wout = (0x2000000000);
}

 void test::exe5610()
 { 
  //  Method no 56 mname=test
    if (xpc10nz==0/*0:xpc10nz*/)
    test_t2 = (101);
}

 void test::exe5710()
 { 
  //  Method no 57 mname=test
    if (xpc10nz==0/*0:xpc10nz*/)
    test_t1 = (32);
}

 void test::exe5810()
 { 
  //  Method no 58 mname=test
    if (xpc10nz==1/*1:xpc10nz*/)
    T403_test_st3_0_21_V_3_GP = (T403_test_st0_0_12_V_3_GP<<24);
}

 void test::exe5910()
 { 
  //  Method no 59 mname=test
    if (T403_test_st5_0_27_V_1_GP<1&&xpc10nz==2/*2:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (1+T403_test_st5_0_27_V_1_GP);
}

 void test::exe6010()
 { 
  //  Method no 60 mname=test
    if (T403_test_st5_0_27_V_1_GP<1&&xpc10nz==2/*2:xpc10nz*/)
    T403_test_st0_0_12_V_3_GP = ((unsigned char)(1+T403_test_st0_0_12_V_3_GP));
}

 void test::exe6110()
 { 
  //  Method no 61 mname=test
    if (T403_test_st5_0_27_V_1_GP>=1&&xpc10nz==2/*2:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (0);
}

 void test::exe6210()
 { 
  //  Method no 62 mname=test
    if (T403_test_st5_0_27_V_1_GP>=1&&xpc10nz==2/*2:xpc10nz*/)
    T403_test_st0_0_12_V_3_GP = (0xfa);
}

 void test::exe6310()
 { 
  //  Method no 63 mname=test
    if (T403_test_st5_0_27_V_1_GP>=1&&xpc10nz==2/*2:xpc10nz*/)
    T403_test_st0_0_12_V_4 = (0x0);
}

 void test::exe6410()
 { 
  //  Method no 64 mname=test
    if (T403_test_st5_0_27_V_1_GP<4&&xpc10nz==3/*3:xpc10nz*/)
    iuMULTIPLIER10_A1 = (T403_test_st0_0_12_V_4);
}

 void test::exe6510()
 { 
  //  Method no 65 mname=test
    if (T403_test_st5_0_27_V_1_GP<4&&xpc10nz==3/*3:xpc10nz*/)
    iuMULTIPLIER10_A0 = (T403_test_st0_0_12_V_3_GP);
}

 void test::exe6610()
 { 
  //  Method no 66 mname=test
    if (T403_test_st5_0_27_V_1_GP<4&&xpc10nz==4/*4:xpc10nz*/)
    T403_test_st3_0_21_V_3_GP = (T403_test_st0_0_12_V_3_GP+T403_test_st0_0_12_V_4);
}

 void test::exe6710()
 { 
  //  Method no 67 mname=test
    if (T403_test_st5_0_27_V_1_GP<4&&xpc10nz==4/*4:xpc10nz*/)
    T403_test_st4_0_24_V_0_GP = (((xpc10nz==4/*4:xpc10nz*/)?iuMULTIPLIER10_RR:iuMULTIPLIER10RRh10hold));
}

 void test::exe6810()
 { 
  //  Method no 68 mname=test
    if (T403_test_st5_0_27_V_1_GP>=4&&xpc10nz==3/*3:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (0);
}

 void test::exe6910()
 { 
  //  Method no 69 mname=test
    if (T403_test_st5_0_27_V_1_GP>=4&&xpc10nz==3/*3:xpc10nz*/)
    T403_test_st6_0_30_V_1_GP = (0x12345678);
}

 void test::exe7010()
 { 
  //  Method no 70 mname=test
    if (T403_test_st5_0_27_V_1_GP<2&&xpc10nz==5/*5:xpc10nz*/)
    T403_test_st6_0_30_V_1_GP = (0x100000+T403_test_st6_0_30_V_1_GP);
}

 void test::exe7110()
 { 
  //  Method no 71 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==5/*5:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (-1);
}

 void test::exe7210()
 { 
  //  Method no 72 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==5/*5:xpc10nz*/)
    T403_test_st4_0_24_V_0_GP = (0xffffffff);
}

 void test::exe7310()
 { 
  //  Method no 73 mname=test
    if (T403_test_st5_0_27_V_1_GP>=2&&xpc10nz==5/*5:xpc10nz*/)
    T403_test_st6_0_30_V_0_GP = (0);
}

 void test::exe7410()
 { 
  //  Method no 74 mname=test
    if (T403_test_st6_0_30_V_0_GP<3&&xpc10nz==6/*6:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (-1);
}

 void test::exe7510()
 { 
  //  Method no 75 mname=test
    if (T403_test_st6_0_30_V_0_GP<3&&xpc10nz==6/*6:xpc10nz*/)
    T403_test_st4_0_24_V_0_GP = (T403_test_st4_0_24_V_0_GP>>>8);
}

 void test::exe7610()
 { 
  //  Method no 76 mname=test
    if (T403_test_st6_0_30_V_0_GP>=3&&xpc10nz==6/*6:xpc10nz*/)
    T403_test_st6_0_30_V_0_GP = (-135);
}

 void test::exe7710()
 { 
  //  Method no 77 mname=test
    if (xpc10nz==7/*7:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (0);
}

 void test::exe7810()
 { 
  //  Method no 78 mname=test
    if (T403_test_st5_0_27_V_1_GP<2&&xpc10nz==8/*8:xpc10nz*/)
    T403_test_st6_0_30_V_0_GP = (~test_t1+~test_t2);
}

 void test::exe7910()
 { 
  //  Method no 79 mname=test
    if (xpc10nz==9/*9:xpc10nz*/)
    T403_test_st6_0_30_V_0_GP = (0);
}

 void test::exe8010()
 { 
  //  Method no 80 mname=test
    if (xpc10nz==11/*11:xpc10nz*/)
    T403_test_st6_0_30_V_1_GP = (0xff000000<<(63&16*T403_test_st6_0_30_V_0_GP));
}

 void test::exe8110()
 { 
  //  Method no 81 mname=test
    if (xpc10nz==14/*14:xpc10nz*/)
    T403_test_st6_0_30_V_0_GP = (1+T403_test_st6_0_30_V_0_GP);
}

 void test::exe8210()
 { 
  //  Method no 82 mname=test
    if (xpc10nz==15/*15:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (1+T403_test_st5_0_27_V_1_GP);
}

 void test::exe8310()
 { 
  //  Method no 83 mname=test
    if (xpc10nz==15/*15:xpc10nz*/)
    test_t2 = (test_t2>>1);
}

 void test::exe8410()
 { 
  //  Method no 84 mname=test
    if (xpc10nz==15/*15:xpc10nz*/)
    test_t1 = (test_t1<<1);
}

 void test::exe8510()
 { 
  //  Method no 85 mname=test
    if (xpc10nz==16/*16:xpc10nz*/)
    T403_test_st6_0_30_V_0_GP = (1+T403_test_st6_0_30_V_0_GP);
}

 void test::exe8610()
 { 
  //  Method no 86 mname=test
    if (xpc10nz==17/*17:xpc10nz*/)
    T403_test_st3_0_21_V_3_GP = ((unsigned int)(0xffff&T403_test_st6_0_30_V_1_GP));
}

 void test::exe8710()
 { 
  //  Method no 87 mname=test
    if (xpc10nz==17/*17:xpc10nz*/)
    T403_test_st4_0_24_V_0_GP = ((unsigned int)((unsigned short)(T403_test_st6_0_30_V_1_GP)));
}

 void test::exe8810()
 { 
  //  Method no 88 mname=test
    if (xpc10nz==18/*18:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (1+T403_test_st5_0_27_V_1_GP);
}

 void test::exe8910()
 { 
  //  Method no 89 mname=test
    if (xpc10nz==19/*19:xpc10nz*/)
    T403_test_st5_0_27_V_1_GP = (1+T403_test_st5_0_27_V_1_GP);
}

 void test::exe9010()
 { 
  //  Method no 90 mname=test
    if (xpc10nz==19/*19:xpc10nz*/)
    T403_test_st0_0_12_V_3_GP = ((unsigned char)(1+T403_test_st0_0_12_V_3_GP));
}

 void test::exe9110()
 { 
  //  Method no 91 mname=test
    if (xpc10nz==19/*19:xpc10nz*/)
    T403_test_st0_0_12_V_4 = ((unsigned char)(4+T403_test_st0_0_12_V_4));
}

 void test::exe010()
 { 
  //  Method no 0 mname=iuMULTIPLIER10.CV_INT_FL1_MULTIPLIER_US
    iuMULTIPLIER10_RR = (iuMULTIPLIER10_A0*iuMULTIPLIER10_A1);
}
// eof test
