// test39r1
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:56:20
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test39r1.exe -sim 1800 -restructure2=disable -conerefine=disable -bevelab=disable -verilog-gen=disable -repack=disable -give-backtrace -report-each-step

#ifndef test39r1_H
#define test39r1_H
#define HPR_NEEDS_SYSTEMC 1
#include "hprls.h"
// opath operation: 10: cgen2

struct  test39r1  : public sc_module
{
  unsigned int T403_LinkedListOfInts_alloc_1_6_V_3_GP;
  unsigned int test39r1_T403_Main_T403_Main_V_1;
  unsigned int T403_LinkedListOfInts_alloc_1_6_V_1;
  unsigned int test39r1_T403_Main_T403_Main_V_0;
  unsigned int test39r1_T403_Main_T403_Main_V_3_GP;
  sc_uint<1> WASANON16_blockrefreftran16;
  sc_uint<1> WASANON14_blockrefreftran14;
  sc_uint<1> WASANON12_blockrefreftran12;
  sc_uint<1> WASANON10_blockrefreftran10;
  unsigned int ktop16;
  unsigned int T402__cctor_CZ:0:10_blockrefxxnewobj12;
  unsigned int T402__cctor_CZ:0:8_blockrefxxnewobj10;
  unsigned char CS_0_6_refxxarray10;
  unsigned int LinkedListOfInts_locker;
  unsigned int LinkedListOfInts_ohandler;
  unsigned char LinkedListOfInts_heapPool;
  unsigned int LinkedListOfInts_sbrk;
  unsigned int LinkedListOfInts_freelist;
  unsigned int ktop14;
  sc_uint<1> System_BitConverter_IsLittleEndian;
  unsigned int ktop12;
  unsigned INT64 KiwiSystem_Kiwi_tnow;
  unsigned int KiwiSystem_Kiwi_old_pausemode_value;
  unsigned int ktop10;
  sc_in < sc_uint<1> > clk;

  test39r1( sc_core::sc_module_name name)  :    sc_core::sc_module("test39r1")
   { 
       SC_HAS_PROCESS(test39r1);
SC_METHOD(new SystemCsharp.sc_method_t(exe110)).sensitive_pos(clk);
SC_METHOD(new SystemCsharp.sc_method_t(exe010)).sensitive_pos(clk);
  }

   void exe010();

   int exe110();
};

#endif
// eof test39r1
