// test26
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:53:56
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test26.exe -diosim-vcd=test26.vcd -sim 1800 -give-backtrace -report-each-step

#include "test26.h"

// opath operation: 10: cgen2

 void test26::exe010()
 { 
  //  Method no 0 mname=test26
    if (xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test26::exe110()
 { 
  //  Method no 1 mname=test26
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test26::exe210()
 { 
  //  Method no 2 mname=test26
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test26::exe310()
 { 
  //  Method no 3 mname=test26
    if (xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("Test 26 mid point 1: fish=%u chips=%u", 46, 101);
}

 void test26::exe410()
 { 
  //  Method no 4 mname=test26
    if (xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("%i%s", 42, " ");
}

 void test26::exe510()
 { 
  //  Method no 5 mname=test26
    if (xpc10nz==2/*2:xpc10nz*/)
     hpr_sysexit(0);
}

 void test26::exe610()
 { 
  //  Method no 6 mname=test26
    if (xpc10nz==2/*2:xpc10nz*/)
     hpr_writeln("Test 26 finished.");
}

 void test26::exe710()
 { 
  //  Method no 7 mname=test26
    if (xpc10nz==2/*2:xpc10nz*/)
     hpr_writeln("Test 26 end point: fish=%u chips=%u", 46, 48);
}

 void test26::exe810()
 { 
  //  Method no 8 mname=test26
    if (xpc10nz==2/*2:xpc10nz*/)
     hpr_writeln("%i%s", 44, " ");
}
// eof test26
