// test3
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:48:26
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test3.exe -root test3;test3.Main -vnl VNL.v -sim 1800 -give-backtrace -report-each-step

#include "test3.h"

// opath operation: 10: cgen2

 void test3::exe010()
 { 
  //  Method no 0 mname=test3
    if (xpc10nz==7/*7:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test3::exe110()
 { 
  //  Method no 1 mname=test3
    if (xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (7/*7:xpc10nz*/);
}

 void test3::exe210()
 { 
  //  Method no 2 mname=test3
    if (1==T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test3::exe310()
 { 
  //  Method no 3 mname=test3
    if (6==T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test3::exe410()
 { 
  //  Method no 4 mname=test3
    if (17==T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test3::exe510()
 { 
  //  Method no 5 mname=test3
    if (1!=T402_ShiptonEnums_RunE2_5_2_V_0&&6!=T402_ShiptonEnums_RunE2_5_2_V_0&&17!=T402_ShiptonEnums_RunE2_5_2_V_0&&153==T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test3::exe610()
 { 
  //  Method no 6 mname=test3
    if (1!=T402_ShiptonEnums_RunE2_5_2_V_0&&6!=T402_ShiptonEnums_RunE2_5_2_V_0&&17!=T402_ShiptonEnums_RunE2_5_2_V_0&&153!=T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test3::exe710()
 { 
  //  Method no 7 mname=test3
    if (xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test3::exe810()
 { 
  //  Method no 8 mname=test3
    if ((test3_T402_Main_T402_Main_V_1!=0L)&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test3::exe910()
 { 
  //  Method no 9 mname=test3
    if (0==test3_T402_Main_T402_Main_V_1&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test3::exe1010()
 { 
  //  Method no 10 mname=test3
    if (test3_T402_Main_T402_Main_V_1<3&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test3::exe1110()
 { 
  //  Method no 11 mname=test3
    if (test3_T402_Main_T402_Main_V_1>=3&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test3::exe1210()
 { 
  //  Method no 12 mname=test3
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test3::exe1310()
 { 
  //  Method no 13 mname=test3
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test3::exe1410()
 { 
  //  Method no 14 mname=test3
    if (xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln(" yoko ");
}

 void test3::exe1510()
 { 
  //  Method no 15 mname=test3
    if (test3_T402_Main_T402_Main_V_1>=3&&xpc10nz==2/*2:xpc10nz*/)
     hpr_sysexit(0);
}

 void test3::exe1610()
 { 
  //  Method no 16 mname=test3
    if ((test3_T402_Main_T402_Main_V_1!=0L)&&xpc10nz==3/*3:xpc10nz*/)
     hpr_writeln("Run E2 %u", test3_T402_Main_T402_Main_V_1);
}

 void test3::exe1710()
 { 
  //  Method no 17 mname=test3
    if (0==test3_T402_Main_T402_Main_V_1&&xpc10nz==3/*3:xpc10nz*/)
     hpr_writeln("Run E2 %u", test3_T402_Main_T402_Main_V_1);
}

 void test3::exe1810()
 { 
  //  Method no 18 mname=test3
    if (1==T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln("  XAB");
}

 void test3::exe1910()
 { 
  //  Method no 19 mname=test3
    if (6==T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln("  XAA");
}

 void test3::exe2010()
 { 
  //  Method no 20 mname=test3
    if (17==T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln("  XAC");
}

 void test3::exe2110()
 { 
  //  Method no 21 mname=test3
    if (1!=T402_ShiptonEnums_RunE2_5_2_V_0&&6!=T402_ShiptonEnums_RunE2_5_2_V_0&&17!=T402_ShiptonEnums_RunE2_5_2_V_0&&153==T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln("  XAD");
}

 void test3::exe2210()
 { 
  //  Method no 22 mname=test3
    if (1!=T402_ShiptonEnums_RunE2_5_2_V_0&&6!=T402_ShiptonEnums_RunE2_5_2_V_0&&17!=T402_ShiptonEnums_RunE2_5_2_V_0&&153!=T402_ShiptonEnums_RunE2_5_2_V_0&&xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln("  Unknown value %h", (unsigned char)(T402_ShiptonEnums_RunE2_5_2_V_0));
}

 void test3::exe2310()
 { 
  //  Method no 23 mname=test3
    if (xpc10nz==7/*7:xpc10nz*/)
     hpr_writeln("  Enum pt one %d %d", T402_ShiptonEnums_RunE2_5_2_V_0, T402_ShiptonEnums_RunE2_5_2_V_0);
}

 void test3::exe2410()
 { 
  //  Method no 24 mname=test3
    if (xpc10nz==1/*1:xpc10nz*/)
    test3_T402_Main_T402_Main_V_1 = (0);
}

 void test3::exe2510()
 { 
  //  Method no 25 mname=test3
    if ((test3_T402_Main_T402_Main_V_1!=0L)&&xpc10nz==3/*3:xpc10nz*/)
    T402_ShiptonEnums_RunE2_5_2_V_0 = (test3_T402_Main_T402_Main_V_1);
}

 void test3::exe2610()
 { 
  //  Method no 26 mname=test3
    if (0==test3_T402_Main_T402_Main_V_1&&xpc10nz==3/*3:xpc10nz*/)
    T402_ShiptonEnums_RunE2_5_2_V_0 = (0x11);
}

 void test3::exe2710()
 { 
  //  Method no 27 mname=test3
    if (xpc10nz==7/*7:xpc10nz*/)
    test3_T402_Main_T402_Main_V_1 = (1+test3_T402_Main_T402_Main_V_1);
}
// eof test3
