// test41r1
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:56:38
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test41r1.exe -sim 1800 -vnl-resets=synchronous -vnl DUT.v -give-backtrace -report-each-step

#include "test41r1.h"

// opath operation: 10: cgen2

 void test41r1::exe014()
 { 
  //  Method no 0 mname=test41r1
    if ((xpc10nz==19/*19:xpc10nz*/&&isDIVIDER10_rdy)||(xpc10nz==19/*19:xpc10nz*/&&isDIVIDER10RRh10vld))
    if (isDIVIDER10RRh10vld||isDIVIDER10_rdy)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test41r1::exe114()
 { 
  //  Method no 1 mname=test41r1
    if (xpc10nz==18/*18:xpc10nz*/)
    xpc10nz = (19/*19:xpc10nz*/);
}

 void test41r1::exe212()
 { 
  //  Method no 2 mname=test41r1
    if (xpc10nz==17/*17:xpc10nz*/)
    xpc10nz = (18/*18:xpc10nz*/);
}

 void test41r1::exe310()
 { 
  //  Method no 3 mname=test41r1
    if (xpc10nz==16/*16:xpc10nz*/)
    xpc10nz = (17/*17:xpc10nz*/);
}

 void test41r1::exe410()
 { 
  //  Method no 4 mname=test41r1
    if (xpc10nz==15/*15:xpc10nz*/)
    xpc10nz = (16/*16:xpc10nz*/);
}

 void test41r1::exe510()
 { 
  //  Method no 5 mname=test41r1
    if (xpc10nz==14/*14:xpc10nz*/)
    xpc10nz = (15/*15:xpc10nz*/);
}

 void test41r1::exe610()
 { 
  //  Method no 6 mname=test41r1
    if (xpc10nz==13/*13:xpc10nz*/)
    xpc10nz = (14/*14:xpc10nz*/);
}

 void test41r1::exe710()
 { 
  //  Method no 7 mname=test41r1
    if (xpc10nz==12/*12:xpc10nz*/)
    xpc10nz = (13/*13:xpc10nz*/);
}

 void test41r1::exe810()
 { 
  //  Method no 8 mname=test41r1
    if (xpc10nz==11/*11:xpc10nz*/)
    xpc10nz = (12/*12:xpc10nz*/);
}

 void test41r1::exe910()
 { 
  //  Method no 9 mname=test41r1
    if (xpc10nz==10/*10:xpc10nz*/)
    xpc10nz = (11/*11:xpc10nz*/);
}

 void test41r1::exe1010()
 { 
  //  Method no 10 mname=test41r1
    if (xpc10nz==9/*9:xpc10nz*/)
    xpc10nz = (10/*10:xpc10nz*/);
}

 void test41r1::exe1110()
 { 
  //  Method no 11 mname=test41r1
    if (xpc10nz==8/*8:xpc10nz*/)
    xpc10nz = (9/*9:xpc10nz*/);
}

 void test41r1::exe1210()
 { 
  //  Method no 12 mname=test41r1
    if (xpc10nz==7/*7:xpc10nz*/)
    xpc10nz = (8/*8:xpc10nz*/);
}

 void test41r1::exe1310()
 { 
  //  Method no 13 mname=test41r1
    if (xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (7/*7:xpc10nz*/);
}

 void test41r1::exe1410()
 { 
  //  Method no 14 mname=test41r1
    if (xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test41r1::exe1510()
 { 
  //  Method no 15 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_4<120&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test41r1::exe1610()
 { 
  //  Method no 16 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_4>=120&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test41r1::exe1710()
 { 
  //  Method no 17 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_3_GP>=180&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test41r1::exe1810()
 { 
  //  Method no 18 mname=test41r1
    if (xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test41r1::exe1910()
 { 
  //  Method no 19 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_3_GP<180&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test41r1::exe2010()
 { 
  //  Method no 20 mname=test41r1
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test41r1::exe2110()
 { 
  //  Method no 21 mname=test41r1
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test41r1::exe2210()
 { 
  //  Method no 22 mname=test41r1
    xpc10_clear = (xpc10nz==4/*4:xpc10nz*/||xpc10nz==5/*5:xpc10nz*/||xpc10nz==2/*2:xpc10nz*/||xpc10nz==1/*1:xpc10nz*/||xpc10nz==0/*0:xpc10nz*/);
}

 void test41r1::exe2310()
 { 
  //  Method no 23 mname=test41r1
    if (xpc10nz==0/*0:xpc10nz*/&&!xpc10_stall)
     hpr_writeln("Start Kiwi test41r1");
}

 void test41r1::exe2410()
 { 
  //  Method no 24 mname=test41r1
    if (xpc10nz==1/*1:xpc10nz*/&&!xpc10_stall)
     hpr_writeln("The value of the integer: %u", 1024);
}

 void test41r1::exe2510()
 { 
  //  Method no 25 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_4>=120&&xpc10nz==4/*4:xpc10nz*/&&!xpc10_stall)
     hpr_sysexit(0);
}

 void test41r1::exe2610()
 { 
  //  Method no 26 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_4>=120&&xpc10nz==4/*4:xpc10nz*/&&!xpc10_stall)
     hpr_writeln("Press any key to exit.");
}

 void test41r1::exe2710()
 { 
  //  Method no 27 mname=test41r1
    if (xpc10nz==19/*19:xpc10nz*/&&!xpc10_stall)
     hpr_writeln("    dd=%u ss=%u", ((isDIVIDER10RRh10vld)?isDIVIDER10RRh10hold:isDIVIDER10_RR), test41r1_T402_Main_T402_Main_V_3_GP+(((isDIVIDER10RRh10vld)?isDIVIDER10RRh10hold:isDIVIDER10_RR)));
}

 void test41r1::exe2810()
 { 
  //  Method no 28 mname=test41r1
    if (xpc10nz==19/*19:xpc10nz*/&&!xpc10_stall)
     hpr_write("  readback vv=%u pp=%u qq=%u", test41r1_T402_Main_T402_Main_V_4, (int)(((xpc10nz==6/*6:xpc10nz*/)?__SINT_CC_SCALbx10_ARA0_RDD0:SINTCCSCALbx10ARA0RRh10hold)), (int)(((xpc10nz==7/*7:xpc10nz*/)?__SINT_CC_SCALbx10_ARA0_RDD0:SINTCCSCALbx10ARA0RRh12hold)));
}

 void test41r1::exe2910()
 { 
  //  Method no 29 mname=test41r1
    SINTCCSCALbx10ARA0RRh10shot0 = (xpc10nz==5/*5:xpc10nz*/&&!xpc10_stall);
}

 void test41r1::exe3010()
 { 
  //  Method no 30 mname=test41r1
    SINTCCSCALbx10ARA0RRh12shot0 = (xpc10nz==6/*6:xpc10nz*/&&!xpc10_stall);
}

 void test41r1::exe3110()
 { 
  //  Method no 31 mname=test41r1
    if (!xpc10_stall)
    __SINT_CC_SCALbx10_ARA0_WEN0 = (test41r1_T402_Main_T402_Main_V_3_GP<180&&xpc10nz==2/*2:xpc10nz*/);
}

 void test41r1::exe3210()
 { 
  //  Method no 32 mname=test41r1
    if (!xpc10_stall)
    __SINT_CC_SCALbx10_ARA0_REN0 = (((xpc10nz==6/*6:xpc10nz*/||xpc10nz==5/*5:xpc10nz*/)?1:0));
}

 void test41r1::exe3310()
 { 
  //  Method no 33 mname=test41r1
    if (!xpc10_stall)
    isDIVIDER10_req = (((xpc10nz==7/*7:xpc10nz*/)?1:0));
}

 void test41r1::exe3410()
 { 
  //  Method no 34 mname=test41r1
    if (isDIVIDER10_rdy&&isDIVIDER10RRh10primed)
    isDIVIDER10RRh10hold = (isDIVIDER10_RR);
}

 void test41r1::exe3510()
 { 
  //  Method no 35 mname=test41r1
    if (!xpc10_stall&&xpc10_clear)
    isDIVIDER10RRh10vld = (0);
}

 void test41r1::exe3610()
 { 
  //  Method no 36 mname=test41r1
    if (isDIVIDER10_rdy&&isDIVIDER10RRh10primed)
    isDIVIDER10RRh10vld = (1);
}

 void test41r1::exe3710()
 { 
  //  Method no 37 mname=test41r1
    if (isDIVIDER10_rdy&&isDIVIDER10RRh10primed)
    isDIVIDER10RRh10primed = (0);
}

 void test41r1::exe3810()
 { 
  //  Method no 38 mname=test41r1
    if (SINTCCSCALbx10ARA0RRh12shot0)
    SINTCCSCALbx10ARA0RRh12hold = (__SINT_CC_SCALbx10_ARA0_RDD0);
}

 void test41r1::exe3910()
 { 
  //  Method no 39 mname=test41r1
    if (SINTCCSCALbx10ARA0RRh10shot0)
    SINTCCSCALbx10ARA0RRh10hold = (__SINT_CC_SCALbx10_ARA0_RDD0);
}

 void test41r1::exe4010()
 { 
  //  Method no 40 mname=test41r1
    if (xpc10nz==0/*0:xpc10nz*/&&!xpc10_stall)
    test41r1_T402_Main_T402_Main_V_3_GP = (1024);
}

 void test41r1::exe4110()
 { 
  //  Method no 41 mname=test41r1
    if (xpc10nz==1/*1:xpc10nz*/&&!xpc10_stall)
    test41r1_T402_Main_T402_Main_V_3_GP = (100);
}

 void test41r1::exe4210()
 { 
  //  Method no 42 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_3_GP>=180&&xpc10nz==2/*2:xpc10nz*/&&!xpc10_stall)
    test41r1_T402_Main_T402_Main_V_3_GP = (0);
}

 void test41r1::exe4310()
 { 
  //  Method no 43 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_3_GP>=180&&xpc10nz==2/*2:xpc10nz*/&&!xpc10_stall)
    test41r1_T402_Main_T402_Main_V_4 = (110);
}

 void test41r1::exe4410()
 { 
  //  Method no 44 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_3_GP<180&&xpc10nz==2/*2:xpc10nz*/&&!xpc10_stall)
    test41r1_T402_Main_T402_Main_V_3_GP = (1+test41r1_T402_Main_T402_Main_V_3_GP);
}

 void test41r1::exe4510()
 { 
  //  Method no 45 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_3_GP<180&&xpc10nz==2/*2:xpc10nz*/&&!xpc10_stall)
    __SINT_CC_SCALbx10_ARA0_WRD0 = (-98+test41r1_T402_Main_T402_Main_V_3_GP);
}

 void test41r1::exe4610()
 { 
  //  Method no 46 mname=test41r1
    if (test41r1_T402_Main_T402_Main_V_3_GP<180&&xpc10nz==2/*2:xpc10nz*/&&!xpc10_stall)
    __SINT_CC_SCALbx10_ARA0_AD0 = (test41r1_T402_Main_T402_Main_V_3_GP);
}

 void test41r1::exe4710()
 { 
  //  Method no 47 mname=test41r1
    if (xpc10nz==5/*5:xpc10nz*/&&!xpc10_stall)
    __SINT_CC_SCALbx10_ARA0_AD0 = (test41r1_T402_Main_T402_Main_V_4);
}

 void test41r1::exe4810()
 { 
  //  Method no 48 mname=test41r1
    if (xpc10nz==6/*6:xpc10nz*/&&!xpc10_stall)
    __SINT_CC_SCALbx10_ARA0_AD0 = (40+test41r1_T402_Main_T402_Main_V_4);
}

 void test41r1::exe4910()
 { 
  //  Method no 49 mname=test41r1
    if (xpc10nz==7/*7:xpc10nz*/)
    isDIVIDER10RRh10primed = (!xpc10_stall);
}

 void test41r1::exe5010()
 { 
  //  Method no 50 mname=test41r1
    if (xpc10nz==7/*7:xpc10nz*/&&!xpc10_stall)
    isDIVIDER10_DD = ((int)(((xpc10nz==6/*6:xpc10nz*/)?__SINT_CC_SCALbx10_ARA0_RDD0:SINTCCSCALbx10ARA0RRh10hold)));
}

 void test41r1::exe5110()
 { 
  //  Method no 51 mname=test41r1
    if (xpc10nz==7/*7:xpc10nz*/&&!xpc10_stall)
    isDIVIDER10_NN = ((int)(((xpc10nz==7/*7:xpc10nz*/)?__SINT_CC_SCALbx10_ARA0_RDD0:SINTCCSCALbx10ARA0RRh12hold)));
}

 void test41r1::exe5210()
 { 
  //  Method no 52 mname=test41r1
    if (xpc10nz==19/*19:xpc10nz*/&&!xpc10_stall)
    test41r1_T402_Main_T402_Main_V_3_GP = (test41r1_T402_Main_T402_Main_V_3_GP+(((isDIVIDER10RRh10vld)?isDIVIDER10RRh10hold:isDIVIDER10_RR)));
}

 void test41r1::exe5310()
 { 
  //  Method no 53 mname=test41r1
    if (xpc10nz==19/*19:xpc10nz*/&&!xpc10_stall)
    test41r1_T402_Main_T402_Main_V_4 = (1+test41r1_T402_Main_T402_Main_V_4);
}

 void test41r1::exe5410()
 { 
  //  Method no 54 mname=test41r1
    xpc10_stall = (xpc10nz==19/*19:xpc10nz*/&&!isDIVIDER10RRh10vld&&!isDIVIDER10_rdy);
}

 void test41r1::exe012()
 { 
  //  Method no 0 mname=isDIVIDER10.CV_INT_VL_DIVIDER_S
    isDIVIDER10_rdy = (isDIVIDER10_req);
}

 void test41r1::exe112()
 { 
  //  Method no 1 mname=isDIVIDER10.CV_INT_VL_DIVIDER_S
    isDIVIDER10_RR = (isDIVIDER10_NN/isDIVIDER10_DD);
}

 void test41r1::exe010()
 { 
  //  Method no 0 mname=@_SINT/CC/SCALbx10_ARA0.RAM
    if (__SINT_CC_SCALbx10_ARA0_WEN0)
    __SINT_CC_SCALbx10_ARA0[__SINT_CC_SCALbx10_ARA0_AD0] = (__SINT_CC_SCALbx10_ARA0_WRD0);
}

 void test41r1::exe110()
 { 
  //  Method no 1 mname=@_SINT/CC/SCALbx10_ARA0.RAM
    __SINT_CC_SCALbx10_ARA0_RDD0 = (__SINT_CC_SCALbx10_ARA0[__SINT_CC_SCALbx10_ARA0_AD0]);
}

 void test41r1::exe210()
 { 
  //  Method no 2 mname=@_SINT/CC/SCALbx10_ARA0.RAM
// Resource=SRAM iname=i_@_SINT/CC/SCALbx10_ARA0 10000x32 clk=posedge(clk) synchronous/pipeline=1 no_ports=1 <NONE> used by threads xpc10
}
// eof test41r1
