// test57
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:58:23
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test57.exe -sim 1800 -compose=disable -vnl-rootmodname=DUT -vnl-resets=synchronous -bevelab=disable -verilog-gen=disable -repack=disable -conerefine=disable -restructure2=disable -give-backtrace -report-each-step

#ifndef test57_H
#define test57_H
#define HPR_NEEDS_SYSTEMC 1
#include "hprls.h"
// opath operation: 10: cgen2

struct  test57  : public sc_module
{
  unsigned int T402_test57_test57_phase0_0_6_V_1;
  sc_int<-1> T402_test57_test57_phase0_0_6_V_0;
  sc_int<-1> T402_test57_test57_phase0_0_6_V_2;
  sc_int<-1> T402_test57_test57_phase0_0_6__SPILL_256;
  unsigned int ktop14;
  sc_uint<1> System_BitConverter_IsLittleEndian;
  unsigned int ktop12;
  unsigned INT64 KiwiSystem_Kiwi_tnow;
  unsigned int KiwiSystem_Kiwi_old_pausemode_value;
  unsigned int ktop10;

  test57( sc_core::sc_module_name name)  :    sc_core::sc_module("test57")
   { 
       SC_HAS_PROCESS(test57);
SC_METHOD(new SystemCsharp.sc_method_t(exe010)).sensitive_pos(clk);
  }

   int exe010();
};

#endif
// eof test57
