// test_test2r2
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:48:19
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test2r2.exe -vnl-resets=synchronous -vnl DUT.v -sim 180 -give-backtrace -report-each-step

#include "test_test2r2.h"

// opath operation: 10: cgen2

 void test_test2r2::exe010()
 { 
  //  Method no 0 mname=test_test2r2
    if (xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test_test2r2::exe110()
 { 
  //  Method no 1 mname=test_test2r2
    if (T403_test_test2r2_process2_0_13_V_0<90&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test_test2r2::exe210()
 { 
  //  Method no 2 mname=test_test2r2
    if (T403_test_test2r2_process2_0_13_V_0>=90&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test_test2r2::exe310()
 { 
  //  Method no 3 mname=test_test2r2
    if (xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test_test2r2::exe410()
 { 
  //  Method no 4 mname=test_test2r2
    if (41!=test_test2r2_shared_var&&xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test_test2r2::exe510()
 { 
  //  Method no 5 mname=test_test2r2
    if (41==test_test2r2_shared_var&&xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test_test2r2::exe610()
 { 
  //  Method no 6 mname=test_test2r2
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test_test2r2::exe710()
 { 
  //  Method no 7 mname=test_test2r2
    if (xpc10nz==0/*0:xpc10nz*/)
     hpr_writeln("Note: this can be fragile owing to races.");
}

 void test_test2r2::exe810()
 { 
  //  Method no 8 mname=test_test2r2
    if (xpc10nz==0/*0:xpc10nz*/)
     hpr_writeln("Test2r2: Shared-variable test: Start");
}

 void test_test2r2::exe910()
 { 
  //  Method no 9 mname=test_test2r2
    if (41!=test_test2r2_shared_var&&xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("Process2 %u ", T403_test_test2r2_process2_0_13_V_0);
}

 void test_test2r2::exe1010()
 { 
  //  Method no 10 mname=test_test2r2
    if (41==test_test2r2_shared_var&&xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("Process2 spots Process1 %u %u ", T403_test_test2r2_process2_0_13_V_0, test_test2r2_shared_var);
}

 void test_test2r2::exe1110()
 { 
  //  Method no 11 mname=test_test2r2
    if (41==test_test2r2_shared_var&&xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("Process2 %u ", T403_test_test2r2_process2_0_13_V_0);
}

 void test_test2r2::exe1210()
 { 
  //  Method no 12 mname=test_test2r2
    if (xpc10nz==4/*4:xpc10nz*/)
     hpr_sysexit(0);
}

 void test_test2r2::exe1310()
 { 
  //  Method no 13 mname=test_test2r2
    if (xpc10nz==4/*4:xpc10nz*/)
     hpr_writeln("Test2r2: Shared-variable test: Finished");
}

 void test_test2r2::exe1410()
 { 
  //  Method no 14 mname=test_test2r2
    if (xpc10nz==0/*0:xpc10nz*/)
    T403_test_test2r2_process2_0_13_V_0 = (5);
}

 void test_test2r2::exe1510()
 { 
  //  Method no 15 mname=test_test2r2
    if (xpc10nz==2/*2:xpc10nz*/)
    test_test2r2_shared_var = (1+T403_test_test2r2_process2_0_13_V_0);
}

 void test_test2r2::exe1610()
 { 
  //  Method no 16 mname=test_test2r2
    if (T403_test_test2r2_process2_0_13_V_0<90&&xpc10nz==3/*3:xpc10nz*/)
    T403_test_test2r2_process2_0_13_V_0 = (10+T403_test_test2r2_process2_0_13_V_0);
}

 void test_test2r2::exe1710()
 { 
  //  Method no 17 mname=test_test2r2
    if (T403_test_test2r2_process2_0_13_V_0>=90&&xpc10nz==3/*3:xpc10nz*/)
    T403_test_test2r2_process2_0_13_V_0 = (10+T403_test_test2r2_process2_0_13_V_0);
}

 void test_test2r2::exe1810()
 { 
  //  Method no 18 mname=test_test2r2
    if (test_test2r2_T404_process1_T404_process1_V_0<90&&xpc12nz==2/*2:xpc12nz*/)
    xpc12nz = (1/*1:xpc12nz*/);
}

 void test_test2r2::exe1910()
 { 
  //  Method no 19 mname=test_test2r2
    if (test_test2r2_T404_process1_T404_process1_V_0>=90&&xpc12nz==2/*2:xpc12nz*/)
    xpc12nz = (2/*2:xpc12nz*/);
}

 void test_test2r2::exe2010()
 { 
  //  Method no 20 mname=test_test2r2
    if (xpc12nz==1/*1:xpc12nz*/)
    xpc12nz = (2/*2:xpc12nz*/);
}

 void test_test2r2::exe2110()
 { 
  //  Method no 21 mname=test_test2r2
    if (xpc12nz==0/*0:xpc12nz*/)
    xpc12nz = (1/*1:xpc12nz*/);
}

 void test_test2r2::exe2210()
 { 
  //  Method no 22 mname=test_test2r2
    if (xpc12nz==1/*1:xpc12nz*/)
     hpr_writeln("Process1 count=%u, shared_var=%u", test_test2r2_T404_process1_T404_process1_V_0, test_test2r2_shared_var);
}

 void test_test2r2::exe2310()
 { 
  //  Method no 23 mname=test_test2r2
    if (test_test2r2_T404_process1_T404_process1_V_0>=90&&xpc12nz==2/*2:xpc12nz*/)
     hpr_sysexit(0);
}

 void test_test2r2::exe2410()
 { 
  //  Method no 24 mname=test_test2r2
    if (xpc12nz==0/*0:xpc12nz*/)
    test_test2r2_T404_process1_T404_process1_V_0 = (0);
}

 void test_test2r2::exe2510()
 { 
  //  Method no 25 mname=test_test2r2
    if (xpc12nz==1/*1:xpc12nz*/)
    test_test2r2_shared_var = (1+test_test2r2_T404_process1_T404_process1_V_0);
}

 void test_test2r2::exe2610()
 { 
  //  Method no 26 mname=test_test2r2
    if (test_test2r2_T404_process1_T404_process1_V_0<90&&xpc12nz==2/*2:xpc12nz*/)
    test_test2r2_T404_process1_T404_process1_V_0 = (10+test_test2r2_T404_process1_T404_process1_V_0);
}

 void test_test2r2::exe2710()
 { 
  //  Method no 27 mname=test_test2r2
    if (test_test2r2_T404_process1_T404_process1_V_0>=90&&xpc12nz==2/*2:xpc12nz*/)
    test_test2r2_T404_process1_T404_process1_V_0 = (10+test_test2r2_T404_process1_T404_process1_V_0);
}
// eof test_test2r2
