// test1
// Generated by CBG Orangepath HPR/LS
// 6/30/2011 8:57:23 AM
//  /home/djg11/d320/hprls/kiwic/distro/lib/kiwic.exe -report-each-step -kiwic-oldunwind=enable -csharp-gen=enable test1.exe /home/djg11/d320/hprls/kiwic/distro/support/Kiwi.dll /home/djg11/d320/hprls/kiwic/distro/support/Kiwic.dll -finish true -plot b.plt -sim 2080 -vnl DUT.v -preserve-sequencer=true -simtl 0

using SystemCsharp;
// opath operation: 8: csharp-gen

class  test1  : sc_module
{
  sc_signal tTMT4Main_V_0;
  sc_signal mpc10;
  sc_in < bool > clk;

  test1( string name)  :    base("test1")
   { 
      clk = (new sc_in<bool>(this, "clk"));
      tTMT4Main_V_0 = (new sc_signal(32, "tTMT4Main_V_0"));
      mpc10 = (new sc_signal(32, "mpc10"));
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe12)).sensitive_pos(clk.Read());
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe10)).sensitive_pos(clk.Read());
  }

   void exe10()
   { 
    //  Method no 0 mname=test1

    {      if (((mpc10.Read())==(0)))
       hpr_writeln("%s%d", "Test 1 Limit=", 10);
      if (((mpc10.Read())==(2)))
       hpr_write("%d%s", 1, " ");
      if (((mpc10.Read())==(4))&&((tTMT4Main_V_0.Read())<(9)))
       hpr_write("%d%s", 2+tTMT4Main_V_0.Read(), " ");
      if (((mpc10.Read())==(4))&&((tTMT4Main_V_0.Read())>=(9)))
       hpr_writeln(" Test 1 finished.");
      if (((mpc10.Read())==(8)))
       hpr_sysexit(0);

    }
  }

   void exe12()
   { 
    //  Method no 1 mname=test1

    {      if (((mpc10.Read())==(0)))
      mpc10.Write(2/*2:mpc10XS:":pcIS22:AG"*/);
      if (((mpc10.Read())==(2)))
      mpc10.Write(4/*4:mpc10XS:":pcIS29:AG"*/);
      if (((mpc10.Read())==(4)))
      mpc10.Write((((tTMT4Main_V_0.Read())>=(9)))? 8/*8:mpc10*/:(((tTMT4Main_V_0.Read())<(9)))? 4/*4:mpc10*/:mpc10.Read());
      if (((mpc10.Read())==(8)))
      mpc10.Write(1/*1:mpc10XS:":pcIS-10:AG"*/);
      if (((mpc10.Read())==(2)))
      tTMT4Main_V_0.Write(1);
      if (((mpc10.Read())==(4)))
      tTMT4Main_V_0.Write(2+tTMT4Main_V_0.Read());

    }
  }
};

// eof test1
