// test1
// Generated by CBG Orangepath HPR/LS
// 8/3/2011 4:35:59 PM
//  /home/djg11/d320/hprls/kiwic/distro/lib/kiwic.exe -report-each-step -csharp-gen=enable -gtrace-loglevel=0 -firstpass-loglevel=0 test1.exe /home/djg11/d320/hprls/kiwic/distro/support/Kiwi.dll /home/djg11/d320/hprls/kiwic/distro/support/Kiwic.dll -finish true -plot b.plt -sim 2080 -vnl DUT.v -preserve-sequencer=true -simtl 0

using SystemCsharp;
// opath operation: 8: csharp-gen

public class  test1  : sc_module
{
  public sc_signal tTMT4Main_V_0;
  public sc_signal mpc10;
  public sc_in < bool > clk;

  public test1( string name)  :    base("test1")
   { 
      clk = (new sc_in<bool>(this, "clk"));
      tTMT4Main_V_0 = (new sc_signal(32, "tTMT4Main_V_0"));
      mpc10 = (new sc_signal(32, "mpc10"));
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe12)).sensitive_pos(clk);
SystemCsharp.SC.sc_method(new SystemCsharp.sc_method_t(exe10)).sensitive_pos(clk);
  }

   void exe10()
   { 
    //  Method no 0 mname=test1

    {      if (((mpc10.Read())==(0)))
       hpr_writeln("%s%d", "Test 1 Limit=", 10);
      if (((mpc10.Read())==(2)))
       hpr_write("%d%s", 1, " ");
      if (((mpc10.Read())==(4)))

    {      if (((tTMT4Main_V_0.Read())<(9)))
       hpr_write("%d%s", 2+tTMT4Main_V_0.Read(), " ");
      if (((tTMT4Main_V_0.Read())>=(9)))
       hpr_writeln(" Test 1 finished.");

    }
      if (((mpc10.Read())==(8)))
       hpr_sysexit(0);

    }
  }

   void exe12()
   { 
    //  Method no 1 mname=test1

    {      switch (mpc10.Read())     {
 
    case 2:
    
    {      mpc10.Write(4/*4:mpc10XS:":pcIS32:AG"*/);
      tTMT4Main_V_0.Write(1);

    }
    break;
    case 4:
    
    {      mpc10.Write((((tTMT4Main_V_0.Read())>=(9)))?8/*8:mpc10*/:(((tTMT4Main_V_0.Read())<(9)))?4/*4:mpc10*/:mpc10.Read());
      tTMT4Main_V_0.Write(2+tTMT4Main_V_0.Read());

    }
    break; }      if (((mpc10.Read())==(0)))
      mpc10.Write(2/*2:mpc10XS:":pcIS22:AG"*/);
      if (((mpc10.Read())==(8)))
      mpc10.Write(1/*1:mpc10XS:":pcIS-10:AG"*/);

    }
  }
};

// eof test1
