// test41r0
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:56:28
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test41r0.exe -sim 1800 -vnl-resets=synchronous -vnl DUT.v -give-backtrace -report-each-step

#include "test41r0.h"

// opath operation: 10: cgen2

 void test41r0::exe012()
 { 
  //  Method no 0 mname=test41r0
    if (xpc10nz==8/*8:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test41r0::exe112()
 { 
  //  Method no 1 mname=test41r0
    if (xpc10nz==7/*7:xpc10nz*/)
    xpc10nz = (8/*8:xpc10nz*/);
}

 void test41r0::exe212()
 { 
  //  Method no 2 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_5<120&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (7/*7:xpc10nz*/);
}

 void test41r0::exe310()
 { 
  //  Method no 3 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_5>=120&&xpc10nz==6/*6:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test41r0::exe410()
 { 
  //  Method no 4 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP>=117&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (6/*6:xpc10nz*/);
}

 void test41r0::exe510()
 { 
  //  Method no 5 mname=test41r0
    if (xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test41r0::exe610()
 { 
  //  Method no 6 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP<117&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test41r0::exe710()
 { 
  //  Method no 7 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP>=130&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test41r0::exe810()
 { 
  //  Method no 8 mname=test41r0
    if (xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test41r0::exe910()
 { 
  //  Method no 9 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP<130&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test41r0::exe1010()
 { 
  //  Method no 10 mname=test41r0
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test41r0::exe1110()
 { 
  //  Method no 11 mname=test41r0
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test41r0::exe1210()
 { 
  //  Method no 12 mname=test41r0
    if (xpc10nz==0/*0:xpc10nz*/)
     hpr_writeln("Running test41r0");
}

 void test41r0::exe1310()
 { 
  //  Method no 13 mname=test41r0
    if (xpc10nz==1/*1:xpc10nz*/)
     hpr_writeln("The value of the integer: %u", 2048);
}

 void test41r0::exe1410()
 { 
  //  Method no 14 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_5>=120&&xpc10nz==6/*6:xpc10nz*/)
     hpr_sysexit(0);
}

 void test41r0::exe1510()
 { 
  //  Method no 15 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_5>=120&&xpc10nz==6/*6:xpc10nz*/)
     hpr_writeln("Press any key to exit.");
}

 void test41r0::exe1610()
 { 
  //  Method no 16 mname=test41r0
    if (xpc10nz==8/*8:xpc10nz*/)
     hpr_writeln("  readback vv=%u rb=%u ss=%u", test41r0_T402_Main_T402_Main_V_5, (int)(((xpc10nz==8/*8:xpc10nz*/)?__SINT_CC_SCALbx10_ARA0_RDD0:SINTCCSCALbx10ARA0RRh10hold)), test41r0_T402_Main_T402_Main_V_4_GP+((int)(((xpc10nz==8/*8:xpc10nz*/)?__SINT_CC_SCALbx10_ARA0_RDD0:SINTCCSCALbx10ARA0RRh10hold))));
}

 void test41r0::exe1710()
 { 
  //  Method no 17 mname=test41r0
    SINTCCSCALbx10ARA0RRh10shot0 = (xpc10nz==7/*7:xpc10nz*/);
}

 void test41r0::exe1810()
 { 
  //  Method no 18 mname=test41r0
    __SINT_CC_SCALbx10_ARA0_WEN0 = ((test41r0_T402_Main_T402_Main_V_4_GP<117&&xpc10nz==4/*4:xpc10nz*/)||(test41r0_T402_Main_T402_Main_V_4_GP<130&&xpc10nz==2/*2:xpc10nz*/));
}

 void test41r0::exe1910()
 { 
  //  Method no 19 mname=test41r0
    __SINT_CC_SCALbx10_ARA0_REN0 = (((xpc10nz==7/*7:xpc10nz*/)?1:0));
}

 void test41r0::exe2010()
 { 
  //  Method no 20 mname=test41r0
    if (SINTCCSCALbx10ARA0RRh10shot0)
    SINTCCSCALbx10ARA0RRh10hold = (__SINT_CC_SCALbx10_ARA0_RDD0);
}

 void test41r0::exe2110()
 { 
  //  Method no 21 mname=test41r0
    if (xpc10nz==0/*0:xpc10nz*/)
    test41r0_T402_Main_T402_Main_V_4_GP = (2048);
}

 void test41r0::exe2210()
 { 
  //  Method no 22 mname=test41r0
    if (xpc10nz==1/*1:xpc10nz*/)
    test41r0_T402_Main_T402_Main_V_4_GP = (100);
}

 void test41r0::exe2310()
 { 
  //  Method no 23 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP>=130&&xpc10nz==2/*2:xpc10nz*/)
    test41r0_T402_Main_T402_Main_V_4_GP = (114);
}

 void test41r0::exe2410()
 { 
  //  Method no 24 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP<130&&xpc10nz==2/*2:xpc10nz*/)
    test41r0_T402_Main_T402_Main_V_4_GP = (1+test41r0_T402_Main_T402_Main_V_4_GP);
}

 void test41r0::exe2510()
 { 
  //  Method no 25 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP<130&&xpc10nz==2/*2:xpc10nz*/)
    __SINT_CC_SCALbx10_ARA0_WRD0 = (1000+test41r0_T402_Main_T402_Main_V_4_GP);
}

 void test41r0::exe2610()
 { 
  //  Method no 26 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP<130&&xpc10nz==2/*2:xpc10nz*/)
    __SINT_CC_SCALbx10_ARA0_AD0 = (test41r0_T402_Main_T402_Main_V_4_GP);
}

 void test41r0::exe2710()
 { 
  //  Method no 27 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP>=117&&xpc10nz==4/*4:xpc10nz*/)
    test41r0_T402_Main_T402_Main_V_4_GP = (0);
}

 void test41r0::exe2810()
 { 
  //  Method no 28 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP>=117&&xpc10nz==4/*4:xpc10nz*/)
    test41r0_T402_Main_T402_Main_V_5 = (110);
}

 void test41r0::exe2910()
 { 
  //  Method no 29 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP<117&&xpc10nz==4/*4:xpc10nz*/)
    test41r0_T402_Main_T402_Main_V_4_GP = (1+test41r0_T402_Main_T402_Main_V_4_GP);
}

 void test41r0::exe3010()
 { 
  //  Method no 30 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP<117&&xpc10nz==4/*4:xpc10nz*/)
    __SINT_CC_SCALbx10_ARA0_WRD0 = (2000+test41r0_T402_Main_T402_Main_V_4_GP);
}

 void test41r0::exe3110()
 { 
  //  Method no 31 mname=test41r0
    if (test41r0_T402_Main_T402_Main_V_4_GP<117&&xpc10nz==4/*4:xpc10nz*/)
    __SINT_CC_SCALbx10_ARA0_AD0 = (test41r0_T402_Main_T402_Main_V_4_GP);
}

 void test41r0::exe3210()
 { 
  //  Method no 32 mname=test41r0
    if (xpc10nz==7/*7:xpc10nz*/)
    __SINT_CC_SCALbx10_ARA0_AD0 = (test41r0_T402_Main_T402_Main_V_5);
}

 void test41r0::exe3310()
 { 
  //  Method no 33 mname=test41r0
    if (xpc10nz==8/*8:xpc10nz*/)
    test41r0_T402_Main_T402_Main_V_4_GP = (test41r0_T402_Main_T402_Main_V_4_GP+((int)(((xpc10nz==8/*8:xpc10nz*/)?__SINT_CC_SCALbx10_ARA0_RDD0:SINTCCSCALbx10ARA0RRh10hold))));
}

 void test41r0::exe3410()
 { 
  //  Method no 34 mname=test41r0
    if (xpc10nz==8/*8:xpc10nz*/)
    test41r0_T402_Main_T402_Main_V_5 = (1+test41r0_T402_Main_T402_Main_V_5);
}

 void test41r0::exe010()
 { 
  //  Method no 0 mname=@_SINT/CC/SCALbx10_ARA0.RAM
    if (__SINT_CC_SCALbx10_ARA0_WEN0)
    __SINT_CC_SCALbx10_ARA0[__SINT_CC_SCALbx10_ARA0_AD0] = (__SINT_CC_SCALbx10_ARA0_WRD0);
}

 void test41r0::exe110()
 { 
  //  Method no 1 mname=@_SINT/CC/SCALbx10_ARA0.RAM
    __SINT_CC_SCALbx10_ARA0_RDD0 = (__SINT_CC_SCALbx10_ARA0[__SINT_CC_SCALbx10_ARA0_AD0]);
}

 void test41r0::exe210()
 { 
  //  Method no 2 mname=@_SINT/CC/SCALbx10_ARA0.RAM
// Resource=SRAM iname=i_@_SINT/CC/SCALbx10_ARA0 10000x32 clk=posedge(clk) synchronous/pipeline=1 no_ports=1 <NONE> used by threads xpc10
}
// eof test41r0
