// test38r0
// Generated by CBG HPR L/S stagename=cgen2
//Kiwi Scientific Acceleration (KiwiC .net/CIL/C# to Verilog/SystemC compiler): Version alpha 0.2.18b : 5th-December-2016 Linux/X86_64:koo// 08/12/2016 06:55:33
//  /home/djg11/d320/hprls/kiwipro/kiwic/distro/lib/kiwic.exe -vnl-roundtrip=disable -report-each-step -kiwic-finish=enable -kiwic-register-colours=1 -repack-to-roms=disable test38r0.exe -sim 1800 -vnl-resets=synchronous -vnl DUT.v -give-backtrace -report-each-step

#include "test38r0.h"

// opath operation: 10: cgen2

 void test38r0::exe010()
 { 
  //  Method no 0 mname=test38r0
    if (xpc10nz==5/*5:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test38r0::exe110()
 { 
  //  Method no 1 mname=test38r0
    if (__star1__TestClass_CC_SCALbx10_SCALARC0_0!=0/*0:USA10*/&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test38r0::exe210()
 { 
  //  Method no 2 mname=test38r0
    if (__star1__TestClass_CC_SCALbx10_SCALARC0_0==0/*0:USA10*/&&xpc10nz==4/*4:xpc10nz*/)
    xpc10nz = (5/*5:xpc10nz*/);
}

 void test38r0::exe310()
 { 
  //  Method no 3 mname=test38r0
    if (__star1__TestClass_CC_SCALbx10_SCALARC0_0!=1/*1:USA10*/&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test38r0::exe410()
 { 
  //  Method no 4 mname=test38r0
    if (__star1__TestClass_CC_SCALbx10_SCALARC0_0==1/*1:USA10*/&&xpc10nz==3/*3:xpc10nz*/)
    xpc10nz = (4/*4:xpc10nz*/);
}

 void test38r0::exe510()
 { 
  //  Method no 5 mname=test38r0
    if (__star1__TestClass_CC_SCALbx10_SCALARC0_0!=2/*2:USA10*/&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test38r0::exe610()
 { 
  //  Method no 6 mname=test38r0
    if (__star1__TestClass_CC_SCALbx10_SCALARC0_0==2/*2:USA10*/&&xpc10nz==2/*2:xpc10nz*/)
    xpc10nz = (3/*3:xpc10nz*/);
}

 void test38r0::exe710()
 { 
  //  Method no 7 mname=test38r0
    if (xpc10nz==1/*1:xpc10nz*/)
    xpc10nz = (2/*2:xpc10nz*/);
}

 void test38r0::exe810()
 { 
  //  Method no 8 mname=test38r0
    if (xpc10nz==0/*0:xpc10nz*/)
    xpc10nz = (1/*1:xpc10nz*/);
}

 void test38r0::exe910()
 { 
  //  Method no 9 mname=test38r0
    if (xpc10nz==0/*0:xpc10nz*/)
     hpr_writeln("Test38r0 start.");
}

 void test38r0::exe1010()
 { 
  //  Method no 10 mname=test38r0
    if (xpc10nz==5/*5:xpc10nz*/)
     hpr_sysexit(0);
}

 void test38r0::exe1110()
 { 
  //  Method no 11 mname=test38r0
    if (xpc10nz==5/*5:xpc10nz*/)
     hpr_writeln("Test38r0 finished.");
}

 void test38r0::exe1210()
 { 
  //  Method no 12 mname=test38r0
    if (xpc10nz==0/*0:xpc10nz*/)
    __star1__TestClass_CC_SCALbx10_SCALARC0_0 = (d4.2);
}

 void test38r0::exe1310()
 { 
  //  Method no 13 mname=test38r0
    if (xpc10nz==0/*0:xpc10nz*/)
    __star1__TestClass_CC_SCALbx10_SCALARB1_0 = (d3.1);
}

 void test38r0::exe1410()
 { 
  //  Method no 14 mname=test38r0
    if (xpc10nz==1/*1:xpc10nz*/)
    __star1__TestClass_CC_SCALbx10_SCALARC0_0 = (__star1__TestClass_CC_SCALbx10_SCALARB1_0);
}
// eof test38r0
